/** home-screen dictionary; zh defines the key set, en must match (type-checked) */
export const strings = {
  zh: {
    // Sidebar navigation
    navRecent: '最近',
    navStarred: '收藏',
    cloudSortRecent: '最近',
    cloudSortOldest: '最早',
    navTrash: '回收站',
    navTrashTip: '删除的文件在系统废纸篓中，可从那里还原',
    secQuickStart: '快速开始',
    secRecent: '最近使用',
    secStarred: '收藏',
    secProjectFiles: '项目文件',
    secActivity: '项目动态',
    colName: '名称',
    colLocation: '位置',
    colModified: '修改时间',
    colSize: '大小',
    // Quick start
    openLocal: '打开本地文件',
    quickAiPpt: 'AI PPT',
    quickAiPptSub: '用一句话生成专业演示文稿',
    greetMorning: '早上好',
    greetAfternoon: '下午好',
    greetEvening: '晚上好',
    greetAsk1: '今天想创建点什么？',
    greetAsk2: '准备好开始了吗？',
    greetAsk3: '有什么想做的吗？',
    greetAsk4: '今天从哪里开始？',
    greetAsk5: '想做点什么新的？',
    greetAsk6: '灵感来了吗？',
    // Filters
    filterAll: '全部',
    filterSlides: '演示',
    filterAria: '按类型筛选',
    // List / bulk actions
    fileCount: '{n} 个文件',
    fileCountOne: '{n} 个文件',
    selectedCount: '已选 {n} 项',
    selectAll: '全选',
    selectFile: '选择 {name}',
    removeFromList: '从列表中移除',
    deleteFiles: '删除文件',
    cancel: '取消',
    star: '收藏',
    unstar: '取消收藏',
    moreActions: '更多操作',
    open: '打开',
    revealInFolder: '打开所在文件夹',
    copyPath: '复制路径',
    moveToProject: '移动到项目',
    rename: '重命名',
    duplicate: '创建副本',
    renameFailed: '重命名失败',
    emptyStarred: '还没有收藏 — 悬浮文件行并点击星标即可收藏。',
    emptyRecent: '暂无最近文件 — 新建或打开一个文件开始使用。',
    emptyFiltered: '该类型下暂无文件。',
    // Delete confirmation dialog
    deleteModalTitle: '删除文件',
    deleteConfirmOne: '确定将"{name}"移到废纸篓？',
    deleteConfirmMany: '确定将以下 {n} 个文件移到废纸篓？',
    deleteMoreCount: '… 等共 {n} 个',
    delete: '删除',
    // Project sidebar
    projects: '项目',
    newProject: '新建项目',
    projectName: '项目名称',
    deleteProject: '删除项目…',
    deleteProjectConfirm: '删除该项目？\n项目下的文件将回归"默认项目"，不会丢失。',
    projMoreActions: '{name} 更多操作',
    defaultProject: '默认项目',
    projEmpty: '把相关文档放进同一个项目，AI 对话历史会按项目沉淀。',
    projEmptyHint: '新建文件或从"最近文件"右键选择"移动到项目"。',
    timelineCount: '{n} 条',
    timelineCountOne: '{n} 条',
    timelineEmpty: '该项目还没有 AI 对话记录。',
    timelineYou: '你',
    timelineUserAria: '用户',
    untitled: '未命名',
    noContent: '（无内容）',
    // Account
    appVersion: '版本 {v}',
    versionLabel: '版本',
    theme: '主题',
    themeLight: '浅色',
    themeDark: '深色',
    themeSystem: '跟随系统',
    saveLocation: '默认保存位置',
    settings: '设置',
    setSecGeneral: '通用',
    setSecAbout: '关于',
    setChange: '更改',
    // Dates
    today: '今天',
    yesterday: '昨天',
    daysAgo: '{n}天前',
    // Language / tab strip
    language: '语言',
    closeTab: '关闭标签',
    tabList: '全部标签',
    newTab: '新建标签页',
    // First-run onboarding
    onbTitle1: '欢迎使用 byeppt',
    onbSubtitle1: '开源的 AI 原生演示文稿工作室',
    onbBody1: '用一句话生成演示文稿，再逐像素精修。AI 深度融入每个环节。',
    onbTitle2: '这只是一个开始',
    onbBody2: 'byeppt 目前处于早期阶段，欢迎反馈建议，一起塑造它的未来。',
    onbSkip: '跳过',
    onbNext: '下一步',
    onbStart: '开始使用',
    onbStepAria: '第 {n} 页，共 {total} 页',
    onbTitle3: '人人免费',
    onbBody3: '无授权费用，无广告，无水印。',
    onbBack: '上一步',
  },
  en: {
    navRecent: 'Recent',
    navStarred: 'Starred',
    cloudSortRecent: 'Recent',
    cloudSortOldest: 'Oldest',
    navTrash: 'Trash',
    navTrashTip: 'Deleted files go to the system Trash and can be restored there',
    secQuickStart: 'Quick start',
    secRecent: 'Recent',
    secStarred: 'Starred',
    secProjectFiles: 'Project files',
    secActivity: 'Activity',
    colName: 'Name',
    colLocation: 'Location',
    colModified: 'Modified',
    colSize: 'Size',
    openLocal: 'Open Local File',
    quickAiPpt: 'AI PPT',
    quickAiPptSub: 'Generate a professional deck from a prompt',
    greetMorning: 'Good morning',
    greetAfternoon: 'Good afternoon',
    greetEvening: 'Good evening',
    greetAsk1: 'What would you like to create today?',
    greetAsk2: 'Ready to get started?',
    greetAsk3: 'What are you working on?',
    greetAsk4: 'Where shall we begin today?',
    greetAsk5: 'Feeling creative?',
    greetAsk6: "What's next on your mind?",
    filterAll: 'All',
    filterSlides: 'Slides',
    filterAria: 'Filter by type',
    fileCount: '{n} files',
    fileCountOne: '{n} file',
    selectedCount: '{n} selected',
    selectAll: 'Select all',
    selectFile: 'Select {name}',
    removeFromList: 'Remove from list',
    deleteFiles: 'Delete files',
    cancel: 'Cancel',
    star: 'Star',
    unstar: 'Unstar',
    moreActions: 'More actions',
    open: 'Open',
    revealInFolder: 'Reveal in folder',
    copyPath: 'Copy path',
    moveToProject: 'Move to project',
    rename: 'Rename',
    duplicate: 'Duplicate',
    renameFailed: 'Rename failed',
    emptyStarred: 'No starred files — hover a row and click the star.',
    emptyRecent: 'No recent files — create or open a file to get started.',
    emptyFiltered: 'No files of this type.',
    deleteModalTitle: 'Delete Files',
    deleteConfirmOne: 'Move "{name}" to the Trash?',
    deleteConfirmMany: 'Move these {n} files to the Trash?',
    deleteMoreCount: '… {n} in total',
    delete: 'Delete',
    projects: 'Projects',
    newProject: 'New project',
    projectName: 'Project name',
    deleteProject: 'Delete project…',
    deleteProjectConfirm:
      "Delete this project?\nIts files will return to the Default project and won't be lost.",
    projMoreActions: 'More actions for {name}',
    defaultProject: 'Default project',
    projEmpty: 'Keep related documents in one project — AI chat history accumulates per project.',
    projEmptyHint: 'Create a file, or right-click a recent file and choose "Move to project".',
    timelineCount: '{n} items',
    timelineCountOne: '{n} item',
    timelineEmpty: 'No AI conversations in this project yet.',
    timelineYou: 'You',
    timelineUserAria: 'User',
    untitled: 'Untitled',
    noContent: '(empty)',
    appVersion: 'Version {v}',
    versionLabel: 'Version',
    theme: 'Theme',
    themeLight: 'Light',
    themeDark: 'Dark',
    themeSystem: 'Follow System',
    saveLocation: 'Save Location',
    settings: 'Settings',
    setSecGeneral: 'General',
    setSecAbout: 'About',
    setChange: 'Change',
    today: 'Today',
    yesterday: 'Yesterday',
    daysAgo: '{n}d ago',
    language: 'Language',
    closeTab: 'Close tab',
    tabList: 'All tabs',
    newTab: 'New tab',
    // First-run onboarding
    onbTitle1: 'Welcome to byeppt',
    onbSubtitle1: 'The open-source, AI-native presentation studio',
    onbBody1: 'Generate a deck from a sentence, then refine every pixel. AI is woven into every step.',
    onbTitle2: 'This is just the beginning',
    onbBody2: 'byeppt is still early — your feedback shapes what comes next.',
    onbSkip: 'Skip',
    onbNext: 'Next',
    onbStart: 'Get started',
    onbStepAria: 'Page {n} of {total}',
    onbTitle3: 'Free for everyone',
    onbBody3: 'No license fees. No ads. No watermarks.',
    onbBack: 'Back',
  },
  ja: {
    // Sidebar navigation
    navRecent: '最近使用',
    navStarred: 'お気に入り',
    cloudSortRecent: '新しい順',
    cloudSortOldest: '古い順',
    navTrash: 'ゴミ箱',
    navTrashTip: '削除したファイルはシステムのゴミ箱に移動され、そこから復元できます',
    // Section headings
    secQuickStart: 'クイックスタート',
    secRecent: '最近使用',
    secStarred: 'お気に入り',
    secProjectFiles: 'プロジェクトファイル',
    secActivity: 'アクティビティ',
    colName: '名前',
    colLocation: '場所',
    colModified: '更新日時',
    colSize: 'サイズ',
    // Quick start
    openLocal: 'ローカルファイルを開く',
    quickAiPpt: 'AI PPT',
    quickAiPptSub: '一言でプロのプレゼンを生成',
    greetMorning: 'おはようございます',
    greetAfternoon: 'こんにちは',
    greetEvening: 'こんばんは',
    greetAsk1: '今日は何を作りますか？',
    greetAsk2: '準備はできましたか？',
    greetAsk3: '何か作りたいものはありますか？',
    greetAsk4: '今日はどこから始めますか？',
    greetAsk5: '新しいことに挑戦しますか？',
    greetAsk6: 'インスピレーションは湧きましたか？',
    // Filters
    filterAll: 'すべて',
    filterSlides: 'プレゼンテーション',
    filterAria: '種類で絞り込み',
    // List / bulk actions
    fileCount: '{n} 個のファイル',
    fileCountOne: '{n} 個のファイル',
    selectedCount: '{n} 件選択中',
    selectAll: 'すべて選択',
    selectFile: '{name} を選択',
    removeFromList: 'リストから削除',
    deleteFiles: 'ファイルを削除',
    cancel: 'キャンセル',
    star: 'お気に入りに追加',
    unstar: 'お気に入りから削除',
    moreActions: 'その他の操作',
    open: '開く',
    revealInFolder: 'フォルダーで表示',
    copyPath: 'パスをコピー',
    moveToProject: 'プロジェクトに移動',
    rename: '名前の変更',
    duplicate: '複製を作成',
    renameFailed: '名前の変更に失敗しました',
    emptyStarred:
      'お気に入りはまだありません — ファイルの行にカーソルを合わせて星マークをクリックしてください。',
    emptyRecent: '最近使ったファイルはありません — 新規作成するかファイルを開いて始めましょう。',
    emptyFiltered: 'この種類のファイルはありません。',
    // Delete confirmation dialog
    deleteModalTitle: 'ファイルの削除',
    deleteConfirmOne: '「{name}」をゴミ箱に移動しますか？',
    deleteConfirmMany: '次の {n} 個のファイルをゴミ箱に移動しますか？',
    deleteMoreCount: '… ほか、計 {n} 個',
    delete: '削除',
    // Project sidebar
    projects: 'プロジェクト',
    newProject: '新規プロジェクト',
    projectName: 'プロジェクト名',
    deleteProject: 'プロジェクトを削除…',
    deleteProjectConfirm:
      'このプロジェクトを削除しますか？\nプロジェクト内のファイルは「既定のプロジェクト」に戻り、失われることはありません。',
    projMoreActions: '{name} のその他の操作',
    defaultProject: '既定のプロジェクト',
    projEmpty:
      '関連するドキュメントを同じプロジェクトにまとめると、AI との会話履歴がプロジェクトごとに蓄積されます。',
    projEmptyHint:
      '新規ファイルを作成するか、「最近使用」のファイルを右クリックして「プロジェクトに移動」を選択してください。',
    timelineCount: '{n} 件',
    timelineCountOne: '{n} 件',
    timelineEmpty: 'このプロジェクトにはまだ AI との会話履歴がありません。',
    timelineYou: 'あなた',
    timelineUserAria: 'ユーザー',
    untitled: '無題',
    noContent: '（内容なし）',
    // Account
    appVersion: 'バージョン {v}',
    versionLabel: 'バージョン',
    theme: 'テーマ',
    themeLight: 'ライト',
    themeDark: 'ダーク',
    themeSystem: 'システムに従う',
    saveLocation: '保存先',
    settings: '設定',
    setSecGeneral: '一般',
    setSecAbout: '情報',
    setChange: '変更',
    // Dates
    today: '今日',
    yesterday: '昨日',
    daysAgo: '{n}日前',
    // Language / tab strip
    language: '言語',
    closeTab: 'タブを閉じる',
    tabList: 'すべてのタブ',
    newTab: '新しいタブ',
    // First-run onboarding
    onbTitle1: 'byeppt へようこそ',
    onbSubtitle1: 'オープンソースの AI ネイティブ・プレゼンテーションスタジオ',
    onbBody1: '一文からデッキを生成し、細部まで磨き上げる。AI がすべての工程に溶け込んでいます。',
    onbTitle2: 'これはまだ始まりにすぎません',
    onbBody2: 'byeppt はまだ初期段階です。フィードバックがこれからを形作ります。',
    onbSkip: 'スキップ',
    onbNext: '次へ',
    onbStart: 'はじめる',
    onbStepAria: '{total} ページ中 {n} ページ目',
    onbTitle3: 'すべての人に無料',
    onbBody3: 'ライセンス料なし、広告なし、透かしなし。',
    onbBack: '戻る',
  },
  ko: {
    // Sidebar navigation
    navRecent: '최근 사용',
    navStarred: '즐겨찾기',
    cloudSortRecent: '최신순',
    cloudSortOldest: '오래된순',
    navTrash: '휴지통',
    navTrashTip: '삭제된 파일은 시스템 휴지통으로 이동되며 그곳에서 복원할 수 있습니다',
    // Section headings
    secQuickStart: '빠른 시작',
    secRecent: '최근 사용',
    secStarred: '즐겨찾기',
    secProjectFiles: '프로젝트 파일',
    secActivity: '활동',
    colName: '이름',
    colLocation: '위치',
    colModified: '수정한 날짜',
    colSize: '크기',
    // Quick start
    openLocal: '로컬 파일 열기',
    quickAiPpt: 'AI PPT',
    quickAiPptSub: '한 문장으로 전문 프레젠테이션 생성',
    greetMorning: '좋은 아침이에요',
    greetAfternoon: '안녕하세요',
    greetEvening: '좋은 저녁이에요',
    greetAsk1: '오늘은 무엇을 만들까요?',
    greetAsk2: '시작할 준비가 되셨나요?',
    greetAsk3: '무엇을 하고 싶으신가요?',
    greetAsk4: '오늘 어디서부터 시작할까요?',
    greetAsk5: '새로운 걸 만들어 볼까요?',
    greetAsk6: '아이디어가 떠오르셨나요?',
    // Filters
    filterAll: '전체',
    filterSlides: '프레젠테이션',
    filterAria: '유형별 필터',
    // List / bulk actions
    fileCount: '파일 {n}개',
    fileCountOne: '파일 {n}개',
    selectedCount: '{n}개 선택됨',
    selectAll: '모두 선택',
    selectFile: '{name} 선택',
    removeFromList: '목록에서 제거',
    deleteFiles: '파일 삭제',
    cancel: '취소',
    star: '즐겨찾기에 추가',
    unstar: '즐겨찾기에서 제거',
    moreActions: '기타 작업',
    open: '열기',
    revealInFolder: '폴더에서 보기',
    copyPath: '경로 복사',
    moveToProject: '프로젝트로 이동',
    rename: '이름 바꾸기',
    duplicate: '복사본 만들기',
    renameFailed: '이름 바꾸기에 실패했습니다',
    emptyStarred: '즐겨찾기가 없습니다 — 파일 행에 마우스를 올리고 별표를 클릭하세요.',
    emptyRecent: '최근 파일이 없습니다 — 새로 만들거나 파일을 열어 시작하세요.',
    emptyFiltered: '이 유형의 파일이 없습니다.',
    // Delete confirmation dialog
    deleteModalTitle: '파일 삭제',
    deleteConfirmOne: '"{name}"을(를) 휴지통으로 이동하시겠습니까?',
    deleteConfirmMany: '다음 {n}개 파일을 휴지통으로 이동하시겠습니까?',
    deleteMoreCount: '… 외 총 {n}개',
    delete: '삭제',
    // Project sidebar
    projects: '프로젝트',
    newProject: '새 프로젝트',
    projectName: '프로젝트 이름',
    deleteProject: '프로젝트 삭제…',
    deleteProjectConfirm:
      '이 프로젝트를 삭제하시겠습니까?\n프로젝트의 파일은 "기본 프로젝트"로 돌아가며 사라지지 않습니다.',
    projMoreActions: '{name}의 기타 작업',
    defaultProject: '기본 프로젝트',
    projEmpty: '관련 문서를 하나의 프로젝트에 모아 두면 AI 대화 기록이 프로젝트별로 쌓입니다.',
    projEmptyHint:
      '새 파일을 만들거나 "최근 사용"에서 파일을 마우스 오른쪽 버튼으로 클릭해 "프로젝트로 이동"을 선택하세요.',
    timelineCount: '{n}건',
    timelineCountOne: '{n}건',
    timelineEmpty: '이 프로젝트에는 아직 AI 대화 기록이 없습니다.',
    timelineYou: '나',
    timelineUserAria: '사용자',
    untitled: '제목 없음',
    noContent: '(내용 없음)',
    // Account
    appVersion: '버전 {v}',
    versionLabel: '버전',
    theme: '테마',
    themeLight: '라이트',
    themeDark: '다크',
    themeSystem: '시스템 설정 따르기',
    saveLocation: '저장 위치',
    settings: '설정',
    setSecGeneral: '일반',
    setSecAbout: '정보',
    setChange: '변경',
    // Dates
    today: '오늘',
    yesterday: '어제',
    daysAgo: '{n}일 전',
    // Language / tab strip
    language: '언어',
    closeTab: '탭 닫기',
    tabList: '모든 탭',
    newTab: '새 탭',
    // First-run onboarding
    onbTitle1: 'byeppt에 오신 것을 환영합니다',
    onbSubtitle1: '오픈 소스 AI 네이티브 프레젠테이션 스튜디오',
    onbBody1: '한 문장으로 덱을 생성하고 픽셀 단위로 다듬으세요. AI가 모든 단계에 깊이 통합되어 있습니다.',
    onbTitle2: '이제 시작일 뿐입니다',
    onbBody2: 'byeppt는 아직 초기 단계입니다. 여러분의 피드백이 앞으로를 만듭니다.',
    onbSkip: '건너뛰기',
    onbNext: '다음',
    onbStart: '시작하기',
    onbStepAria: '총 {total}페이지 중 {n}페이지',
    onbTitle3: '모두에게 무료',
    onbBody3: '라이선스 비용 없음, 광고 없음, 워터마크 없음.',
    onbBack: '이전',
  },
  fr: {
    // Sidebar navigation
    navRecent: 'Récents',
    navStarred: 'Favoris',
    cloudSortRecent: 'Récents',
    cloudSortOldest: 'Plus anciens',
    navTrash: 'Corbeille',
    navTrashTip:
      'Les fichiers supprimés sont placés dans la corbeille du système et peuvent y être restaurés',
    // Section headings
    secQuickStart: 'Démarrage rapide',
    secRecent: 'Récents',
    secStarred: 'Favoris',
    secProjectFiles: 'Fichiers du projet',
    secActivity: 'Activité',
    colName: 'Nom',
    colLocation: 'Emplacement',
    colModified: 'Modifié le',
    colSize: 'Taille',
    // Quick start
    openLocal: 'Ouvrir un fichier local',
    quickAiPpt: 'AI PPT',
    quickAiPptSub: 'Générez une présentation pro à partir d’une phrase',
    greetMorning: 'Bonjour',
    greetAfternoon: 'Bonjour',
    greetEvening: 'Bonsoir',
    greetAsk1: 'Que souhaitez-vous créer aujourd’hui ?',
    greetAsk2: 'Prêt à commencer ?',
    greetAsk3: 'Sur quoi travaillez-vous ?',
    greetAsk4: 'Par où commencer aujourd’hui ?',
    greetAsk5: 'Envie de créer quelque chose de nouveau ?',
    greetAsk6: 'Une idée en tête ?',
    // Filters
    filterAll: 'Tous',
    filterSlides: 'Présentations',
    filterAria: 'Filtrer par type',
    // List / bulk actions
    fileCount: '{n} fichiers',
    fileCountOne: '{n} fichier',
    selectedCount: '{n} sélectionné(s)',
    selectAll: 'Tout sélectionner',
    selectFile: 'Sélectionner {name}',
    removeFromList: 'Retirer de la liste',
    deleteFiles: 'Supprimer les fichiers',
    cancel: 'Annuler',
    star: 'Ajouter aux favoris',
    unstar: 'Retirer des favoris',
    moreActions: 'Autres actions',
    open: 'Ouvrir',
    revealInFolder: 'Afficher dans le dossier',
    copyPath: 'Copier le chemin',
    moveToProject: 'Déplacer vers un projet',
    rename: 'Renommer',
    duplicate: 'Dupliquer',
    renameFailed: 'Échec du renommage',
    emptyStarred: "Aucun favori — survolez une ligne et cliquez sur l'étoile.",
    emptyRecent: 'Aucun fichier récent — créez ou ouvrez un fichier pour commencer.',
    emptyFiltered: 'Aucun fichier de ce type.',
    // Delete confirmation dialog
    deleteModalTitle: 'Supprimer les fichiers',
    deleteConfirmOne: 'Déplacer « {name} » vers la corbeille ?',
    deleteConfirmMany: 'Déplacer ces {n} fichiers vers la corbeille ?',
    deleteMoreCount: '… {n} au total',
    delete: 'Supprimer',
    // Project sidebar
    projects: 'Projets',
    newProject: 'Nouveau projet',
    projectName: 'Nom du projet',
    deleteProject: 'Supprimer le projet…',
    deleteProjectConfirm:
      'Supprimer ce projet ?\nSes fichiers retourneront dans le projet par défaut et ne seront pas perdus.',
    projMoreActions: 'Autres actions pour {name}',
    defaultProject: 'Projet par défaut',
    projEmpty:
      "Regroupez les documents associés dans un même projet — l'historique des conversations IA s'accumule par projet.",
    projEmptyHint:
      'Créez un fichier, ou cliquez avec le bouton droit sur un fichier récent et choisissez « Déplacer vers un projet ».',
    timelineCount: '{n} éléments',
    timelineCountOne: '{n} élément',
    timelineEmpty: 'Aucune conversation IA dans ce projet pour le moment.',
    timelineYou: 'Vous',
    timelineUserAria: 'Utilisateur',
    untitled: 'Sans titre',
    noContent: '(vide)',
    // Account
    appVersion: 'Version {v}',
    versionLabel: 'Version',
    theme: 'Thème',
    themeLight: 'Clair',
    themeDark: 'Sombre',
    themeSystem: 'Suivre le système',
    saveLocation: "Emplacement d'enregistrement",
    settings: 'Paramètres',
    setSecGeneral: 'Général',
    setSecAbout: 'À propos',
    setChange: 'Modifier',
    // Dates
    today: "Aujourd'hui",
    yesterday: 'Hier',
    daysAgo: 'il y a {n} j',
    // Language / tab strip
    language: 'Langue',
    closeTab: "Fermer l'onglet",
    tabList: 'Tous les onglets',
    newTab: 'Nouvel onglet',
    // First-run onboarding
    onbTitle1: 'Bienvenue dans byeppt',
    onbSubtitle1: 'Le studio de présentation open source et IA-natif',
    onbBody1: 'Générez un deck à partir d’une phrase, puis peaufinez chaque pixel. L’IA est intégrée à chaque étape.',
    onbTitle2: 'Ce n’est qu’un début',
    onbBody2: 'byeppt n’en est qu’à ses débuts — vos retours façonnent la suite.',
    onbSkip: 'Passer',
    onbNext: 'Suivant',
    onbStart: 'Commencer',
    onbStepAria: 'Page {n} sur {total}',
    onbTitle3: 'Gratuit pour tous',
    onbBody3: 'Pas de licence. Pas de publicité. Pas de filigrane.',
    onbBack: 'Retour',
  },
  de: {
    // Sidebar navigation
    navRecent: 'Zuletzt verwendet',
    navStarred: 'Favoriten',
    cloudSortRecent: 'Neueste',
    cloudSortOldest: 'Älteste',
    navTrash: 'Papierkorb',
    navTrashTip:
      'Gelöschte Dateien werden in den System-Papierkorb verschoben und können dort wiederhergestellt werden',
    // Section headings
    secQuickStart: 'Schnellstart',
    secRecent: 'Zuletzt verwendet',
    secStarred: 'Favoriten',
    secProjectFiles: 'Projektdateien',
    secActivity: 'Aktivität',
    colName: 'Name',
    colLocation: 'Speicherort',
    colModified: 'Geändert',
    colSize: 'Größe',
    // Quick start
    openLocal: 'Lokale Datei öffnen',
    quickAiPpt: 'AI PPT',
    quickAiPptSub: 'Professionelles Deck aus einem Satz generieren',
    greetMorning: 'Guten Morgen',
    greetAfternoon: 'Guten Tag',
    greetEvening: 'Guten Abend',
    greetAsk1: 'Was möchten Sie heute erstellen?',
    greetAsk2: 'Bereit loszulegen?',
    greetAsk3: 'Woran arbeiten Sie?',
    greetAsk4: 'Womit sollen wir heute beginnen?',
    greetAsk5: 'Lust auf etwas Neues?',
    greetAsk6: 'Schon eine Idee?',
    // Filters
    filterAll: 'Alle',
    filterSlides: 'Präsentationen',
    filterAria: 'Nach Typ filtern',
    // List / bulk actions
    fileCount: '{n} Dateien',
    fileCountOne: '{n} Datei',
    selectedCount: '{n} ausgewählt',
    selectAll: 'Alle auswählen',
    selectFile: '{name} auswählen',
    removeFromList: 'Aus Liste entfernen',
    deleteFiles: 'Dateien löschen',
    cancel: 'Abbrechen',
    star: 'Zu Favoriten hinzufügen',
    unstar: 'Aus Favoriten entfernen',
    moreActions: 'Weitere Aktionen',
    open: 'Öffnen',
    revealInFolder: 'Im Ordner anzeigen',
    copyPath: 'Pfad kopieren',
    moveToProject: 'In Projekt verschieben',
    rename: 'Umbenennen',
    duplicate: 'Duplizieren',
    renameFailed: 'Umbenennen fehlgeschlagen',
    emptyStarred:
      'Keine Favoriten — bewegen Sie den Mauszeiger über eine Zeile und klicken Sie auf den Stern.',
    emptyRecent:
      'Keine zuletzt verwendeten Dateien — erstellen oder öffnen Sie eine Datei, um zu beginnen.',
    emptyFiltered: 'Keine Dateien dieses Typs.',
    // Delete confirmation dialog
    deleteModalTitle: 'Dateien löschen',
    deleteConfirmOne: '„{name}“ in den Papierkorb verschieben?',
    deleteConfirmMany: 'Diese {n} Dateien in den Papierkorb verschieben?',
    deleteMoreCount: '… insgesamt {n}',
    delete: 'Löschen',
    // Project sidebar
    projects: 'Projekte',
    newProject: 'Neues Projekt',
    projectName: 'Projektname',
    deleteProject: 'Projekt löschen…',
    deleteProjectConfirm:
      'Dieses Projekt löschen?\nSeine Dateien kehren in das Standardprojekt zurück und gehen nicht verloren.',
    projMoreActions: 'Weitere Aktionen für {name}',
    defaultProject: 'Standardprojekt',
    projEmpty:
      'Bewahren Sie zusammengehörige Dokumente in einem Projekt auf — der KI-Chatverlauf sammelt sich pro Projekt an.',
    projEmptyHint:
      'Erstellen Sie eine Datei oder klicken Sie mit der rechten Maustaste auf eine zuletzt verwendete Datei und wählen Sie „In Projekt verschieben“.',
    timelineCount: '{n} Einträge',
    timelineCountOne: '{n} Eintrag',
    timelineEmpty: 'Noch keine KI-Unterhaltungen in diesem Projekt.',
    timelineYou: 'Sie',
    timelineUserAria: 'Benutzer',
    untitled: 'Unbenannt',
    noContent: '(leer)',
    // Account
    appVersion: 'Version {v}',
    versionLabel: 'Version',
    theme: 'Thema',
    themeLight: 'Hell',
    themeDark: 'Dunkel',
    themeSystem: 'System folgen',
    saveLocation: 'Speicherort',
    settings: 'Einstellungen',
    setSecGeneral: 'Allgemein',
    setSecAbout: 'Über',
    setChange: 'Ändern',
    // Dates
    today: 'Heute',
    yesterday: 'Gestern',
    daysAgo: 'vor {n} Tagen',
    // Language / tab strip
    language: 'Sprache',
    closeTab: 'Tab schließen',
    tabList: 'Alle Tabs',
    newTab: 'Neuer Tab',
    // First-run onboarding
    onbTitle1: 'Willkommen bei byeppt',
    onbSubtitle1: 'Das quelloffene, KI-native Präsentationsstudio',
    onbBody1: 'Erstellen Sie ein Deck aus einem Satz und verfeinern Sie jedes Pixel. KI ist in jeden Schritt integriert.',
    onbTitle2: 'Das ist erst der Anfang',
    onbBody2: 'byeppt ist noch früh — Ihr Feedback gestaltet die Zukunft mit.',
    onbSkip: 'Überspringen',
    onbNext: 'Weiter',
    onbStart: 'Loslegen',
    onbStepAria: 'Seite {n} von {total}',
    onbTitle3: 'Kostenlos für alle',
    onbBody3: 'Keine Lizenzgebühren. Keine Werbung. Keine Wasserzeichen.',
    onbBack: 'Zurück',
  },
  es: {
    // Sidebar navigation
    navRecent: 'Recientes',
    navStarred: 'Destacados',
    cloudSortRecent: 'Recientes',
    cloudSortOldest: 'Más antiguos',
    navTrash: 'Papelera',
    navTrashTip:
      'Los archivos eliminados van a la papelera del sistema y pueden restaurarse desde allí',
    // Section headings
    secQuickStart: 'Inicio rápido',
    secRecent: 'Recientes',
    secStarred: 'Destacados',
    secProjectFiles: 'Archivos del proyecto',
    secActivity: 'Actividad',
    colName: 'Nombre',
    colLocation: 'Ubicación',
    colModified: 'Modificado',
    colSize: 'Tamaño',
    // Quick start
    openLocal: 'Abrir archivo local',
    quickAiPpt: 'AI PPT',
    quickAiPptSub: 'Genera una presentación profesional con una frase',
    greetMorning: 'Buenos días',
    greetAfternoon: 'Buenas tardes',
    greetEvening: 'Buenas noches',
    greetAsk1: '¿Qué quieres crear hoy?',
    greetAsk2: '¿Listo para empezar?',
    greetAsk3: '¿En qué estás trabajando?',
    greetAsk4: '¿Por dónde empezamos hoy?',
    greetAsk5: '¿Te apetece crear algo nuevo?',
    greetAsk6: '¿Alguna idea?',
    // Filters
    filterAll: 'Todos',
    filterSlides: 'Presentaciones',
    filterAria: 'Filtrar por tipo',
    // List / bulk actions
    fileCount: '{n} archivos',
    fileCountOne: '{n} archivo',
    selectedCount: '{n} seleccionados',
    selectAll: 'Seleccionar todo',
    selectFile: 'Seleccionar {name}',
    removeFromList: 'Quitar de la lista',
    deleteFiles: 'Eliminar archivos',
    cancel: 'Cancelar',
    star: 'Destacar',
    unstar: 'Quitar de destacados',
    moreActions: 'Más acciones',
    open: 'Abrir',
    revealInFolder: 'Mostrar en la carpeta',
    copyPath: 'Copiar ruta',
    moveToProject: 'Mover a un proyecto',
    rename: 'Cambiar nombre',
    duplicate: 'Duplicar',
    renameFailed: 'No se pudo cambiar el nombre',
    emptyStarred:
      'No hay archivos destacados — pase el cursor sobre una fila y haga clic en la estrella.',
    emptyRecent: 'No hay archivos recientes — cree o abra un archivo para empezar.',
    emptyFiltered: 'No hay archivos de este tipo.',
    // Delete confirmation dialog
    deleteModalTitle: 'Eliminar archivos',
    deleteConfirmOne: '¿Mover "{name}" a la papelera?',
    deleteConfirmMany: '¿Mover estos {n} archivos a la papelera?',
    deleteMoreCount: '… {n} en total',
    delete: 'Eliminar',
    // Project sidebar
    projects: 'Proyectos',
    newProject: 'Nuevo proyecto',
    projectName: 'Nombre del proyecto',
    deleteProject: 'Eliminar proyecto…',
    deleteProjectConfirm:
      '¿Eliminar este proyecto?\nSus archivos volverán al proyecto predeterminado y no se perderán.',
    projMoreActions: 'Más acciones para {name}',
    defaultProject: 'Proyecto predeterminado',
    projEmpty:
      'Guarde los documentos relacionados en un mismo proyecto — el historial de chat de IA se acumula por proyecto.',
    projEmptyHint:
      'Cree un archivo o haga clic derecho en un archivo reciente y elija "Mover a un proyecto".',
    timelineCount: '{n} elementos',
    timelineCountOne: '{n} elemento',
    timelineEmpty: 'Aún no hay conversaciones de IA en este proyecto.',
    timelineYou: 'Tú',
    timelineUserAria: 'Usuario',
    untitled: 'Sin título',
    noContent: '(vacío)',
    // Account
    appVersion: 'Versión {v}',
    versionLabel: 'Versión',
    theme: 'Tema',
    themeLight: 'Claro',
    themeDark: 'Oscuro',
    themeSystem: 'Seguir el sistema',
    saveLocation: 'Ubicación de guardado',
    settings: 'Configuración',
    setSecGeneral: 'General',
    setSecAbout: 'Acerca de',
    setChange: 'Cambiar',
    // Dates
    today: 'Hoy',
    yesterday: 'Ayer',
    daysAgo: 'hace {n} días',
    // Language / tab strip
    language: 'Idioma',
    closeTab: 'Cerrar pestaña',
    tabList: 'Todas las pestañas',
    newTab: 'Nueva pestaña',
    // First-run onboarding
    onbTitle1: 'Bienvenido a byeppt',
    onbSubtitle1: 'El estudio de presentaciones de código abierto e IA nativa',
    onbBody1: 'Genera un deck con una frase y refina cada píxel. La IA está integrada en cada paso.',
    onbTitle2: 'Esto es solo el comienzo',
    onbBody2: 'byeppt aún está empezando: tus comentarios moldean lo que viene.',
    onbSkip: 'Omitir',
    onbNext: 'Siguiente',
    onbStart: 'Empezar',
    onbStepAria: 'Página {n} de {total}',
    onbTitle3: 'Gratis para todos',
    onbBody3: 'Sin licencias. Sin anuncios. Sin marcas de agua.',
    onbBack: 'Atrás',
  },
  th: {
    // Sidebar navigation
    navRecent: 'ล่าสุด',
    navStarred: 'รายการโปรด',
    cloudSortRecent: 'ล่าสุด',
    cloudSortOldest: 'เก่าสุด',
    navTrash: 'ถังขยะ',
    navTrashTip: 'ไฟล์ที่ถูกลบจะถูกย้ายไปยังถังขยะของระบบ และสามารถกู้คืนได้จากที่นั่น',
    // Section headings
    secQuickStart: 'เริ่มต้นอย่างรวดเร็ว',
    secRecent: 'ใช้งานล่าสุด',
    secStarred: 'รายการโปรด',
    secProjectFiles: 'ไฟล์โปรเจ็กต์',
    secActivity: 'กิจกรรม',
    colName: 'ชื่อ',
    colLocation: 'ตำแหน่งที่ตั้ง',
    colModified: 'แก้ไขเมื่อ',
    colSize: 'ขนาด',
    // Quick start
    openLocal: 'เปิดไฟล์ในเครื่อง',
    quickAiPpt: 'AI PPT',
    quickAiPptSub: 'สร้างงานนำเสนอมืออาชีพจากประโยคเดียว',
    greetMorning: 'สวัสดีตอนเช้า',
    greetAfternoon: 'สวัสดีตอนบ่าย',
    greetEvening: 'สวัสดีตอนเย็น',
    greetAsk1: 'วันนี้อยากสร้างอะไร',
    greetAsk2: 'พร้อมเริ่มต้นหรือยัง',
    greetAsk3: 'อยากทำอะไรดี',
    greetAsk4: 'วันนี้เริ่มจากตรงไหนดี',
    greetAsk5: 'อยากลองทำอะไรใหม่ไหม',
    greetAsk6: 'มีไอเดียอะไรบ้าง',
    // Filters
    filterAll: 'ทั้งหมด',
    filterSlides: 'งานนำเสนอ',
    filterAria: 'กรองตามชนิด',
    // List / bulk actions
    fileCount: '{n} ไฟล์',
    fileCountOne: '{n} ไฟล์',
    selectedCount: 'เลือกแล้ว {n} รายการ',
    selectAll: 'เลือกทั้งหมด',
    selectFile: 'เลือก {name}',
    removeFromList: 'นำออกจากรายการ',
    deleteFiles: 'ลบไฟล์',
    cancel: 'ยกเลิก',
    star: 'เพิ่มในรายการโปรด',
    unstar: 'นำออกจากรายการโปรด',
    moreActions: 'การดำเนินการเพิ่มเติม',
    open: 'เปิด',
    revealInFolder: 'แสดงในโฟลเดอร์',
    copyPath: 'คัดลอกเส้นทาง',
    moveToProject: 'ย้ายไปยังโปรเจ็กต์',
    rename: 'เปลี่ยนชื่อ',
    duplicate: 'สร้างสำเนา',
    renameFailed: 'เปลี่ยนชื่อไม่สำเร็จ',
    emptyStarred: 'ยังไม่มีรายการโปรด — วางเมาส์เหนือแถวไฟล์แล้วคลิกดาว',
    emptyRecent: 'ยังไม่มีไฟล์ล่าสุด — สร้างหรือเปิดไฟล์เพื่อเริ่มต้น',
    emptyFiltered: 'ไม่มีไฟล์ชนิดนี้',
    // Delete confirmation dialog
    deleteModalTitle: 'ลบไฟล์',
    deleteConfirmOne: 'ย้าย "{name}" ไปยังถังขยะหรือไม่',
    deleteConfirmMany: 'ย้ายไฟล์ {n} ไฟล์นี้ไปยังถังขยะหรือไม่',
    deleteMoreCount: '… รวมทั้งหมด {n} ไฟล์',
    delete: 'ลบ',
    // Project sidebar
    projects: 'โปรเจ็กต์',
    newProject: 'โปรเจ็กต์ใหม่',
    projectName: 'ชื่อโปรเจ็กต์',
    deleteProject: 'ลบโปรเจ็กต์…',
    deleteProjectConfirm:
      'ลบโปรเจ็กต์นี้หรือไม่\nไฟล์ในโปรเจ็กต์จะกลับไปยัง "โปรเจ็กต์เริ่มต้น" และจะไม่สูญหาย',
    projMoreActions: 'การดำเนินการเพิ่มเติมสำหรับ {name}',
    defaultProject: 'โปรเจ็กต์เริ่มต้น',
    projEmpty:
      'เก็บเอกสารที่เกี่ยวข้องไว้ในโปรเจ็กต์เดียวกัน — ประวัติการสนทนา AI จะสะสมตามโปรเจ็กต์',
    projEmptyHint: 'สร้างไฟล์ใหม่ หรือคลิกขวาที่ไฟล์ล่าสุดแล้วเลือก "ย้ายไปยังโปรเจ็กต์"',
    timelineCount: '{n} รายการ',
    timelineCountOne: '{n} รายการ',
    timelineEmpty: 'โปรเจ็กต์นี้ยังไม่มีประวัติการสนทนา AI',
    timelineYou: 'คุณ',
    timelineUserAria: 'ผู้ใช้',
    untitled: 'ไม่มีชื่อ',
    noContent: '(ไม่มีเนื้อหา)',
    // Account
    appVersion: 'เวอร์ชัน {v}',
    versionLabel: 'เวอร์ชัน',
    theme: 'ธีม',
    themeLight: 'สว่าง',
    themeDark: 'มืด',
    themeSystem: 'ตามระบบ',
    saveLocation: 'ตำแหน่งบันทึก',
    settings: 'การตั้งค่า',
    setSecGeneral: 'ทั่วไป',
    setSecAbout: 'เกี่ยวกับ',
    setChange: 'เปลี่ยน',
    // Dates
    today: 'วันนี้',
    yesterday: 'เมื่อวาน',
    daysAgo: '{n} วันที่แล้ว',
    // Language / tab strip
    language: 'ภาษา',
    closeTab: 'ปิดแท็บ',
    tabList: 'แท็บทั้งหมด',
    newTab: 'แท็บใหม่',
    // First-run onboarding
    onbTitle1: 'ยินดีต้อนรับสู่ byeppt',
    onbSubtitle1: 'สตูดิโองานนำเสนอ AI เนทีฟแบบโอเพนซอร์ส',
    onbBody1: 'สร้างเด็คจากประโยคเดียว แล้วปรับแต่งทุกพิกเซล AI ผสานอยู่ในทุกขั้นตอน',
    onbTitle2: 'นี่เป็นเพียงจุดเริ่มต้น',
    onbBody2: 'byeppt ยังอยู่ในช่วงเริ่มต้น ความคิดเห็นของคุณจะกำหนดอนาคตของมัน',
    onbSkip: 'ข้าม',
    onbNext: 'ถัดไป',
    onbStart: 'เริ่มใช้งาน',
    onbStepAria: 'หน้า {n} จาก {total}',
    onbTitle3: 'ฟรีสำหรับทุกคน',
    onbBody3: 'ไม่มีค่าลิขสิทธิ์ ไม่มีโฆษณา ไม่มีลายน้ำ',
    onbBack: 'ย้อนกลับ',
  },
  id: {
    // Sidebar navigation
    navRecent: 'Terbaru',
    navStarred: 'Berbintang',
    cloudSortRecent: 'Terbaru',
    cloudSortOldest: 'Terlama',
    navTrash: 'Sampah',
    navTrashTip:
      'File yang dihapus akan dipindahkan ke tempat sampah sistem dan dapat dipulihkan dari sana',
    // Section headings
    secQuickStart: 'Mulai cepat',
    secRecent: 'Terbaru',
    secStarred: 'Berbintang',
    secProjectFiles: 'File proyek',
    secActivity: 'Aktivitas',
    colName: 'Nama',
    colLocation: 'Lokasi',
    colModified: 'Diubah',
    colSize: 'Ukuran',
    // Quick start
    openLocal: 'Buka File Lokal',
    quickAiPpt: 'AI PPT',
    quickAiPptSub: 'Buat deck profesional dari satu kalimat',
    greetMorning: 'Selamat pagi',
    greetAfternoon: 'Selamat siang',
    greetEvening: 'Selamat malam',
    greetAsk1: 'Mau membuat apa hari ini?',
    greetAsk2: 'Siap mulai?',
    greetAsk3: 'Ada yang ingin dikerjakan?',
    greetAsk4: 'Mulai dari mana hari ini?',
    greetAsk5: 'Mau buat sesuatu yang baru?',
    greetAsk6: 'Ada ide bagus?',
    // Filters
    filterAll: 'Semua',
    filterSlides: 'Presentasi',
    filterAria: 'Filter menurut jenis',
    // List / bulk actions
    fileCount: '{n} file',
    fileCountOne: '{n} file',
    selectedCount: '{n} dipilih',
    selectAll: 'Pilih semua',
    selectFile: 'Pilih {name}',
    removeFromList: 'Hapus dari daftar',
    deleteFiles: 'Hapus file',
    cancel: 'Batal',
    star: 'Beri bintang',
    unstar: 'Hapus bintang',
    moreActions: 'Tindakan lainnya',
    open: 'Buka',
    revealInFolder: 'Tampilkan di folder',
    copyPath: 'Salin jalur',
    moveToProject: 'Pindahkan ke proyek',
    rename: 'Ganti nama',
    duplicate: 'Duplikat',
    renameFailed: 'Gagal mengganti nama',
    emptyStarred: 'Belum ada file berbintang — arahkan kursor ke baris file lalu klik bintang.',
    emptyRecent: 'Belum ada file terbaru — buat atau buka file untuk memulai.',
    emptyFiltered: 'Tidak ada file jenis ini.',
    // Delete confirmation dialog
    deleteModalTitle: 'Hapus File',
    deleteConfirmOne: 'Pindahkan "{name}" ke tempat sampah?',
    deleteConfirmMany: 'Pindahkan {n} file ini ke tempat sampah?',
    deleteMoreCount: '… total {n} file',
    delete: 'Hapus',
    // Project sidebar
    projects: 'Proyek',
    newProject: 'Proyek baru',
    projectName: 'Nama proyek',
    deleteProject: 'Hapus proyek…',
    deleteProjectConfirm:
      'Hapus proyek ini?\nFile di dalamnya akan kembali ke Proyek Default dan tidak akan hilang.',
    projMoreActions: 'Tindakan lainnya untuk {name}',
    defaultProject: 'Proyek default',
    projEmpty:
      'Simpan dokumen terkait dalam satu proyek — riwayat percakapan AI terkumpul per proyek.',
    projEmptyHint: 'Buat file, atau klik kanan file terbaru dan pilih "Pindahkan ke proyek".',
    timelineCount: '{n} item',
    timelineCountOne: '{n} item',
    timelineEmpty: 'Belum ada percakapan AI di proyek ini.',
    timelineYou: 'Anda',
    timelineUserAria: 'Pengguna',
    untitled: 'Tanpa judul',
    noContent: '(kosong)',
    // Account
    appVersion: 'Versi {v}',
    versionLabel: 'Versi',
    theme: 'Tema',
    themeLight: 'Terang',
    themeDark: 'Gelap',
    themeSystem: 'Ikuti Sistem',
    saveLocation: 'Lokasi penyimpanan',
    settings: 'Pengaturan',
    setSecGeneral: 'Umum',
    setSecAbout: 'Tentang',
    setChange: 'Ubah',
    // Dates
    today: 'Hari ini',
    yesterday: 'Kemarin',
    daysAgo: '{n} hari lalu',
    // Language / tab strip
    language: 'Bahasa',
    closeTab: 'Tutup tab',
    tabList: 'Semua tab',
    newTab: 'Tab baru',
    // First-run onboarding
    onbTitle1: 'Selamat datang di byeppt',
    onbSubtitle1: 'Studio presentasi AI-native sumber terbuka',
    onbBody1: 'Buat deck dari satu kalimat, lalu sempurnakan setiap piksel. AI menyatu di setiap langkah.',
    onbTitle2: 'Ini baru permulaan',
    onbBody2: 'byeppt masih tahap awal — masukan Anda membentuk masa depannya.',
    onbSkip: 'Lewati',
    onbNext: 'Berikutnya',
    onbStart: 'Mulai',
    onbStepAria: 'Halaman {n} dari {total}',
    onbTitle3: 'Gratis untuk semua',
    onbBody3: 'Tanpa biaya lisensi. Tanpa iklan. Tanpa watermark.',
    onbBack: 'Kembali',
  },
  ru: {
    // Sidebar navigation
    navRecent: 'Недавние',
    navStarred: 'Избранное',
    cloudSortRecent: 'Сначала новые',
    cloudSortOldest: 'Сначала старые',
    navTrash: 'Корзина',
    navTrashTip: 'Удалённые файлы перемещаются в системную корзину, откуда их можно восстановить',
    // Section headings
    secQuickStart: 'Быстрый старт',
    secRecent: 'Недавние',
    secStarred: 'Избранное',
    secProjectFiles: 'Файлы проекта',
    secActivity: 'Активность',
    colName: 'Имя',
    colLocation: 'Расположение',
    colModified: 'Изменён',
    colSize: 'Размер',
    // Quick start
    openLocal: 'Открыть локальный файл',
    quickAiPpt: 'AI PPT',
    quickAiPptSub: 'Профессиональная презентация по одной фразе',
    greetMorning: 'Доброе утро',
    greetAfternoon: 'Добрый день',
    greetEvening: 'Добрый вечер',
    greetAsk1: 'Что создадим сегодня?',
    greetAsk2: 'Готовы начать?',
    greetAsk3: 'Над чем работаем?',
    greetAsk4: 'С чего начнём сегодня?',
    greetAsk5: 'Хотите создать что-то новое?',
    greetAsk6: 'Есть идея?',
    // Filters
    filterAll: 'Все',
    filterSlides: 'Презентации',
    filterAria: 'Фильтр по типу',
    // List / bulk actions
    fileCount: 'Файлов: {n}',
    fileCountOne: '{n} файл',
    selectedCount: 'Выбрано: {n}',
    selectAll: 'Выбрать все',
    selectFile: 'Выбрать {name}',
    removeFromList: 'Убрать из списка',
    deleteFiles: 'Удалить файлы',
    cancel: 'Отмена',
    star: 'В избранное',
    unstar: 'Убрать из избранного',
    moreActions: 'Другие действия',
    open: 'Открыть',
    revealInFolder: 'Показать в папке',
    copyPath: 'Скопировать путь',
    moveToProject: 'Переместить в проект',
    rename: 'Переименовать',
    duplicate: 'Создать копию',
    renameFailed: 'Не удалось переименовать',
    emptyStarred:
      'В избранном пока пусто — наведите курсор на строку файла и нажмите на звёздочку.',
    emptyRecent: 'Нет недавних файлов — создайте или откройте файл, чтобы начать.',
    emptyFiltered: 'Файлов этого типа нет.',
    // Delete confirmation dialog
    deleteModalTitle: 'Удаление файлов',
    deleteConfirmOne: 'Переместить «{name}» в корзину?',
    deleteConfirmMany: 'Переместить эти файлы ({n}) в корзину?',
    deleteMoreCount: '… всего {n}',
    delete: 'Удалить',
    // Project sidebar
    projects: 'Проекты',
    newProject: 'Создать проект',
    projectName: 'Название проекта',
    deleteProject: 'Удалить проект…',
    deleteProjectConfirm:
      'Удалить этот проект?\nЕго файлы вернутся в проект по умолчанию и не будут потеряны.',
    projMoreActions: 'Другие действия для {name}',
    defaultProject: 'Проект по умолчанию',
    projEmpty:
      'Храните связанные документы в одном проекте — история диалогов с ИИ накапливается по проектам.',
    projEmptyHint:
      'Создайте файл или щёлкните недавний файл правой кнопкой мыши и выберите «Переместить в проект».',
    timelineCount: 'Записей: {n}',
    timelineCountOne: '{n} запись',
    timelineEmpty: 'В этом проекте пока нет диалогов с ИИ.',
    timelineYou: 'Вы',
    timelineUserAria: 'Пользователь',
    untitled: 'Без названия',
    noContent: '(пусто)',
    // Account
    appVersion: 'Версия {v}',
    versionLabel: 'Версия',
    theme: 'Тема',
    themeLight: 'Светлая',
    themeDark: 'Тёмная',
    themeSystem: 'Как в системе',
    saveLocation: 'Папка сохранения',
    settings: 'Настройки',
    setSecGeneral: 'Общие',
    setSecAbout: 'О программе',
    setChange: 'Изменить',
    // Dates
    today: 'Сегодня',
    yesterday: 'Вчера',
    daysAgo: '{n} дн. назад',
    // Language / tab strip
    language: 'Язык',
    closeTab: 'Закрыть вкладку',
    tabList: 'Все вкладки',
    newTab: 'Новая вкладка',
    // First-run onboarding
    onbTitle1: 'Добро пожаловать в byeppt',
    onbSubtitle1: 'Открытая AI-native студия презентаций',
    onbBody1: 'Создайте презентацию из одной фразы и доработайте каждый пиксель. ИИ встроен в каждый шаг.',
    onbTitle2: 'Это только начало',
    onbBody2: 'byeppt пока на ранней стадии — ваши отзывы формируют его будущее.',
    onbSkip: 'Пропустить',
    onbNext: 'Далее',
    onbStart: 'Начать',
    onbStepAria: 'Страница {n} из {total}',
    onbTitle3: 'Бесплатно для всех',
    onbBody3: 'Без лицензий. Без рекламы. Без водяных знаков.',
    onbBack: 'Назад',
  },
  ar: {
    // Sidebar navigation
    navRecent: 'الأخيرة',
    navStarred: 'المفضلة',
    cloudSortRecent: 'الأحدث',
    cloudSortOldest: 'الأقدم',
    navTrash: 'سلة المهملات',
    navTrashTip: 'تُنقل الملفات المحذوفة إلى سلة مهملات النظام ويمكن استعادتها من هناك',
    // Section headings
    secQuickStart: 'بدء سريع',
    secRecent: 'المستخدمة مؤخرًا',
    secStarred: 'المفضلة',
    secProjectFiles: 'ملفات المشروع',
    secActivity: 'النشاط',
    colName: 'الاسم',
    colLocation: 'الموقع',
    colModified: 'تاريخ التعديل',
    colSize: 'الحجم',
    // Quick start
    openLocal: 'فتح ملف محلي',
    quickAiPpt: 'AI PPT',
    quickAiPptSub: 'أنشئ عرضًا احترافيًا من جملة واحدة',
    greetMorning: 'صباح الخير',
    greetAfternoon: 'مساء الخير',
    greetEvening: 'مساء الخير',
    greetAsk1: 'ماذا تريد أن تنشئ اليوم؟',
    greetAsk2: 'هل أنت مستعد للبدء؟',
    greetAsk3: 'على ماذا تعمل؟',
    greetAsk4: 'من أين نبدأ اليوم؟',
    greetAsk5: 'هل ترغب في إنشاء شيء جديد؟',
    greetAsk6: 'هل لديك فكرة؟',
    // Filters
    filterAll: 'الكل',
    filterSlides: 'عروض تقديمية',
    filterAria: 'تصفية حسب النوع',
    // List / bulk actions
    fileCount: '{n} ملفات',
    fileCountOne: 'ملف واحد',
    selectedCount: 'تم تحديد {n}',
    selectAll: 'تحديد الكل',
    selectFile: 'تحديد {name}',
    removeFromList: 'إزالة من القائمة',
    deleteFiles: 'حذف الملفات',
    cancel: 'إلغاء',
    star: 'إضافة إلى المفضلة',
    unstar: 'إزالة من المفضلة',
    moreActions: 'إجراءات أخرى',
    open: 'فتح',
    revealInFolder: 'إظهار في المجلد',
    copyPath: 'نسخ المسار',
    moveToProject: 'نقل إلى مشروع',
    rename: 'إعادة تسمية',
    duplicate: 'إنشاء نسخة',
    renameFailed: 'فشلت إعادة التسمية',
    emptyStarred: 'لا توجد ملفات مفضلة — مرِّر المؤشر فوق صف الملف وانقر على النجمة.',
    emptyRecent: 'لا توجد ملفات حديثة — أنشئ ملفًا أو افتحه للبدء.',
    emptyFiltered: 'لا توجد ملفات من هذا النوع.',
    // Delete confirmation dialog
    deleteModalTitle: 'حذف الملفات',
    deleteConfirmOne: 'هل تريد نقل "{name}" إلى سلة المهملات؟',
    deleteConfirmMany: 'هل تريد نقل هذه الملفات ({n}) إلى سلة المهملات؟',
    deleteMoreCount: '… الإجمالي {n}',
    delete: 'حذف',
    // Project sidebar
    projects: 'المشاريع',
    newProject: 'مشروع جديد',
    projectName: 'اسم المشروع',
    deleteProject: 'حذف المشروع…',
    deleteProjectConfirm:
      'هل تريد حذف هذا المشروع؟\nستعود ملفاته إلى "المشروع الافتراضي" ولن تُفقد.',
    projMoreActions: 'إجراءات أخرى لـ {name}',
    defaultProject: 'المشروع الافتراضي',
    projEmpty:
      'احتفظ بالمستندات المرتبطة في مشروع واحد — يتراكم سجل محادثات الذكاء الاصطناعي لكل مشروع.',
    projEmptyHint: 'أنشئ ملفًا، أو انقر بزر الماوس الأيمن على ملف حديث واختر "نقل إلى مشروع".',
    timelineCount: '{n} عناصر',
    timelineCountOne: 'عنصر واحد',
    timelineEmpty: 'لا توجد محادثات ذكاء اصطناعي في هذا المشروع بعد.',
    timelineYou: 'أنت',
    timelineUserAria: 'المستخدم',
    untitled: 'بدون عنوان',
    noContent: '(فارغ)',
    // Account
    appVersion: 'الإصدار {v}',
    versionLabel: 'الإصدار',
    theme: 'المظهر',
    themeLight: 'فاتح',
    themeDark: 'داكن',
    themeSystem: 'اتباع النظام',
    saveLocation: 'موقع الحفظ',
    settings: 'الإعدادات',
    setSecGeneral: 'عام',
    setSecAbout: 'حول',
    setChange: 'تغيير',
    // Dates
    today: 'اليوم',
    yesterday: 'أمس',
    daysAgo: 'قبل {n} أيام',
    // Language / tab strip
    language: 'اللغة',
    closeTab: 'إغلاق علامة التبويب',
    tabList: 'كل علامات التبويب',
    newTab: 'علامة تبويب جديدة',
    // First-run onboarding
    onbTitle1: 'مرحبًا بك في byeppt',
    onbSubtitle1: 'استوديو العروض التقديمية المفتوح المصدر والمدعوم بالذكاء الاصطناعي',
    onbBody1: 'أنشئ عرضًا من جملة واحدة، ثم حسّن كل بكسل. الذكاء الاصطناعي مدمج في كل خطوة.',
    onbTitle2: 'هذه مجرد البداية',
    onbBody2: 'byeppt لا يزال في بدايته — ملاحظاتك تشكل مستقبله.',
    onbSkip: 'تخطي',
    onbNext: 'التالي',
    onbStart: 'ابدأ الآن',
    onbStepAria: 'الصفحة {n} من {total}',
    onbTitle3: 'مجاني للجميع',
    onbBody3: 'بلا رسوم ترخيص، بلا إعلانات، بلا علامات مائية.',
    onbBack: 'رجوع',
  },
  pt: {
    navRecent: 'Recentes',
    navStarred: 'Favoritos',
    cloudSortRecent: 'Recentes',
    cloudSortOldest: 'Mais antigos',
    navTrash: 'Lixeira',
    navTrashTip:
      'Os arquivos excluídos vão para a lixeira do sistema e podem ser restaurados de lá',
    secQuickStart: 'Início rápido',
    secRecent: 'Recentes',
    secStarred: 'Favoritos',
    secProjectFiles: 'Arquivos do projeto',
    secActivity: 'Atividade',
    colName: 'Nome',
    colLocation: 'Local',
    colModified: 'Modificado',
    colSize: 'Tamanho',
    openLocal: 'Abrir arquivo local',
    quickAiPpt: 'AI PPT',
    quickAiPptSub: 'Gere uma apresentação profissional a partir de uma frase',
    greetMorning: 'Bom dia',
    greetAfternoon: 'Boa tarde',
    greetEvening: 'Boa noite',
    greetAsk1: 'O que você quer criar hoje?',
    greetAsk2: 'Pronto para começar?',
    greetAsk3: 'No que você está trabalhando?',
    greetAsk4: 'Por onde começamos hoje?',
    greetAsk5: 'Que tal criar algo novo?',
    greetAsk6: 'Alguma ideia?',
    filterAll: 'Todos',
    filterSlides: 'Apresentações',
    filterAria: 'Filtrar por tipo',
    fileCount: '{n} arquivos',
    fileCountOne: '{n} arquivo',
    selectedCount: '{n} selecionados',
    selectAll: 'Selecionar tudo',
    selectFile: 'Selecionar {name}',
    removeFromList: 'Remover da lista',
    deleteFiles: 'Excluir arquivos',
    cancel: 'Cancelar',
    star: 'Adicionar aos favoritos',
    unstar: 'Remover dos favoritos',
    moreActions: 'Mais ações',
    open: 'Abrir',
    revealInFolder: 'Mostrar na pasta',
    copyPath: 'Copiar caminho',
    moveToProject: 'Mover para um projeto',
    rename: 'Renomear',
    duplicate: 'Duplicar',
    renameFailed: 'Falha ao renomear',
    emptyStarred: 'Nenhum favorito — passe o cursor sobre uma linha e clique na estrela.',
    emptyRecent: 'Nenhum arquivo recente — crie ou abra um arquivo para começar.',
    emptyFiltered: 'Nenhum arquivo deste tipo.',
    deleteModalTitle: 'Excluir arquivos',
    deleteConfirmOne: 'Mover "{name}" para a lixeira?',
    deleteConfirmMany: 'Mover estes {n} arquivos para a lixeira?',
    deleteMoreCount: '… {n} no total',
    delete: 'Excluir',
    projects: 'Projetos',
    newProject: 'Novo projeto',
    projectName: 'Nome do projeto',
    deleteProject: 'Excluir projeto…',
    deleteProjectConfirm:
      'Excluir este projeto?\nSeus arquivos voltarão ao projeto padrão e não serão perdidos.',
    projMoreActions: 'Mais ações para {name}',
    defaultProject: 'Projeto padrão',
    projEmpty:
      'Mantenha documentos relacionados em um mesmo projeto — o histórico de conversas com a IA se acumula por projeto.',
    projEmptyHint:
      'Crie um arquivo ou clique com o botão direito em um arquivo recente e escolha "Mover para um projeto".',
    timelineCount: '{n} itens',
    timelineCountOne: '{n} item',
    timelineEmpty: 'Ainda não há conversas com a IA neste projeto.',
    timelineYou: 'Você',
    timelineUserAria: 'Usuário',
    untitled: 'Sem título',
    noContent: '(vazio)',
    appVersion: 'Versão {v}',
    versionLabel: 'Versão',
    theme: 'Tema',
    themeLight: 'Claro',
    themeDark: 'Escuro',
    themeSystem: 'Seguir o Sistema',
    saveLocation: 'Local de salvamento',
    settings: 'Configurações',
    setSecGeneral: 'Geral',
    setSecAbout: 'Sobre',
    setChange: 'Alterar',
    today: 'Hoje',
    yesterday: 'Ontem',
    daysAgo: 'há {n} dias',
    language: 'Idioma',
    closeTab: 'Fechar guia',
    tabList: 'Todas as guias',
    newTab: 'Nova guia',
    // First-run onboarding
    onbTitle1: 'Bem-vindo ao byeppt',
    onbSubtitle1: 'O estúdio de apresentações open source e nativo de IA',
    onbBody1: 'Gere um deck a partir de uma frase e refine cada pixel. A IA está presente em cada etapa.',
    onbTitle2: 'Isto é só o começo',
    onbBody2: 'byeppt ainda está no começo — seu feedback molda o que vem a seguir.',
    onbSkip: 'Pular',
    onbNext: 'Avançar',
    onbStart: 'Começar',
    onbStepAria: 'Página {n} de {total}',
    onbTitle3: 'Gratuito para todos',
    onbBody3: "Sem licenças. Sem anúncios. Sem marcas d'água.",
    onbBack: 'Voltar',
  },
  it: {
    navRecent: 'Recenti',
    navStarred: 'Preferiti',
    cloudSortRecent: 'Recenti',
    cloudSortOldest: 'Meno recenti',
    navTrash: 'Cestino',
    navTrashTip:
      'I file eliminati vengono spostati nel cestino di sistema e possono essere ripristinati da lì',
    secQuickStart: 'Avvio rapido',
    secRecent: 'Recenti',
    secStarred: 'Preferiti',
    secProjectFiles: 'File del progetto',
    secActivity: 'Attività',
    colName: 'Nome',
    colLocation: 'Posizione',
    colModified: 'Modificato',
    colSize: 'Dimensione',
    openLocal: 'Apri file locale',
    quickAiPpt: 'AI PPT',
    quickAiPptSub: 'Genera una presentazione professionale da una frase',
    greetMorning: 'Buongiorno',
    greetAfternoon: 'Buon pomeriggio',
    greetEvening: 'Buonasera',
    greetAsk1: 'Cosa vuoi creare oggi?',
    greetAsk2: 'Pronto per iniziare?',
    greetAsk3: 'Su cosa stai lavorando?',
    greetAsk4: 'Da dove iniziamo oggi?',
    greetAsk5: 'Vuoi creare qualcosa di nuovo?',
    greetAsk6: "Hai un'idea?",
    filterAll: 'Tutti',
    filterSlides: 'Presentazioni',
    filterAria: 'Filtra per tipo',
    fileCount: '{n} file',
    fileCountOne: '{n} file',
    selectedCount: '{n} selezionati',
    selectAll: 'Seleziona tutto',
    selectFile: 'Seleziona {name}',
    removeFromList: "Rimuovi dall'elenco",
    deleteFiles: 'Elimina file',
    cancel: 'Annulla',
    star: 'Aggiungi ai preferiti',
    unstar: 'Rimuovi dai preferiti',
    moreActions: 'Altre azioni',
    open: 'Apri',
    revealInFolder: 'Mostra nella cartella',
    copyPath: 'Copia percorso',
    moveToProject: 'Sposta in un progetto',
    rename: 'Rinomina',
    duplicate: 'Duplica',
    renameFailed: 'Impossibile rinominare',
    emptyStarred: 'Nessun preferito — passa il cursore su una riga e fai clic sulla stella.',
    emptyRecent: 'Nessun file recente — crea o apri un file per iniziare.',
    emptyFiltered: 'Nessun file di questo tipo.',
    deleteModalTitle: 'Elimina file',
    deleteConfirmOne: 'Spostare "{name}" nel cestino?',
    deleteConfirmMany: 'Spostare questi {n} file nel cestino?',
    deleteMoreCount: '… {n} in totale',
    delete: 'Elimina',
    projects: 'Progetti',
    newProject: 'Nuovo progetto',
    projectName: 'Nome del progetto',
    deleteProject: 'Elimina progetto…',
    deleteProjectConfirm:
      'Eliminare questo progetto?\nI suoi file torneranno nel progetto predefinito e non andranno persi.',
    projMoreActions: 'Altre azioni per {name}',
    defaultProject: 'Progetto predefinito',
    projEmpty:
      'Tieni i documenti correlati in uno stesso progetto — la cronologia delle chat IA si accumula per progetto.',
    projEmptyHint:
      'Crea un file oppure fai clic con il pulsante destro su un file recente e scegli "Sposta in un progetto".',
    timelineCount: '{n} elementi',
    timelineCountOne: '{n} elemento',
    timelineEmpty: 'Non ci sono ancora conversazioni IA in questo progetto.',
    timelineYou: 'Tu',
    timelineUserAria: 'Utente',
    untitled: 'Senza titolo',
    noContent: '(vuoto)',
    appVersion: 'Versione {v}',
    versionLabel: 'Versione',
    theme: 'Tema',
    themeLight: 'Chiaro',
    themeDark: 'Scuro',
    themeSystem: 'Segui il sistema',
    saveLocation: 'Posizione di salvataggio',
    settings: 'Impostazioni',
    setSecGeneral: 'Generale',
    setSecAbout: 'Informazioni',
    setChange: 'Cambia',
    today: 'Oggi',
    yesterday: 'Ieri',
    daysAgo: '{n} giorni fa',
    language: 'Lingua',
    closeTab: 'Chiudi scheda',
    tabList: 'Tutte le schede',
    newTab: 'Nuova scheda',
    // First-run onboarding
    onbTitle1: 'Benvenuto in byeppt',
    onbSubtitle1: 'Lo studio di presentazioni open source e AI-native',
    onbBody1: 'Genera un deck da una frase, poi rifinisci ogni pixel. L’IA è integrata in ogni passaggio.',
    onbTitle2: 'Questo è solo l’inizio',
    onbBody2: 'byeppt è solo all’inizio: i tuoi feedback plasmano il futuro.',
    onbSkip: 'Salta',
    onbNext: 'Avanti',
    onbStart: 'Inizia',
    onbStepAria: 'Pagina {n} di {total}',
    onbTitle3: 'Gratuito per tutti',
    onbBody3: 'Nessuna licenza. Nessuna pubblicità. Nessuna filigrana.',
    onbBack: 'Indietro',
  },
  pl: {
    navRecent: 'Ostatnie',
    navStarred: 'Ulubione',
    cloudSortRecent: 'Najnowsze',
    cloudSortOldest: 'Najstarsze',
    navTrash: 'Kosz',
    navTrashTip: 'Usunięte pliki trafiają do systemowego kosza i można je stamtąd przywrócić',
    secQuickStart: 'Szybki start',
    secRecent: 'Ostatnie',
    secStarred: 'Ulubione',
    secProjectFiles: 'Pliki projektu',
    secActivity: 'Aktywność',
    colName: 'Nazwa',
    colLocation: 'Lokalizacja',
    colModified: 'Zmodyfikowano',
    colSize: 'Rozmiar',
    openLocal: 'Otwórz plik lokalny',
    quickAiPpt: 'AI PPT',
    quickAiPptSub: 'Wygeneruj profesjonalną prezentację z jednego zdania',
    greetMorning: 'Dzień dobry',
    greetAfternoon: 'Dzień dobry',
    greetEvening: 'Dobry wieczór',
    greetAsk1: 'Co chcesz dziś stworzyć?',
    greetAsk2: 'Gotowy, aby zacząć?',
    greetAsk3: 'Nad czym pracujesz?',
    greetAsk4: 'Od czego dziś zaczniemy?',
    greetAsk5: 'Masz ochotę stworzyć coś nowego?',
    greetAsk6: 'Masz jakiś pomysł?',
    filterAll: 'Wszystkie',
    filterSlides: 'Prezentacje',
    filterAria: 'Filtruj według typu',
    fileCount: 'Pliki: {n}',
    fileCountOne: '{n} plik',
    selectedCount: 'Wybrano: {n}',
    selectAll: 'Zaznacz wszystko',
    selectFile: 'Zaznacz {name}',
    removeFromList: 'Usuń z listy',
    deleteFiles: 'Usuń pliki',
    cancel: 'Anuluj',
    star: 'Dodaj do ulubionych',
    unstar: 'Usuń z ulubionych',
    moreActions: 'Więcej działań',
    open: 'Otwórz',
    revealInFolder: 'Pokaż w folderze',
    copyPath: 'Kopiuj ścieżkę',
    moveToProject: 'Przenieś do projektu',
    rename: 'Zmień nazwę',
    duplicate: 'Utwórz kopię',
    renameFailed: 'Nie udało się zmienić nazwy',
    emptyStarred: 'Brak ulubionych — najedź kursorem na wiersz pliku i kliknij gwiazdkę.',
    emptyRecent: 'Brak ostatnich plików — utwórz lub otwórz plik, aby rozpocząć.',
    emptyFiltered: 'Brak plików tego typu.',
    deleteModalTitle: 'Usuwanie plików',
    deleteConfirmOne: 'Przenieść „{name}” do kosza?',
    deleteConfirmMany: 'Przenieść te pliki ({n}) do kosza?',
    deleteMoreCount: '… łącznie {n}',
    delete: 'Usuń',
    projects: 'Projekty',
    newProject: 'Nowy projekt',
    projectName: 'Nazwa projektu',
    deleteProject: 'Usuń projekt…',
    deleteProjectConfirm:
      'Usunąć ten projekt?\nJego pliki wrócą do projektu domyślnego i nie zostaną utracone.',
    projMoreActions: 'Więcej działań dla {name}',
    defaultProject: 'Projekt domyślny',
    projEmpty:
      'Trzymaj powiązane dokumenty w jednym projekcie — historia rozmów z AI gromadzi się dla każdego projektu.',
    projEmptyHint:
      'Utwórz plik lub kliknij ostatni plik prawym przyciskiem myszy i wybierz „Przenieś do projektu”.',
    timelineCount: 'Wpisy: {n}',
    timelineCountOne: '{n} wpis',
    timelineEmpty: 'W tym projekcie nie ma jeszcze rozmów z AI.',
    timelineYou: 'Ty',
    timelineUserAria: 'Użytkownik',
    untitled: 'Bez tytułu',
    noContent: '(pusto)',
    appVersion: 'Wersja {v}',
    versionLabel: 'Wersja',
    theme: 'Motyw',
    themeLight: 'Jasny',
    themeDark: 'Ciemny',
    themeSystem: 'Zgodnie z systemem',
    saveLocation: 'Lokalizacja zapisu',
    settings: 'Ustawienia',
    setSecGeneral: 'Ogólne',
    setSecAbout: 'O aplikacji',
    setChange: 'Zmień',
    today: 'Dzisiaj',
    yesterday: 'Wczoraj',
    daysAgo: '{n} dni temu',
    language: 'Język',
    closeTab: 'Zamknij kartę',
    tabList: 'Wszystkie karty',
    newTab: 'Nowa karta',
    // First-run onboarding
    onbTitle1: 'Witamy w byeppt',
    onbSubtitle1: 'Otwartoźródłowe, AI-native studio prezentacji',
    onbBody1: 'Wygeneruj deck z jednego zdania, a potem dopracuj każdy piksel. AI jest wpisane w każdy krok.',
    onbTitle2: 'To dopiero początek',
    onbBody2: 'byeppt jest dopiero na początku — Twoje opinie kształtują jego przyszłość.',
    onbSkip: 'Pomiń',
    onbNext: 'Dalej',
    onbStart: 'Rozpocznij',
    onbStepAria: 'Strona {n} z {total}',
    onbTitle3: 'Za darmo dla każdego',
    onbBody3: 'Bez opłat licencyjnych. Bez reklam. Bez znaków wodnych.',
    onbBack: 'Wstecz',
  },
  nl: {
    navRecent: 'Recent',
    navStarred: 'Favorieten',
    cloudSortRecent: 'Recent',
    cloudSortOldest: 'Oudste',
    navTrash: 'Prullenbak',
    navTrashTip:
      'Verwijderde bestanden gaan naar de systeemprullenbak en kunnen daar worden hersteld',
    secQuickStart: 'Snel starten',
    secRecent: 'Recent',
    secStarred: 'Favorieten',
    secProjectFiles: 'Projectbestanden',
    secActivity: 'Activiteit',
    colName: 'Naam',
    colLocation: 'Locatie',
    colModified: 'Gewijzigd',
    colSize: 'Grootte',
    openLocal: 'Lokaal bestand openen',
    quickAiPpt: 'AI PPT',
    quickAiPptSub: 'Genereer een professionele presentatie met één zin',
    greetMorning: 'Goedemorgen',
    greetAfternoon: 'Goedemiddag',
    greetEvening: 'Goedenavond',
    greetAsk1: 'Wat wil je vandaag maken?',
    greetAsk2: 'Klaar om te beginnen?',
    greetAsk3: 'Waar werk je aan?',
    greetAsk4: 'Waar beginnen we vandaag?',
    greetAsk5: 'Zin om iets nieuws te maken?',
    greetAsk6: 'Al een idee?',
    filterAll: 'Alle',
    filterSlides: 'Presentaties',
    filterAria: 'Filteren op type',
    fileCount: '{n} bestanden',
    fileCountOne: '{n} bestand',
    selectedCount: '{n} geselecteerd',
    selectAll: 'Alles selecteren',
    selectFile: '{name} selecteren',
    removeFromList: 'Uit lijst verwijderen',
    deleteFiles: 'Bestanden verwijderen',
    cancel: 'Annuleren',
    star: 'Aan favorieten toevoegen',
    unstar: 'Uit favorieten verwijderen',
    moreActions: 'Meer acties',
    open: 'Openen',
    revealInFolder: 'Tonen in map',
    copyPath: 'Pad kopiëren',
    moveToProject: 'Naar project verplaatsen',
    rename: 'Naam wijzigen',
    duplicate: 'Dupliceren',
    renameFailed: 'Naam wijzigen mislukt',
    emptyStarred: 'Geen favorieten — beweeg de muis over een rij en klik op de ster.',
    emptyRecent: 'Geen recente bestanden — maak of open een bestand om te beginnen.',
    emptyFiltered: 'Geen bestanden van dit type.',
    deleteModalTitle: 'Bestanden verwijderen',
    deleteConfirmOne: '"{name}" naar de prullenbak verplaatsen?',
    deleteConfirmMany: 'Deze {n} bestanden naar de prullenbak verplaatsen?',
    deleteMoreCount: '… {n} in totaal',
    delete: 'Verwijderen',
    projects: 'Projecten',
    newProject: 'Nieuw project',
    projectName: 'Projectnaam',
    deleteProject: 'Project verwijderen…',
    deleteProjectConfirm:
      'Dit project verwijderen?\nDe bestanden gaan terug naar het standaardproject en gaan niet verloren.',
    projMoreActions: 'Meer acties voor {name}',
    defaultProject: 'Standaardproject',
    projEmpty:
      'Bewaar gerelateerde documenten in één project — de AI-chatgeschiedenis wordt per project opgebouwd.',
    projEmptyHint:
      'Maak een bestand, of klik met de rechtermuisknop op een recent bestand en kies "Naar project verplaatsen".',
    timelineCount: '{n} items',
    timelineCountOne: '{n} item',
    timelineEmpty: 'Nog geen AI-gesprekken in dit project.',
    timelineYou: 'Jij',
    timelineUserAria: 'Gebruiker',
    untitled: 'Naamloos',
    noContent: '(leeg)',
    appVersion: 'Versie {v}',
    versionLabel: 'Versie',
    theme: 'Thema',
    themeLight: 'Licht',
    themeDark: 'Donker',
    themeSystem: 'Systeem volgen',
    saveLocation: 'Opslaglocatie',
    settings: 'Instellingen',
    setSecGeneral: 'Algemeen',
    setSecAbout: 'Over',
    setChange: 'Wijzigen',
    today: 'Vandaag',
    yesterday: 'Gisteren',
    daysAgo: '{n} dagen geleden',
    language: 'Taal',
    closeTab: 'Tabblad sluiten',
    tabList: 'Alle tabbladen',
    newTab: 'Nieuw tabblad',
    // First-run onboarding
    onbTitle1: 'Welkom bij byeppt',
    onbSubtitle1: 'De open-source, AI-native presentatiestudio',
    onbBody1: 'Genereer een deck uit één zin en verfijn elke pixel. AI is in elke stap verweven.',
    onbTitle2: 'Dit is nog maar het begin',
    onbBody2: 'byeppt staat nog aan het begin — jouw feedback bepaalt wat er komt.',
    onbSkip: 'Overslaan',
    onbNext: 'Volgende',
    onbStart: 'Aan de slag',
    onbStepAria: 'Pagina {n} van {total}',
    onbTitle3: 'Gratis voor iedereen',
    onbBody3: 'Geen licentiekosten. Geen advertenties. Geen watermerken.',
    onbBack: 'Terug',
  },
  ms: {
    navRecent: 'Terkini',
    navStarred: 'Berbintang',
    cloudSortRecent: 'Terbaru',
    cloudSortOldest: 'Terlama',
    navTrash: 'Tong sampah',
    navTrashTip:
      'Fail yang dipadamkan akan dipindahkan ke tong sampah sistem dan boleh dipulihkan dari sana',
    secQuickStart: 'Mula pantas',
    secRecent: 'Terkini',
    secStarred: 'Berbintang',
    secProjectFiles: 'Fail projek',
    secActivity: 'Aktiviti',
    colName: 'Nama',
    colLocation: 'Lokasi',
    colModified: 'Diubah suai',
    colSize: 'Saiz',
    openLocal: 'Buka Fail Setempat',
    quickAiPpt: 'AI PPT',
    quickAiPptSub: 'Jana pembentangan profesional daripada satu ayat',
    greetMorning: 'Selamat pagi',
    greetAfternoon: 'Selamat tengah hari',
    greetEvening: 'Selamat petang',
    greetAsk1: 'Apa yang anda mahu cipta hari ini?',
    greetAsk2: 'Sedia untuk bermula?',
    greetAsk3: 'Apa yang anda sedang usahakan?',
    greetAsk4: 'Dari mana kita mula hari ini?',
    greetAsk5: 'Mahu cipta sesuatu yang baharu?',
    greetAsk6: 'Ada idea?',
    filterAll: 'Semua',
    filterSlides: 'Persembahan',
    filterAria: 'Tapis mengikut jenis',
    fileCount: '{n} fail',
    fileCountOne: '{n} fail',
    selectedCount: '{n} dipilih',
    selectAll: 'Pilih semua',
    selectFile: 'Pilih {name}',
    removeFromList: 'Alih keluar daripada senarai',
    deleteFiles: 'Padam fail',
    cancel: 'Batal',
    star: 'Tambah bintang',
    unstar: 'Buang bintang',
    moreActions: 'Tindakan lain',
    open: 'Buka',
    revealInFolder: 'Tunjukkan dalam folder',
    copyPath: 'Salin laluan',
    moveToProject: 'Pindahkan ke projek',
    rename: 'Namakan semula',
    duplicate: 'Buat salinan',
    renameFailed: 'Gagal menamakan semula',
    emptyStarred: 'Belum ada fail berbintang — halakan kursor ke baris fail dan klik bintang.',
    emptyRecent: 'Belum ada fail terkini — cipta atau buka fail untuk bermula.',
    emptyFiltered: 'Tiada fail jenis ini.',
    deleteModalTitle: 'Padam Fail',
    deleteConfirmOne: 'Pindahkan "{name}" ke tong sampah?',
    deleteConfirmMany: 'Pindahkan {n} fail ini ke tong sampah?',
    deleteMoreCount: '… {n} kesemuanya',
    delete: 'Padam',
    projects: 'Projek',
    newProject: 'Projek baharu',
    projectName: 'Nama projek',
    deleteProject: 'Padam projek…',
    deleteProjectConfirm:
      'Padam projek ini?\nFail di dalamnya akan kembali ke Projek Lalai dan tidak akan hilang.',
    projMoreActions: 'Tindakan lain untuk {name}',
    defaultProject: 'Projek lalai',
    projEmpty:
      'Simpan dokumen berkaitan dalam satu projek — sejarah perbualan AI terkumpul mengikut projek.',
    projEmptyHint: 'Cipta fail, atau klik kanan fail terkini dan pilih "Pindahkan ke projek".',
    timelineCount: '{n} item',
    timelineCountOne: '{n} item',
    timelineEmpty: 'Belum ada perbualan AI dalam projek ini.',
    timelineYou: 'Anda',
    timelineUserAria: 'Pengguna',
    untitled: 'Tanpa tajuk',
    noContent: '(kosong)',
    appVersion: 'Versi {v}',
    versionLabel: 'Versi',
    theme: 'Tema',
    themeLight: 'Cerah',
    themeDark: 'Gelap',
    themeSystem: 'Ikut Sistem',
    saveLocation: 'Lokasi simpanan',
    settings: 'Tetapan',
    setSecGeneral: 'Umum',
    setSecAbout: 'Perihal',
    setChange: 'Tukar',
    today: 'Hari ini',
    yesterday: 'Semalam',
    daysAgo: '{n} hari lalu',
    language: 'Bahasa',
    closeTab: 'Tutup tab',
    tabList: 'Semua tab',
    newTab: 'Tab baharu',
    // First-run onboarding
    onbTitle1: 'Selamat datang ke byeppt',
    onbSubtitle1: 'Studio persembahan AI-natif sumber terbuka',
    onbBody1: 'Jana dek daripada satu ayat, kemudian kemas setiap piksel. AI terbina dalam setiap langkah.',
    onbTitle2: 'Ini baru permulaan',
    onbBody2: 'byeppt masih di peringkat awal — maklum balas anda membentuk masa depannya.',
    onbSkip: 'Langkau',
    onbNext: 'Seterusnya',
    onbStart: 'Mula',
    onbStepAria: 'Halaman {n} daripada {total}',
    onbTitle3: 'Percuma untuk semua',
    onbBody3: 'Tiada yuran lesen. Tiada iklan. Tiada tera air.',
    onbBack: 'Kembali',
  },
  he: {
    navRecent: 'אחרונים',
    navStarred: 'מועדפים',
    cloudSortRecent: 'החדשים ביותר',
    cloudSortOldest: 'הישנים ביותר',
    navTrash: 'אשפה',
    navTrashTip: 'קבצים שנמחקו עוברים לאשפה של המערכת וניתן לשחזר אותם משם',
    secQuickStart: 'התחלה מהירה',
    secRecent: 'אחרונים',
    secStarred: 'מועדפים',
    secProjectFiles: 'קובצי הפרויקט',
    secActivity: 'פעילות',
    colName: 'שם',
    colLocation: 'מיקום',
    colModified: 'שונה',
    colSize: 'גודל',
    openLocal: 'פתיחת קובץ מקומי',
    quickAiPpt: 'AI PPT',
    quickAiPptSub: 'צור מצגת מקצועית ממשפט אחד',
    greetMorning: 'בוקר טוב',
    greetAfternoon: 'צהריים טובים',
    greetEvening: 'ערב טוב',
    greetAsk1: 'מה תרצו ליצור היום?',
    greetAsk2: 'מוכנים להתחיל?',
    greetAsk3: 'על מה אתם עובדים?',
    greetAsk4: 'מאיפה נתחיל היום?',
    greetAsk5: 'רוצים ליצור משהו חדש?',
    greetAsk6: 'יש לכם רעיון?',
    filterAll: 'הכול',
    filterSlides: 'מצגות',
    filterAria: 'סינון לפי סוג',
    fileCount: '{n} קבצים',
    fileCountOne: 'קובץ אחד',
    selectedCount: 'נבחרו {n}',
    selectAll: 'בחירת הכול',
    selectFile: 'בחירת {name}',
    removeFromList: 'הסרה מהרשימה',
    deleteFiles: 'מחיקת קבצים',
    cancel: 'ביטול',
    star: 'הוספה למועדפים',
    unstar: 'הסרה מהמועדפים',
    moreActions: 'פעולות נוספות',
    open: 'פתיחה',
    revealInFolder: 'הצגה בתיקייה',
    copyPath: 'העתקת נתיב',
    moveToProject: 'העברה לפרויקט',
    rename: 'שינוי שם',
    duplicate: 'יצירת עותק',
    renameFailed: 'שינוי השם נכשל',
    emptyStarred: 'אין מועדפים עדיין — רחפו מעל שורת קובץ ולחצו על הכוכב.',
    emptyRecent: 'אין קבצים אחרונים — צרו או פתחו קובץ כדי להתחיל.',
    emptyFiltered: 'אין קבצים מסוג זה.',
    deleteModalTitle: 'מחיקת קבצים',
    deleteConfirmOne: 'להעביר את "{name}" לאשפה?',
    deleteConfirmMany: 'להעביר את {n} הקבצים האלה לאשפה?',
    deleteMoreCount: '… {n} בסך הכול',
    delete: 'מחיקה',
    projects: 'פרויקטים',
    newProject: 'פרויקט חדש',
    projectName: 'שם הפרויקט',
    deleteProject: 'מחיקת פרויקט…',
    deleteProjectConfirm:
      'למחוק את הפרויקט הזה?\nהקבצים שבו יחזרו ל"פרויקט ברירת המחדל" ולא יאבדו.',
    projMoreActions: 'פעולות נוספות עבור {name}',
    defaultProject: 'פרויקט ברירת מחדל',
    projEmpty: 'שמרו מסמכים קשורים באותו פרויקט — היסטוריית שיחות ה-AI נצברת לפי פרויקט.',
    projEmptyHint: 'צרו קובץ, או לחצו לחיצה ימנית על קובץ אחרון ובחרו "העברה לפרויקט".',
    timelineCount: '{n} פריטים',
    timelineCountOne: 'פריט אחד',
    timelineEmpty: 'אין עדיין שיחות AI בפרויקט הזה.',
    timelineYou: 'את/ה',
    timelineUserAria: 'משתמש',
    untitled: 'ללא שם',
    noContent: '(ריק)',
    appVersion: 'גרסה {v}',
    versionLabel: 'גרסה',
    theme: 'ערכת נושא',
    themeLight: 'בהיר',
    themeDark: 'כהה',
    themeSystem: 'עקוב אחר המערכת',
    saveLocation: 'מיקום שמירה',
    settings: 'הגדרות',
    setSecGeneral: 'כללי',
    setSecAbout: 'אודות',
    setChange: 'שינוי',
    today: 'היום',
    yesterday: 'אתמול',
    daysAgo: 'לפני {n} ימים',
    language: 'שפה',
    closeTab: 'סגירת כרטיסייה',
    tabList: 'כל הכרטיסיות',
    newTab: 'כרטיסייה חדשה',
    // First-run onboarding
    onbTitle1: 'ברוכים הבאים ל-byeppt',
    onbSubtitle1: 'סטודיו המצגות בקוד פתוח עם AI מובנה',
    onbBody1: 'צור מצגת ממשפט אחד ולטש כל פיקסל. ה-AI משולב בכל שלב.',
    onbTitle2: 'זו רק ההתחלה',
    onbBody2: 'byeppt עוד בתחילת הדרך — המשוב שלך מעצב את ההמשך.',
    onbSkip: 'דילוג',
    onbNext: 'הבא',
    onbStart: 'להתחיל',
    onbStepAria: 'עמוד {n} מתוך {total}',
    onbTitle3: 'חינם לכולם',
    onbBody3: 'ללא דמי רישיון, ללא פרסומות, ללא סימני מים.',
    onbBack: 'חזרה',
  },
  hi: {
    navRecent: 'हाल के',
    navStarred: 'तारांकित',
    cloudSortRecent: 'हाल के',
    cloudSortOldest: 'सबसे पुराने',
    navTrash: 'ट्रैश',
    navTrashTip: 'हटाई गई फ़ाइलें सिस्टम ट्रैश में जाती हैं और वहाँ से पुनर्स्थापित की जा सकती हैं',
    secQuickStart: 'त्वरित प्रारंभ',
    secRecent: 'हाल के',
    secStarred: 'तारांकित',
    secProjectFiles: 'प्रोजेक्ट फ़ाइलें',
    secActivity: 'गतिविधि',
    colName: 'नाम',
    colLocation: 'स्थान',
    colModified: 'संशोधित',
    colSize: 'आकार',
    openLocal: 'स्थानीय फ़ाइल खोलें',
    quickAiPpt: 'AI PPT',
    quickAiPptSub: 'एक वाक्य से प्रोफ़ेशनल प्रेज़ेंटेशन बनाएं',
    greetMorning: 'सुप्रभात',
    greetAfternoon: 'नमस्ते',
    greetEvening: 'शुभ संध्या',
    greetAsk1: 'आज आप क्या बनाना चाहेंगे?',
    greetAsk2: 'शुरू करने के लिए तैयार?',
    greetAsk3: 'आप किस पर काम कर रहे हैं?',
    greetAsk4: 'आज कहाँ से शुरू करें?',
    greetAsk5: 'कुछ नया बनाना चाहेंगे?',
    greetAsk6: 'कोई आइडिया है?',
    filterAll: 'सभी',
    filterSlides: 'प्रस्तुतियाँ',
    filterAria: 'प्रकार के अनुसार फ़िल्टर करें',
    fileCount: '{n} फ़ाइलें',
    fileCountOne: '{n} फ़ाइल',
    selectedCount: '{n} चयनित',
    selectAll: 'सभी चुनें',
    selectFile: '{name} चुनें',
    removeFromList: 'सूची से हटाएँ',
    deleteFiles: 'फ़ाइलें हटाएँ',
    cancel: 'रद्द करें',
    star: 'तारांकित करें',
    unstar: 'तारांकन हटाएँ',
    moreActions: 'अधिक कार्रवाइयाँ',
    open: 'खोलें',
    revealInFolder: 'फ़ोल्डर में दिखाएँ',
    copyPath: 'पथ कॉपी करें',
    moveToProject: 'प्रोजेक्ट में ले जाएँ',
    rename: 'नाम बदलें',
    duplicate: 'प्रतिलिपि बनाएँ',
    renameFailed: 'नाम बदलने में विफल',
    emptyStarred:
      'कोई तारांकित फ़ाइल नहीं — फ़ाइल की पंक्ति पर कर्सर ले जाएँ और तारे पर क्लिक करें।',
    emptyRecent: 'कोई हालिया फ़ाइल नहीं — शुरू करने के लिए कोई फ़ाइल बनाएँ या खोलें।',
    emptyFiltered: 'इस प्रकार की कोई फ़ाइल नहीं है।',
    deleteModalTitle: 'फ़ाइलें हटाएँ',
    deleteConfirmOne: '"{name}" को ट्रैश में ले जाएँ?',
    deleteConfirmMany: 'इन {n} फ़ाइलों को ट्रैश में ले जाएँ?',
    deleteMoreCount: '… कुल {n}',
    delete: 'हटाएँ',
    projects: 'प्रोजेक्ट',
    newProject: 'नया प्रोजेक्ट',
    projectName: 'प्रोजेक्ट का नाम',
    deleteProject: 'प्रोजेक्ट हटाएँ…',
    deleteProjectConfirm:
      'यह प्रोजेक्ट हटाएँ?\nइसकी फ़ाइलें "डिफ़ॉल्ट प्रोजेक्ट" में वापस चली जाएँगी और खोएँगी नहीं।',
    projMoreActions: '{name} के लिए अधिक कार्रवाइयाँ',
    defaultProject: 'डिफ़ॉल्ट प्रोजेक्ट',
    projEmpty:
      'संबंधित दस्तावेज़ों को एक ही प्रोजेक्ट में रखें — AI चैट इतिहास प्रोजेक्ट के अनुसार जमा होता है।',
    projEmptyHint:
      'कोई फ़ाइल बनाएँ, या किसी हालिया फ़ाइल पर राइट-क्लिक करके "प्रोजेक्ट में ले जाएँ" चुनें।',
    timelineCount: '{n} आइटम',
    timelineCountOne: '{n} आइटम',
    timelineEmpty: 'इस प्रोजेक्ट में अभी तक कोई AI बातचीत नहीं है।',
    timelineYou: 'आप',
    timelineUserAria: 'उपयोगकर्ता',
    untitled: 'बिना शीर्षक',
    noContent: '(खाली)',
    appVersion: 'संस्करण {v}',
    versionLabel: 'संस्करण',
    theme: 'थीम',
    themeLight: 'लाइट',
    themeDark: 'डार्क',
    themeSystem: 'सिस्टम का अनुसरण करें',
    saveLocation: 'सहेजने का स्थान',
    settings: 'सेटिंग्स',
    setSecGeneral: 'सामान्य',
    setSecAbout: 'जानकारी',
    setChange: 'बदलें',
    today: 'आज',
    yesterday: 'कल',
    daysAgo: '{n} दिन पहले',
    language: 'भाषा',
    closeTab: 'टैब बंद करें',
    tabList: 'सभी टैब',
    newTab: 'नया टैब',
    // First-run onboarding
    onbTitle1: 'byeppt में आपका स्वागत है',
    onbSubtitle1: 'ओपन-सोर्स, AI-नेटिव प्रेज़ेंटेशन स्टूडियो',
    onbBody1: 'एक वाक्य से डेक बनाएं, फिर हर पिक्सेल परफ़ेक्ट करें। AI हर कदम में समाहित है।',
    onbTitle2: 'यह तो बस शुरुआत है',
    onbBody2: 'byeppt अभी शुरुआती दौर में है — आपकी प्रतिक्रिया इसका भविष्य तय करेगी।',
    onbSkip: 'छोड़ें',
    onbNext: 'आगे',
    onbStart: 'शुरू करें',
    onbStepAria: 'कुल {total} में से पृष्ठ {n}',
    onbTitle3: 'सभी के लिए मुफ़्त',
    onbBody3: 'कोई लाइसेंस शुल्क नहीं। कोई विज्ञापन नहीं। कोई वॉटरमार्क नहीं।',
    onbBack: 'वापस',
  },
  'zh-TW': {
    navRecent: '最近',
    navStarred: '收藏',
    cloudSortRecent: '最近',
    cloudSortOldest: '最早',
    navTrash: '垃圾桶',
    navTrashTip: '刪除的檔案會移至系統垃圾桶，可從那裡還原',
    secQuickStart: '快速開始',
    secRecent: '最近使用',
    secStarred: '收藏',
    secProjectFiles: '專案檔案',
    secActivity: '專案動態',
    colName: '名稱',
    colLocation: '位置',
    colModified: '修改時間',
    colSize: '大小',
    openLocal: '開啟本機檔案',
    quickAiPpt: 'AI PPT',
    quickAiPptSub: '用一句話生成專業簡報',
    greetMorning: '早安',
    greetAfternoon: '午安',
    greetEvening: '晚安',
    greetAsk1: '今天想建立點什麼？',
    greetAsk2: '準備好開始了嗎？',
    greetAsk3: '有什麼想做的嗎？',
    greetAsk4: '今天從哪裡開始？',
    greetAsk5: '想做點什麼新的？',
    greetAsk6: '靈感來了嗎？',
    filterAll: '全部',
    filterSlides: '簡報',
    filterAria: '依類型篩選',
    fileCount: '{n} 個檔案',
    fileCountOne: '{n} 個檔案',
    selectedCount: '已選 {n} 項',
    selectAll: '全選',
    selectFile: '選取 {name}',
    removeFromList: '從清單中移除',
    deleteFiles: '刪除檔案',
    cancel: '取消',
    star: '收藏',
    unstar: '取消收藏',
    moreActions: '更多動作',
    open: '開啟',
    revealInFolder: '開啟所在資料夾',
    copyPath: '複製路徑',
    moveToProject: '移至專案',
    rename: '重新命名',
    duplicate: '建立副本',
    renameFailed: '重新命名失敗',
    emptyStarred: '還沒有收藏 — 將游標移到檔案列並點按星號即可收藏。',
    emptyRecent: '暫無最近檔案 — 新增或開啟檔案即可開始使用。',
    emptyFiltered: '此類型下暫無檔案。',
    deleteModalTitle: '刪除檔案',
    deleteConfirmOne: '確定將「{name}」移至垃圾桶？',
    deleteConfirmMany: '確定將以下 {n} 個檔案移至垃圾桶？',
    deleteMoreCount: '… 等共 {n} 個',
    delete: '刪除',
    projects: '專案',
    newProject: '新增專案',
    projectName: '專案名稱',
    deleteProject: '刪除專案…',
    deleteProjectConfirm: '刪除此專案？\n專案內的檔案會回到「預設專案」，不會遺失。',
    projMoreActions: '{name} 更多動作',
    defaultProject: '預設專案',
    projEmpty: '把相關文件放進同一個專案，AI 對話紀錄會依專案累積。',
    projEmptyHint: '新增檔案，或在「最近」檔案上按右鍵選擇「移至專案」。',
    timelineCount: '{n} 筆',
    timelineCountOne: '{n} 筆',
    timelineEmpty: '此專案還沒有 AI 對話紀錄。',
    timelineYou: '你',
    timelineUserAria: '使用者',
    untitled: '未命名',
    noContent: '（無內容）',
    appVersion: '版本 {v}',
    versionLabel: '版本',
    theme: '主題',
    themeLight: '淺色',
    themeDark: '深色',
    themeSystem: '跟隨系統',
    saveLocation: '預設儲存位置',
    settings: '設定',
    setSecGeneral: '一般',
    setSecAbout: '關於',
    setChange: '變更',
    today: '今天',
    yesterday: '昨天',
    daysAgo: '{n} 天前',
    language: '語言',
    closeTab: '關閉分頁',
    tabList: '全部分頁',
    newTab: '新分頁',
    // First-run onboarding
    onbTitle1: '歡迎使用 byeppt',
    onbSubtitle1: '開源的 AI 原生簡報工作室',
    onbBody1: '用一句話生成簡報，再逐像素精修。AI 深度融入每個環節。',
    onbTitle2: '這只是一個開始',
    onbBody2: 'byeppt 目前還在早期階段，歡迎回饋建議，一起塑造它的未來。',
    onbSkip: '略過',
    onbNext: '下一步',
    onbStart: '開始使用',
    onbStepAria: '第 {n} 頁，共 {total} 頁',
    onbTitle3: '人人免費',
    onbBody3: '無授權費用，無廣告，無浮水印。',
    onbBack: '上一步',
  },
} as const
