/** home-screen dictionary; zh defines the key set, en must match (type-checked) */
export const strings = {
  zh: {
    // Sidebar navigation
    navRecent: '最近',
    navStarred: '收藏',
    cloudSortRecent: '最近',
    cloudSortOldest: '最早',
    navTrash: '回收站',
    navTrashTip: '删除的文件在系统废纸篓中，可从那里还原',
    secQuickStart: '快速开始',
    secRecent: '最近使用',
    secStarred: '收藏',
    secProjectFiles: '项目文件',
    secActivity: '项目动态',
    colName: '名称',
    colLocation: '位置',
    colModified: '修改时间',
    colSize: '大小',
    // Quick start
    openLocal: '打开本地文件',
    quickAiPpt: 'AI PPT',
    quickAiPptSub: '用一句话生成专业演示文稿',
    greetMorning: '早上好',
    greetAfternoon: '下午好',
    greetEvening: '晚上好',
    greetAsk1: '今天想创建点什么？',
    greetAsk2: '准备好开始了吗？',
    greetAsk3: '有什么想做的吗？',
    greetAsk4: '今天从哪里开始？',
    greetAsk5: '想做点什么新的？',
    greetAsk6: '灵感来了吗？',
    // Filters
    filterAll: '全部',
    filterSlides: '演示',
    filterAria: '按类型筛选',
    // List / bulk actions
    fileCount: '{n} 个文件',
    fileCountOne: '{n} 个文件',
    selectedCount: '已选 {n} 项',
    selectAll: '全选',
    selectFile: '选择 {name}',
    removeFromList: '从列表中移除',
    deleteFiles: '删除文件',
    cancel: '取消',
    star: '收藏',
    unstar: '取消收藏',
    moreActions: '更多操作',
    open: '打开',
    revealInFolder: '打开所在文件夹',
    copyPath: '复制路径',
    moveToProject: '移动到项目',
    rename: '重命名',
    duplicate: '创建副本',
    renameFailed: '重命名失败',
    emptyStarred: '还没有收藏 — 悬浮文件行并点击星标即可收藏。',
    emptyRecent: '暂无最近文件 — 新建或打开一个文件开始使用。',
    emptyFiltered: '该类型下暂无文件。',
    // Delete confirmation dialog
    deleteModalTitle: '删除文件',
    deleteConfirmOne: '确定将"{name}"移到废纸篓？',
    deleteConfirmMany: '确定将以下 {n} 个文件移到废纸篓？',
    deleteMoreCount: '… 等共 {n} 个',
    delete: '删除',
    // Project sidebar
    projects: '项目',
    newProject: '新建项目',
    projectName: '项目名称',
    deleteProject: '删除项目…',
    deleteProjectConfirm: '删除该项目？\n项目下的文件将回归"默认项目"，不会丢失。',
    projMoreActions: '{name} 更多操作',
    defaultProject: '默认项目',
    projEmpty: '把相关文档放进同一个项目，AI 对话历史会按项目沉淀。',
    projEmptyHint: '新建文件或从"最近文件"右键选择"移动到项目"。',
    timelineCount: '{n} 条',
    timelineCountOne: '{n} 条',
    timelineEmpty: '该项目还没有 AI 对话记录。',
    timelineYou: '你',
    timelineUserAria: '用户',
    untitled: '未命名',
    noContent: '（无内容）',
    // Account
    appVersion: '版本 {v}',
    versionLabel: '版本',
    aboutAuthor: '作者',
    starOnGitHub: '在 GitHub 上 Star',
    theme: '主题',
    themeLight: '浅色',
    themeDark: '深色',
    themeSystem: '跟随系统',
    saveLocation: '默认保存位置',
    settings: '设置',
    setSecGeneral: '通用',
    setSecProviders: '模型服务',
    setLogin: '登录',
    setOauthWaiting: '已在浏览器中打开登录页，完成授权即可；也可以把重定向地址粘贴到下面',
    setOauthPastePlaceholder: '粘贴重定向 URL 或授权码…',
    setTestFailTip: '无法连接，请检查 API key 或订阅状态',
    setEnableNeedsTest: '通过连通性测试后可启用',
    setBedrockHint: 'Amazon Bedrock 使用 AWS 凭证（profile、IAM keys、bearer token 或角色），不支持单个 API key — 请先在环境中配置 AWS 凭证。',
    setEnable: '启用',
    setProxy: '网络代理',
    setProxyEnable: '启用代理',
    setProxyAuto: '留空则自动使用系统代理',
    setProxyNoDetect: '留空则自动检测;当前未检测到系统代理',
    setInUse: '使用中',
    setEdit: '编辑',
    setBaseUrlLabel: 'Base URL',
    setBaseUrlPlaceholder: '留空使用默认地址',
    setConnFailedTip: '无法连接，请检查 API Key 或 Base URL',
    tabHome: '首页',
    setProviderSearch: '搜索供应商…',
    setConfigTitle: '配置 {name}',
    setApiKeyLabel: 'API Key',
    setModelLabel: '模型',
    setModelPlaceholder: '输入模型 ID',
    setSecImageGen: '图片生成',
    setKeyConfigured: '已配置',
    setKeyMissing: '未配置',
    setKeyPlaceholder: '粘贴 API key…',
    setKeyTest: '测试',
    setKeyTestOk: '连接成功',
    setKeyTestFail: '连接失败',
    setKeyClear: '清除',
    setKeySaved: '已保存',
    setKeyCleared: '已清除',
    setSave: '保存',
    setProvidersEmpty: '未发现供应商(代理 SDK 未加载)',
    setImageGenHint: '为 agent 的配图工具选择生图后端;密钥复用上方对应供应商的 key。',
    setSecAbout: '关于',
    setChange: '更改',
    // Dates
    today: '今天',
    yesterday: '昨天',
    daysAgo: '{n}天前',
    // Language / tab strip
    language: '语言',
    closeTab: '关闭标签',
    tabList: '全部标签',
    newTab: '新建标签页',
  },
  en: {
    navRecent: 'Recent',
    navStarred: 'Starred',
    cloudSortRecent: 'Recent',
    cloudSortOldest: 'Oldest',
    navTrash: 'Trash',
    navTrashTip: 'Deleted files go to the system Trash and can be restored there',
    secQuickStart: 'Quick start',
    secRecent: 'Recent',
    secStarred: 'Starred',
    secProjectFiles: 'Project files',
    secActivity: 'Activity',
    colName: 'Name',
    colLocation: 'Location',
    colModified: 'Modified',
    colSize: 'Size',
    openLocal: 'Open Local File',
    quickAiPpt: 'AI PPT',
    quickAiPptSub: 'Generate a professional deck from a prompt',
    greetMorning: 'Good morning',
    greetAfternoon: 'Good afternoon',
    greetEvening: 'Good evening',
    greetAsk1: 'What would you like to create today?',
    greetAsk2: 'Ready to get started?',
    greetAsk3: 'What are you working on?',
    greetAsk4: 'Where shall we begin today?',
    greetAsk5: 'Feeling creative?',
    greetAsk6: "What's next on your mind?",
    filterAll: 'All',
    filterSlides: 'Slides',
    filterAria: 'Filter by type',
    fileCount: '{n} files',
    fileCountOne: '{n} file',
    selectedCount: '{n} selected',
    selectAll: 'Select all',
    selectFile: 'Select {name}',
    removeFromList: 'Remove from list',
    deleteFiles: 'Delete files',
    cancel: 'Cancel',
    star: 'Star',
    unstar: 'Unstar',
    moreActions: 'More actions',
    open: 'Open',
    revealInFolder: 'Reveal in folder',
    copyPath: 'Copy path',
    moveToProject: 'Move to project',
    rename: 'Rename',
    duplicate: 'Duplicate',
    renameFailed: 'Rename failed',
    emptyStarred: 'No starred files — hover a row and click the star.',
    emptyRecent: 'No recent files — create or open a file to get started.',
    emptyFiltered: 'No files of this type.',
    deleteModalTitle: 'Delete Files',
    deleteConfirmOne: 'Move "{name}" to the Trash?',
    deleteConfirmMany: 'Move these {n} files to the Trash?',
    deleteMoreCount: '… {n} in total',
    delete: 'Delete',
    projects: 'Projects',
    newProject: 'New project',
    projectName: 'Project name',
    deleteProject: 'Delete project…',
    deleteProjectConfirm:
      "Delete this project?\nIts files will return to the Default project and won't be lost.",
    projMoreActions: 'More actions for {name}',
    defaultProject: 'Default project',
    projEmpty: 'Keep related documents in one project — AI chat history accumulates per project.',
    projEmptyHint: 'Create a file, or right-click a recent file and choose "Move to project".',
    timelineCount: '{n} items',
    timelineCountOne: '{n} item',
    timelineEmpty: 'No AI conversations in this project yet.',
    timelineYou: 'You',
    timelineUserAria: 'User',
    untitled: 'Untitled',
    noContent: '(empty)',
    appVersion: 'Version {v}',
    versionLabel: 'Version',
    aboutAuthor: 'Author',
    starOnGitHub: 'Star on GitHub',
    theme: 'Theme',
    themeLight: 'Light',
    themeDark: 'Dark',
    themeSystem: 'Follow System',
    saveLocation: 'Save Location',
    settings: 'Settings',
    setSecGeneral: 'General',
    setSecProviders: 'Model providers',
    setLogin: 'Log in',
    setOauthWaiting: 'Sign-in opened in your browser — finish it there, or paste the redirect below',
    setOauthPastePlaceholder: 'Paste redirect URL or code…',
    setTestFailTip: "Can't connect — check the API key or subscription",
    setEnableNeedsTest: 'Enable after the connectivity test passes',
    setBedrockHint: 'Amazon Bedrock uses AWS credentials (profile, IAM keys, bearer token, or role) — there is no single API key. Configure AWS credentials in your environment.',
    setEnable: 'Enable',
    setProxy: 'Network proxy',
    setProxyEnable: 'Enable proxy',
    setProxyAuto: 'Empty = use the system proxy automatically',
    setProxyNoDetect: 'Empty = auto-detect; no system proxy found',
    setInUse: 'In use',
    setEdit: 'Edit',
    setBaseUrlLabel: 'Base URL',
    setBaseUrlPlaceholder: 'Leave empty for the default endpoint',
    setConnFailedTip: 'Connection failed — check the API key or Base URL',
    tabHome: 'Home',
    setProviderSearch: 'Search providers…',
    setConfigTitle: 'Configure {name}',
    setApiKeyLabel: 'API Key',
    setModelLabel: 'Model',
    setModelPlaceholder: 'Enter model ID',
    setSecImageGen: 'Image generation',
    setKeyConfigured: 'Configured',
    setKeyMissing: 'Not configured',
    setKeyPlaceholder: 'Paste API key…',
    setKeyTest: 'Test',
    setKeyTestOk: 'Connection OK',
    setKeyTestFail: 'Connection failed',
    setKeyClear: 'Clear',
    setKeySaved: 'Saved',
    setKeyCleared: 'Cleared',
    setSave: 'Save',
    setProvidersEmpty: 'No providers found (agent SDK not loaded)',
    setImageGenHint: 'Choose the image backend for the agent\'s picture tool; keys are reused from the matching provider above.',
    setSecAbout: 'About',
    setChange: 'Change',
    today: 'Today',
    yesterday: 'Yesterday',
    daysAgo: '{n}d ago',
    language: 'Language',
    closeTab: 'Close tab',
    tabList: 'All tabs',
    newTab: 'New tab',
  },
  ja: {
    // Sidebar navigation
    navRecent: '最近使用',
    navStarred: 'お気に入り',
    cloudSortRecent: '新しい順',
    cloudSortOldest: '古い順',
    navTrash: 'ゴミ箱',
    navTrashTip: '削除したファイルはシステムのゴミ箱に移動され、そこから復元できます',
    // Section headings
    secQuickStart: 'クイックスタート',
    secRecent: '最近使用',
    secStarred: 'お気に入り',
    secProjectFiles: 'プロジェクトファイル',
    secActivity: 'アクティビティ',
    colName: '名前',
    colLocation: '場所',
    colModified: '更新日時',
    colSize: 'サイズ',
    // Quick start
    openLocal: 'ローカルファイルを開く',
    quickAiPpt: 'AI PPT',
    quickAiPptSub: '一言でプロのプレゼンを生成',
    greetMorning: 'おはようございます',
    greetAfternoon: 'こんにちは',
    greetEvening: 'こんばんは',
    greetAsk1: '今日は何を作りますか？',
    greetAsk2: '準備はできましたか？',
    greetAsk3: '何か作りたいものはありますか？',
    greetAsk4: '今日はどこから始めますか？',
    greetAsk5: '新しいことに挑戦しますか？',
    greetAsk6: 'インスピレーションは湧きましたか？',
    // Filters
    filterAll: 'すべて',
    filterSlides: 'プレゼンテーション',
    filterAria: '種類で絞り込み',
    // List / bulk actions
    fileCount: '{n} 個のファイル',
    fileCountOne: '{n} 個のファイル',
    selectedCount: '{n} 件選択中',
    selectAll: 'すべて選択',
    selectFile: '{name} を選択',
    removeFromList: 'リストから削除',
    deleteFiles: 'ファイルを削除',
    cancel: 'キャンセル',
    star: 'お気に入りに追加',
    unstar: 'お気に入りから削除',
    moreActions: 'その他の操作',
    open: '開く',
    revealInFolder: 'フォルダーで表示',
    copyPath: 'パスをコピー',
    moveToProject: 'プロジェクトに移動',
    rename: '名前の変更',
    duplicate: '複製を作成',
    renameFailed: '名前の変更に失敗しました',
    emptyStarred:
      'お気に入りはまだありません — ファイルの行にカーソルを合わせて星マークをクリックしてください。',
    emptyRecent: '最近使ったファイルはありません — 新規作成するかファイルを開いて始めましょう。',
    emptyFiltered: 'この種類のファイルはありません。',
    // Delete confirmation dialog
    deleteModalTitle: 'ファイルの削除',
    deleteConfirmOne: '「{name}」をゴミ箱に移動しますか？',
    deleteConfirmMany: '次の {n} 個のファイルをゴミ箱に移動しますか？',
    deleteMoreCount: '… ほか、計 {n} 個',
    delete: '削除',
    // Project sidebar
    projects: 'プロジェクト',
    newProject: '新規プロジェクト',
    projectName: 'プロジェクト名',
    deleteProject: 'プロジェクトを削除…',
    deleteProjectConfirm:
      'このプロジェクトを削除しますか？\nプロジェクト内のファイルは「既定のプロジェクト」に戻り、失われることはありません。',
    projMoreActions: '{name} のその他の操作',
    defaultProject: '既定のプロジェクト',
    projEmpty:
      '関連するドキュメントを同じプロジェクトにまとめると、AI との会話履歴がプロジェクトごとに蓄積されます。',
    projEmptyHint:
      '新規ファイルを作成するか、「最近使用」のファイルを右クリックして「プロジェクトに移動」を選択してください。',
    timelineCount: '{n} 件',
    timelineCountOne: '{n} 件',
    timelineEmpty: 'このプロジェクトにはまだ AI との会話履歴がありません。',
    timelineYou: 'あなた',
    timelineUserAria: 'ユーザー',
    untitled: '無題',
    noContent: '（内容なし）',
    // Account
    appVersion: 'バージョン {v}',
    versionLabel: 'バージョン',
    aboutAuthor: '作者',
    starOnGitHub: 'GitHub でスター',
    theme: 'テーマ',
    themeLight: 'ライト',
    themeDark: 'ダーク',
    themeSystem: 'システムに従う',
    saveLocation: '保存先',
    settings: '設定',
    setSecGeneral: '一般',
    setSecProviders: 'モデルプロバイダー',
    setLogin: 'ログイン',
    setOauthWaiting: 'ブラウザでログインページを開きました。完了するか、下にリダイレクトを貼り付けてください',
    setOauthPastePlaceholder: 'リダイレクト URL またはコードを貼り付け…',
    setTestFailTip: '接続できません。API キーまたはサブスクリプションを確認してください',
    setEnableNeedsTest: '接続テストに合格すると有効化できます',
    setBedrockHint: 'Amazon Bedrock は AWS 認証情報（プロファイル、IAM キー、ベアラートークン、ロール）を使用します。単一の API キーはありません。環境で AWS 認証情報を設定してください。',
    setEnable: '有効化',
    setProxy: 'ネットワークプロキシ',
    setProxyEnable: 'プロキシを有効化',
    setProxyAuto: '空欄の場合はシステムプロキシを自動使用',
    setProxyNoDetect: '空欄で自動検出;システムプロキシが見つかりません',
    setInUse: '使用中',
    setEdit: '編集',
    setBaseUrlLabel: 'Base URL',
    setBaseUrlPlaceholder: '空の場合は既定の URL',
    setConnFailedTip: '接続できません。API キーまたは Base URL を確認してください',
    tabHome: 'ホーム',
    setProviderSearch: 'プロバイダーを検索…',
    setConfigTitle: '{name} を設定',
    setApiKeyLabel: 'API Key',
    setModelLabel: 'モデル',
    setModelPlaceholder: 'モデル ID を入力',
    setSecImageGen: '画像生成',
    setKeyConfigured: '設定済み',
    setKeyMissing: '未設定',
    setKeyPlaceholder: 'API キーを貼り付け…',
    setKeyTest: 'テスト',
    setKeyTestOk: '接続成功',
    setKeyTestFail: '接続失敗',
    setKeyClear: 'クリア',
    setKeySaved: '保存しました',
    setKeyCleared: 'クリアしました',
    setSave: '保存',
    setProvidersEmpty: 'プロバイダーが見つかりません(エージェント SDK 未読込)',
    setImageGenHint: 'エージェントの画像ツールのバックエンドを選択します。キーは上記の対応プロバイダーと共有されます。',
    setSecAbout: '情報',
    setChange: '変更',
    // Dates
    today: '今日',
    yesterday: '昨日',
    daysAgo: '{n}日前',
    // Language / tab strip
    language: '言語',
    closeTab: 'タブを閉じる',
    tabList: 'すべてのタブ',
    newTab: '新しいタブ',
  },
  ko: {
    // Sidebar navigation
    navRecent: '최근 사용',
    navStarred: '즐겨찾기',
    cloudSortRecent: '최신순',
    cloudSortOldest: '오래된순',
    navTrash: '휴지통',
    navTrashTip: '삭제된 파일은 시스템 휴지통으로 이동되며 그곳에서 복원할 수 있습니다',
    // Section headings
    secQuickStart: '빠른 시작',
    secRecent: '최근 사용',
    secStarred: '즐겨찾기',
    secProjectFiles: '프로젝트 파일',
    secActivity: '활동',
    colName: '이름',
    colLocation: '위치',
    colModified: '수정한 날짜',
    colSize: '크기',
    // Quick start
    openLocal: '로컬 파일 열기',
    quickAiPpt: 'AI PPT',
    quickAiPptSub: '한 문장으로 전문 프레젠테이션 생성',
    greetMorning: '좋은 아침이에요',
    greetAfternoon: '안녕하세요',
    greetEvening: '좋은 저녁이에요',
    greetAsk1: '오늘은 무엇을 만들까요?',
    greetAsk2: '시작할 준비가 되셨나요?',
    greetAsk3: '무엇을 하고 싶으신가요?',
    greetAsk4: '오늘 어디서부터 시작할까요?',
    greetAsk5: '새로운 걸 만들어 볼까요?',
    greetAsk6: '아이디어가 떠오르셨나요?',
    // Filters
    filterAll: '전체',
    filterSlides: '프레젠테이션',
    filterAria: '유형별 필터',
    // List / bulk actions
    fileCount: '파일 {n}개',
    fileCountOne: '파일 {n}개',
    selectedCount: '{n}개 선택됨',
    selectAll: '모두 선택',
    selectFile: '{name} 선택',
    removeFromList: '목록에서 제거',
    deleteFiles: '파일 삭제',
    cancel: '취소',
    star: '즐겨찾기에 추가',
    unstar: '즐겨찾기에서 제거',
    moreActions: '기타 작업',
    open: '열기',
    revealInFolder: '폴더에서 보기',
    copyPath: '경로 복사',
    moveToProject: '프로젝트로 이동',
    rename: '이름 바꾸기',
    duplicate: '복사본 만들기',
    renameFailed: '이름 바꾸기에 실패했습니다',
    emptyStarred: '즐겨찾기가 없습니다 — 파일 행에 마우스를 올리고 별표를 클릭하세요.',
    emptyRecent: '최근 파일이 없습니다 — 새로 만들거나 파일을 열어 시작하세요.',
    emptyFiltered: '이 유형의 파일이 없습니다.',
    // Delete confirmation dialog
    deleteModalTitle: '파일 삭제',
    deleteConfirmOne: '"{name}"을(를) 휴지통으로 이동하시겠습니까?',
    deleteConfirmMany: '다음 {n}개 파일을 휴지통으로 이동하시겠습니까?',
    deleteMoreCount: '… 외 총 {n}개',
    delete: '삭제',
    // Project sidebar
    projects: '프로젝트',
    newProject: '새 프로젝트',
    projectName: '프로젝트 이름',
    deleteProject: '프로젝트 삭제…',
    deleteProjectConfirm:
      '이 프로젝트를 삭제하시겠습니까?\n프로젝트의 파일은 "기본 프로젝트"로 돌아가며 사라지지 않습니다.',
    projMoreActions: '{name}의 기타 작업',
    defaultProject: '기본 프로젝트',
    projEmpty: '관련 문서를 하나의 프로젝트에 모아 두면 AI 대화 기록이 프로젝트별로 쌓입니다.',
    projEmptyHint:
      '새 파일을 만들거나 "최근 사용"에서 파일을 마우스 오른쪽 버튼으로 클릭해 "프로젝트로 이동"을 선택하세요.',
    timelineCount: '{n}건',
    timelineCountOne: '{n}건',
    timelineEmpty: '이 프로젝트에는 아직 AI 대화 기록이 없습니다.',
    timelineYou: '나',
    timelineUserAria: '사용자',
    untitled: '제목 없음',
    noContent: '(내용 없음)',
    // Account
    appVersion: '버전 {v}',
    versionLabel: '버전',
    aboutAuthor: '작성자',
    starOnGitHub: 'GitHub에서 스타',
    theme: '테마',
    themeLight: '라이트',
    themeDark: '다크',
    themeSystem: '시스템 설정 따르기',
    saveLocation: '저장 위치',
    settings: '설정',
    setSecGeneral: '일반',
    setSecProviders: '모델 공급자',
    setLogin: '로그인',
    setOauthWaiting: '브라우저에서 로그인 페이지를 열었습니다. 완료하거나 아래에 리디렉션을 붙여넣으세요',
    setOauthPastePlaceholder: '리디렉션 URL 또는 코드 붙여넣기…',
    setTestFailTip: '연결할 수 없습니다. API 키 또는 구독을 확인하세요',
    setEnableNeedsTest: '연결 테스트를 통과하면 활성화할 수 있습니다',
    setBedrockHint: 'Amazon Bedrock은 AWS 자격 증명(프로필, IAM 키, bearer 토큰, 역할)을 사용하며 단일 API 키가 없습니다. 환경에서 AWS 자격 증명을 구성하세요.',
    setEnable: '활성화',
    setProxy: '네트워크 프록시',
    setProxyEnable: '프록시 활성화',
    setProxyAuto: '비워 두면 시스템 프록시를 자동 사용',
    setProxyNoDetect: '비워 두면 자동 감지;시스템 프록시가 없습니다',
    setInUse: '사용 중',
    setEdit: '편집',
    setBaseUrlLabel: 'Base URL',
    setBaseUrlPlaceholder: '비워 두면 기본 URL 사용',
    setConnFailedTip: '연결할 수 없습니다. API 키 또는 Base URL을 확인하세요',
    tabHome: '홈',
    setProviderSearch: '공급자 검색…',
    setConfigTitle: '{name} 구성',
    setApiKeyLabel: 'API Key',
    setModelLabel: '모델',
    setModelPlaceholder: '모델 ID 입력',
    setSecImageGen: '이미지 생성',
    setKeyConfigured: '구성됨',
    setKeyMissing: '구성 안 됨',
    setKeyPlaceholder: 'API 키 붙여넣기…',
    setKeyTest: '테스트',
    setKeyTestOk: '연결 성공',
    setKeyTestFail: '연결 실패',
    setKeyClear: '지우기',
    setKeySaved: '저장됨',
    setKeyCleared: '지워짐',
    setSave: '저장',
    setProvidersEmpty: '공급자를 찾을 수 없음(에이전트 SDK 미로드)',
    setImageGenHint: '에이전트 이미지 도구의 백엔드를 선택합니다. 키는 위의 해당 공급자와 공유됩니다.',
    setSecAbout: '정보',
    setChange: '변경',
    // Dates
    today: '오늘',
    yesterday: '어제',
    daysAgo: '{n}일 전',
    // Language / tab strip
    language: '언어',
    closeTab: '탭 닫기',
    tabList: '모든 탭',
    newTab: '새 탭',
  },
  fr: {
    // Sidebar navigation
    navRecent: 'Récents',
    navStarred: 'Favoris',
    cloudSortRecent: 'Récents',
    cloudSortOldest: 'Plus anciens',
    navTrash: 'Corbeille',
    navTrashTip:
      'Les fichiers supprimés sont placés dans la corbeille du système et peuvent y être restaurés',
    // Section headings
    secQuickStart: 'Démarrage rapide',
    secRecent: 'Récents',
    secStarred: 'Favoris',
    secProjectFiles: 'Fichiers du projet',
    secActivity: 'Activité',
    colName: 'Nom',
    colLocation: 'Emplacement',
    colModified: 'Modifié le',
    colSize: 'Taille',
    // Quick start
    openLocal: 'Ouvrir un fichier local',
    quickAiPpt: 'AI PPT',
    quickAiPptSub: 'Générez une présentation pro à partir d’une phrase',
    greetMorning: 'Bonjour',
    greetAfternoon: 'Bonjour',
    greetEvening: 'Bonsoir',
    greetAsk1: 'Que souhaitez-vous créer aujourd’hui ?',
    greetAsk2: 'Prêt à commencer ?',
    greetAsk3: 'Sur quoi travaillez-vous ?',
    greetAsk4: 'Par où commencer aujourd’hui ?',
    greetAsk5: 'Envie de créer quelque chose de nouveau ?',
    greetAsk6: 'Une idée en tête ?',
    // Filters
    filterAll: 'Tous',
    filterSlides: 'Présentations',
    filterAria: 'Filtrer par type',
    // List / bulk actions
    fileCount: '{n} fichiers',
    fileCountOne: '{n} fichier',
    selectedCount: '{n} sélectionné(s)',
    selectAll: 'Tout sélectionner',
    selectFile: 'Sélectionner {name}',
    removeFromList: 'Retirer de la liste',
    deleteFiles: 'Supprimer les fichiers',
    cancel: 'Annuler',
    star: 'Ajouter aux favoris',
    unstar: 'Retirer des favoris',
    moreActions: 'Autres actions',
    open: 'Ouvrir',
    revealInFolder: 'Afficher dans le dossier',
    copyPath: 'Copier le chemin',
    moveToProject: 'Déplacer vers un projet',
    rename: 'Renommer',
    duplicate: 'Dupliquer',
    renameFailed: 'Échec du renommage',
    emptyStarred: "Aucun favori — survolez une ligne et cliquez sur l'étoile.",
    emptyRecent: 'Aucun fichier récent — créez ou ouvrez un fichier pour commencer.',
    emptyFiltered: 'Aucun fichier de ce type.',
    // Delete confirmation dialog
    deleteModalTitle: 'Supprimer les fichiers',
    deleteConfirmOne: 'Déplacer « {name} » vers la corbeille ?',
    deleteConfirmMany: 'Déplacer ces {n} fichiers vers la corbeille ?',
    deleteMoreCount: '… {n} au total',
    delete: 'Supprimer',
    // Project sidebar
    projects: 'Projets',
    newProject: 'Nouveau projet',
    projectName: 'Nom du projet',
    deleteProject: 'Supprimer le projet…',
    deleteProjectConfirm:
      'Supprimer ce projet ?\nSes fichiers retourneront dans le projet par défaut et ne seront pas perdus.',
    projMoreActions: 'Autres actions pour {name}',
    defaultProject: 'Projet par défaut',
    projEmpty:
      "Regroupez les documents associés dans un même projet — l'historique des conversations IA s'accumule par projet.",
    projEmptyHint:
      'Créez un fichier, ou cliquez avec le bouton droit sur un fichier récent et choisissez « Déplacer vers un projet ».',
    timelineCount: '{n} éléments',
    timelineCountOne: '{n} élément',
    timelineEmpty: 'Aucune conversation IA dans ce projet pour le moment.',
    timelineYou: 'Vous',
    timelineUserAria: 'Utilisateur',
    untitled: 'Sans titre',
    noContent: '(vide)',
    // Account
    appVersion: 'Version {v}',
    versionLabel: 'Version',
    aboutAuthor: 'Auteur',
    starOnGitHub: 'Star sur GitHub',
    theme: 'Thème',
    themeLight: 'Clair',
    themeDark: 'Sombre',
    themeSystem: 'Suivre le système',
    saveLocation: "Emplacement d'enregistrement",
    settings: 'Paramètres',
    setSecGeneral: 'Général',
    setSecProviders: 'Fournisseurs de modèles',
    setLogin: 'Se connecter',
    setOauthWaiting: 'La page de connexion est ouverte dans le navigateur — terminez-la ou collez la redirection ci-dessous',
    setOauthPastePlaceholder: "Coller l'URL de redirection ou le code…",
    setTestFailTip: "Connexion impossible — vérifiez la clé API ou l'abonnement",
    setEnableNeedsTest: 'Activable après un test de connexion réussi',
    setBedrockHint: 'Amazon Bedrock utilise les identifiants AWS (profil, clés IAM, jeton bearer ou rôle) — pas de clé API unique. Configurez les identifiants AWS dans votre environnement.',
    setEnable: 'Activer',
    setProxy: 'Proxy réseau',
    setProxyEnable: 'Activer le proxy',
    setProxyAuto: 'Vide = utiliser le proxy système',
    setProxyNoDetect: 'Vide = détection auto ; aucun proxy système détecté',
    setInUse: 'En cours',
    setEdit: 'Modifier',
    setBaseUrlLabel: 'Base URL',
    setBaseUrlPlaceholder: "Laisser vide pour l'endpoint par défaut",
    setConnFailedTip: "Connexion impossible — vérifiez la clé API ou l'URL de base",
    tabHome: 'Accueil',
    setProviderSearch: 'Rechercher un fournisseur…',
    setConfigTitle: 'Configurer {name}',
    setApiKeyLabel: 'API Key',
    setModelLabel: 'Modèle',
    setModelPlaceholder: "Saisir l'ID du modèle",
    setSecImageGen: 'Génération d\'images',
    setKeyConfigured: 'Configuré',
    setKeyMissing: 'Non configuré',
    setKeyPlaceholder: 'Coller la clé API…',
    setKeyTest: 'Tester',
    setKeyTestOk: 'Connexion réussie',
    setKeyTestFail: 'Échec de connexion',
    setKeyClear: 'Effacer',
    setKeySaved: 'Enregistré',
    setKeyCleared: 'Effacé',
    setSave: 'Enregistrer',
    setProvidersEmpty: 'Aucun fournisseur trouvé (SDK agent non chargé)',
    setImageGenHint: 'Choisissez le backend d\'images pour l\'agent ; les clés sont partagées avec le fournisseur correspondant ci-dessus.',
    setSecAbout: 'À propos',
    setChange: 'Modifier',
    // Dates
    today: "Aujourd'hui",
    yesterday: 'Hier',
    daysAgo: 'il y a {n} j',
    // Language / tab strip
    language: 'Langue',
    closeTab: "Fermer l'onglet",
    tabList: 'Tous les onglets',
    newTab: 'Nouvel onglet',
  },
  de: {
    // Sidebar navigation
    navRecent: 'Zuletzt verwendet',
    navStarred: 'Favoriten',
    cloudSortRecent: 'Neueste',
    cloudSortOldest: 'Älteste',
    navTrash: 'Papierkorb',
    navTrashTip:
      'Gelöschte Dateien werden in den System-Papierkorb verschoben und können dort wiederhergestellt werden',
    // Section headings
    secQuickStart: 'Schnellstart',
    secRecent: 'Zuletzt verwendet',
    secStarred: 'Favoriten',
    secProjectFiles: 'Projektdateien',
    secActivity: 'Aktivität',
    colName: 'Name',
    colLocation: 'Speicherort',
    colModified: 'Geändert',
    colSize: 'Größe',
    // Quick start
    openLocal: 'Lokale Datei öffnen',
    quickAiPpt: 'AI PPT',
    quickAiPptSub: 'Professionelles Deck aus einem Satz generieren',
    greetMorning: 'Guten Morgen',
    greetAfternoon: 'Guten Tag',
    greetEvening: 'Guten Abend',
    greetAsk1: 'Was möchten Sie heute erstellen?',
    greetAsk2: 'Bereit loszulegen?',
    greetAsk3: 'Woran arbeiten Sie?',
    greetAsk4: 'Womit sollen wir heute beginnen?',
    greetAsk5: 'Lust auf etwas Neues?',
    greetAsk6: 'Schon eine Idee?',
    // Filters
    filterAll: 'Alle',
    filterSlides: 'Präsentationen',
    filterAria: 'Nach Typ filtern',
    // List / bulk actions
    fileCount: '{n} Dateien',
    fileCountOne: '{n} Datei',
    selectedCount: '{n} ausgewählt',
    selectAll: 'Alle auswählen',
    selectFile: '{name} auswählen',
    removeFromList: 'Aus Liste entfernen',
    deleteFiles: 'Dateien löschen',
    cancel: 'Abbrechen',
    star: 'Zu Favoriten hinzufügen',
    unstar: 'Aus Favoriten entfernen',
    moreActions: 'Weitere Aktionen',
    open: 'Öffnen',
    revealInFolder: 'Im Ordner anzeigen',
    copyPath: 'Pfad kopieren',
    moveToProject: 'In Projekt verschieben',
    rename: 'Umbenennen',
    duplicate: 'Duplizieren',
    renameFailed: 'Umbenennen fehlgeschlagen',
    emptyStarred:
      'Keine Favoriten — bewegen Sie den Mauszeiger über eine Zeile und klicken Sie auf den Stern.',
    emptyRecent:
      'Keine zuletzt verwendeten Dateien — erstellen oder öffnen Sie eine Datei, um zu beginnen.',
    emptyFiltered: 'Keine Dateien dieses Typs.',
    // Delete confirmation dialog
    deleteModalTitle: 'Dateien löschen',
    deleteConfirmOne: '„{name}“ in den Papierkorb verschieben?',
    deleteConfirmMany: 'Diese {n} Dateien in den Papierkorb verschieben?',
    deleteMoreCount: '… insgesamt {n}',
    delete: 'Löschen',
    // Project sidebar
    projects: 'Projekte',
    newProject: 'Neues Projekt',
    projectName: 'Projektname',
    deleteProject: 'Projekt löschen…',
    deleteProjectConfirm:
      'Dieses Projekt löschen?\nSeine Dateien kehren in das Standardprojekt zurück und gehen nicht verloren.',
    projMoreActions: 'Weitere Aktionen für {name}',
    defaultProject: 'Standardprojekt',
    projEmpty:
      'Bewahren Sie zusammengehörige Dokumente in einem Projekt auf — der KI-Chatverlauf sammelt sich pro Projekt an.',
    projEmptyHint:
      'Erstellen Sie eine Datei oder klicken Sie mit der rechten Maustaste auf eine zuletzt verwendete Datei und wählen Sie „In Projekt verschieben“.',
    timelineCount: '{n} Einträge',
    timelineCountOne: '{n} Eintrag',
    timelineEmpty: 'Noch keine KI-Unterhaltungen in diesem Projekt.',
    timelineYou: 'Sie',
    timelineUserAria: 'Benutzer',
    untitled: 'Unbenannt',
    noContent: '(leer)',
    // Account
    appVersion: 'Version {v}',
    versionLabel: 'Version',
    aboutAuthor: 'Autor',
    starOnGitHub: 'Star auf GitHub',
    theme: 'Thema',
    themeLight: 'Hell',
    themeDark: 'Dunkel',
    themeSystem: 'System folgen',
    saveLocation: 'Speicherort',
    settings: 'Einstellungen',
    setSecGeneral: 'Allgemein',
    setSecProviders: 'Modellanbieter',
    setLogin: 'Anmelden',
    setOauthWaiting: 'Anmeldeseite wurde im Browser geöffnet — schließen Sie sie ab oder fügen Sie die Umleitung unten ein',
    setOauthPastePlaceholder: 'Weiterleitungs-URL oder Code einfügen…',
    setTestFailTip: 'Verbindung fehlgeschlagen — API-Schlüssel oder Abo prüfen',
    setEnableNeedsTest: 'Nach erfolgreichem Verbindungstest aktivierbar',
    setBedrockHint: 'Amazon Bedrock verwendet AWS-Anmeldedaten (Profil, IAM-Schlüssel, Bearer-Token oder Rolle) — es gibt keinen einzelnen API-Schlüssel. Konfigurieren Sie AWS-Anmeldedaten in Ihrer Umgebung.',
    setEnable: 'Aktivieren',
    setProxy: 'Netzwerk-Proxy',
    setProxyEnable: 'Proxy aktivieren',
    setProxyAuto: 'Leer = System-Proxy automatisch verwenden',
    setProxyNoDetect: 'Leer = automatisch erkennen; kein System-Proxy gefunden',
    setInUse: 'In Verwendung',
    setEdit: 'Bearbeiten',
    setBaseUrlLabel: 'Base URL',
    setBaseUrlPlaceholder: 'Leer lassen für den Standard-Endpoint',
    setConnFailedTip: 'Verbindung fehlgeschlagen — API-Schlüssel oder Base-URL prüfen',
    tabHome: 'Startseite',
    setProviderSearch: 'Anbieter suchen…',
    setConfigTitle: '{name} konfigurieren',
    setApiKeyLabel: 'API Key',
    setModelLabel: 'Modell',
    setModelPlaceholder: 'Modell-ID eingeben',
    setSecImageGen: 'Bildgenerierung',
    setKeyConfigured: 'Konfiguriert',
    setKeyMissing: 'Nicht konfiguriert',
    setKeyPlaceholder: 'API-Schlüssel einfügen…',
    setKeyTest: 'Testen',
    setKeyTestOk: 'Verbindung OK',
    setKeyTestFail: 'Verbindung fehlgeschlagen',
    setKeyClear: 'Löschen',
    setKeySaved: 'Gespeichert',
    setKeyCleared: 'Gelöscht',
    setSave: 'Speichern',
    setProvidersEmpty: 'Keine Anbieter gefunden (Agent-SDK nicht geladen)',
    setImageGenHint: 'Bild-Backend für das Agenten-Tool wählen; Schlüssel werden vom passenden Anbieter oben übernommen.',
    setSecAbout: 'Über',
    setChange: 'Ändern',
    // Dates
    today: 'Heute',
    yesterday: 'Gestern',
    daysAgo: 'vor {n} Tagen',
    // Language / tab strip
    language: 'Sprache',
    closeTab: 'Tab schließen',
    tabList: 'Alle Tabs',
    newTab: 'Neuer Tab',
  },
  es: {
    // Sidebar navigation
    navRecent: 'Recientes',
    navStarred: 'Destacados',
    cloudSortRecent: 'Recientes',
    cloudSortOldest: 'Más antiguos',
    navTrash: 'Papelera',
    navTrashTip:
      'Los archivos eliminados van a la papelera del sistema y pueden restaurarse desde allí',
    // Section headings
    secQuickStart: 'Inicio rápido',
    secRecent: 'Recientes',
    secStarred: 'Destacados',
    secProjectFiles: 'Archivos del proyecto',
    secActivity: 'Actividad',
    colName: 'Nombre',
    colLocation: 'Ubicación',
    colModified: 'Modificado',
    colSize: 'Tamaño',
    // Quick start
    openLocal: 'Abrir archivo local',
    quickAiPpt: 'AI PPT',
    quickAiPptSub: 'Genera una presentación profesional con una frase',
    greetMorning: 'Buenos días',
    greetAfternoon: 'Buenas tardes',
    greetEvening: 'Buenas noches',
    greetAsk1: '¿Qué quieres crear hoy?',
    greetAsk2: '¿Listo para empezar?',
    greetAsk3: '¿En qué estás trabajando?',
    greetAsk4: '¿Por dónde empezamos hoy?',
    greetAsk5: '¿Te apetece crear algo nuevo?',
    greetAsk6: '¿Alguna idea?',
    // Filters
    filterAll: 'Todos',
    filterSlides: 'Presentaciones',
    filterAria: 'Filtrar por tipo',
    // List / bulk actions
    fileCount: '{n} archivos',
    fileCountOne: '{n} archivo',
    selectedCount: '{n} seleccionados',
    selectAll: 'Seleccionar todo',
    selectFile: 'Seleccionar {name}',
    removeFromList: 'Quitar de la lista',
    deleteFiles: 'Eliminar archivos',
    cancel: 'Cancelar',
    star: 'Destacar',
    unstar: 'Quitar de destacados',
    moreActions: 'Más acciones',
    open: 'Abrir',
    revealInFolder: 'Mostrar en la carpeta',
    copyPath: 'Copiar ruta',
    moveToProject: 'Mover a un proyecto',
    rename: 'Cambiar nombre',
    duplicate: 'Duplicar',
    renameFailed: 'No se pudo cambiar el nombre',
    emptyStarred:
      'No hay archivos destacados — pase el cursor sobre una fila y haga clic en la estrella.',
    emptyRecent: 'No hay archivos recientes — cree o abra un archivo para empezar.',
    emptyFiltered: 'No hay archivos de este tipo.',
    // Delete confirmation dialog
    deleteModalTitle: 'Eliminar archivos',
    deleteConfirmOne: '¿Mover "{name}" a la papelera?',
    deleteConfirmMany: '¿Mover estos {n} archivos a la papelera?',
    deleteMoreCount: '… {n} en total',
    delete: 'Eliminar',
    // Project sidebar
    projects: 'Proyectos',
    newProject: 'Nuevo proyecto',
    projectName: 'Nombre del proyecto',
    deleteProject: 'Eliminar proyecto…',
    deleteProjectConfirm:
      '¿Eliminar este proyecto?\nSus archivos volverán al proyecto predeterminado y no se perderán.',
    projMoreActions: 'Más acciones para {name}',
    defaultProject: 'Proyecto predeterminado',
    projEmpty:
      'Guarde los documentos relacionados en un mismo proyecto — el historial de chat de IA se acumula por proyecto.',
    projEmptyHint:
      'Cree un archivo o haga clic derecho en un archivo reciente y elija "Mover a un proyecto".',
    timelineCount: '{n} elementos',
    timelineCountOne: '{n} elemento',
    timelineEmpty: 'Aún no hay conversaciones de IA en este proyecto.',
    timelineYou: 'Tú',
    timelineUserAria: 'Usuario',
    untitled: 'Sin título',
    noContent: '(vacío)',
    // Account
    appVersion: 'Versión {v}',
    versionLabel: 'Versión',
    aboutAuthor: 'Autor',
    starOnGitHub: 'Estrella en GitHub',
    theme: 'Tema',
    themeLight: 'Claro',
    themeDark: 'Oscuro',
    themeSystem: 'Seguir el sistema',
    saveLocation: 'Ubicación de guardado',
    settings: 'Configuración',
    setSecGeneral: 'General',
    setSecProviders: 'Proveedores de modelos',
    setLogin: 'Iniciar sesión',
    setOauthWaiting: 'Se abrió el inicio de sesión en el navegador: termínalo o pega la redirección abajo',
    setOauthPastePlaceholder: 'Pegar URL de redirección o código…',
    setTestFailTip: 'No se pudo conectar: comprueba la clave API o la suscripción',
    setEnableNeedsTest: 'Actívalo tras superar la prueba de conexión',
    setBedrockHint: 'Amazon Bedrock usa credenciales de AWS (perfil, claves IAM, token bearer o rol); no hay una sola clave API. Configura las credenciales de AWS en tu entorno.',
    setEnable: 'Activar',
    setProxy: 'Proxy de red',
    setProxyEnable: 'Activar proxy',
    setProxyAuto: 'Vacío = usar el proxy del sistema',
    setProxyNoDetect: 'Vacío = detección automática; no se detectó proxy del sistema',
    setInUse: 'En uso',
    setEdit: 'Editar',
    setBaseUrlLabel: 'Base URL',
    setBaseUrlPlaceholder: 'Dejar vacío para el endpoint predeterminado',
    setConnFailedTip: 'No se pudo conectar: comprueba la clave de API o la URL base',
    tabHome: 'Inicio',
    setProviderSearch: 'Buscar proveedores…',
    setConfigTitle: 'Configurar {name}',
    setApiKeyLabel: 'API Key',
    setModelLabel: 'Modelo',
    setModelPlaceholder: 'Introducir ID del modelo',
    setSecImageGen: 'Generación de imágenes',
    setKeyConfigured: 'Configurado',
    setKeyMissing: 'No configurado',
    setKeyPlaceholder: 'Pegar clave API…',
    setKeyTest: 'Probar',
    setKeyTestOk: 'Conexión correcta',
    setKeyTestFail: 'Conexión fallida',
    setKeyClear: 'Borrar',
    setKeySaved: 'Guardado',
    setKeyCleared: 'Borrado',
    setSave: 'Guardar',
    setProvidersEmpty: 'No se encontraron proveedores (SDK del agente no cargado)',
    setImageGenHint: 'Elige el backend de imágenes para el agente; las claves se reutilizan del proveedor correspondiente.',
    setSecAbout: 'Acerca de',
    setChange: 'Cambiar',
    // Dates
    today: 'Hoy',
    yesterday: 'Ayer',
    daysAgo: 'hace {n} días',
    // Language / tab strip
    language: 'Idioma',
    closeTab: 'Cerrar pestaña',
    tabList: 'Todas las pestañas',
    newTab: 'Nueva pestaña',
  },
  th: {
    // Sidebar navigation
    navRecent: 'ล่าสุด',
    navStarred: 'รายการโปรด',
    cloudSortRecent: 'ล่าสุด',
    cloudSortOldest: 'เก่าสุด',
    navTrash: 'ถังขยะ',
    navTrashTip: 'ไฟล์ที่ถูกลบจะถูกย้ายไปยังถังขยะของระบบ และสามารถกู้คืนได้จากที่นั่น',
    // Section headings
    secQuickStart: 'เริ่มต้นอย่างรวดเร็ว',
    secRecent: 'ใช้งานล่าสุด',
    secStarred: 'รายการโปรด',
    secProjectFiles: 'ไฟล์โปรเจ็กต์',
    secActivity: 'กิจกรรม',
    colName: 'ชื่อ',
    colLocation: 'ตำแหน่งที่ตั้ง',
    colModified: 'แก้ไขเมื่อ',
    colSize: 'ขนาด',
    // Quick start
    openLocal: 'เปิดไฟล์ในเครื่อง',
    quickAiPpt: 'AI PPT',
    quickAiPptSub: 'สร้างงานนำเสนอมืออาชีพจากประโยคเดียว',
    greetMorning: 'สวัสดีตอนเช้า',
    greetAfternoon: 'สวัสดีตอนบ่าย',
    greetEvening: 'สวัสดีตอนเย็น',
    greetAsk1: 'วันนี้อยากสร้างอะไร',
    greetAsk2: 'พร้อมเริ่มต้นหรือยัง',
    greetAsk3: 'อยากทำอะไรดี',
    greetAsk4: 'วันนี้เริ่มจากตรงไหนดี',
    greetAsk5: 'อยากลองทำอะไรใหม่ไหม',
    greetAsk6: 'มีไอเดียอะไรบ้าง',
    // Filters
    filterAll: 'ทั้งหมด',
    filterSlides: 'งานนำเสนอ',
    filterAria: 'กรองตามชนิด',
    // List / bulk actions
    fileCount: '{n} ไฟล์',
    fileCountOne: '{n} ไฟล์',
    selectedCount: 'เลือกแล้ว {n} รายการ',
    selectAll: 'เลือกทั้งหมด',
    selectFile: 'เลือก {name}',
    removeFromList: 'นำออกจากรายการ',
    deleteFiles: 'ลบไฟล์',
    cancel: 'ยกเลิก',
    star: 'เพิ่มในรายการโปรด',
    unstar: 'นำออกจากรายการโปรด',
    moreActions: 'การดำเนินการเพิ่มเติม',
    open: 'เปิด',
    revealInFolder: 'แสดงในโฟลเดอร์',
    copyPath: 'คัดลอกเส้นทาง',
    moveToProject: 'ย้ายไปยังโปรเจ็กต์',
    rename: 'เปลี่ยนชื่อ',
    duplicate: 'สร้างสำเนา',
    renameFailed: 'เปลี่ยนชื่อไม่สำเร็จ',
    emptyStarred: 'ยังไม่มีรายการโปรด — วางเมาส์เหนือแถวไฟล์แล้วคลิกดาว',
    emptyRecent: 'ยังไม่มีไฟล์ล่าสุด — สร้างหรือเปิดไฟล์เพื่อเริ่มต้น',
    emptyFiltered: 'ไม่มีไฟล์ชนิดนี้',
    // Delete confirmation dialog
    deleteModalTitle: 'ลบไฟล์',
    deleteConfirmOne: 'ย้าย "{name}" ไปยังถังขยะหรือไม่',
    deleteConfirmMany: 'ย้ายไฟล์ {n} ไฟล์นี้ไปยังถังขยะหรือไม่',
    deleteMoreCount: '… รวมทั้งหมด {n} ไฟล์',
    delete: 'ลบ',
    // Project sidebar
    projects: 'โปรเจ็กต์',
    newProject: 'โปรเจ็กต์ใหม่',
    projectName: 'ชื่อโปรเจ็กต์',
    deleteProject: 'ลบโปรเจ็กต์…',
    deleteProjectConfirm:
      'ลบโปรเจ็กต์นี้หรือไม่\nไฟล์ในโปรเจ็กต์จะกลับไปยัง "โปรเจ็กต์เริ่มต้น" และจะไม่สูญหาย',
    projMoreActions: 'การดำเนินการเพิ่มเติมสำหรับ {name}',
    defaultProject: 'โปรเจ็กต์เริ่มต้น',
    projEmpty:
      'เก็บเอกสารที่เกี่ยวข้องไว้ในโปรเจ็กต์เดียวกัน — ประวัติการสนทนา AI จะสะสมตามโปรเจ็กต์',
    projEmptyHint: 'สร้างไฟล์ใหม่ หรือคลิกขวาที่ไฟล์ล่าสุดแล้วเลือก "ย้ายไปยังโปรเจ็กต์"',
    timelineCount: '{n} รายการ',
    timelineCountOne: '{n} รายการ',
    timelineEmpty: 'โปรเจ็กต์นี้ยังไม่มีประวัติการสนทนา AI',
    timelineYou: 'คุณ',
    timelineUserAria: 'ผู้ใช้',
    untitled: 'ไม่มีชื่อ',
    noContent: '(ไม่มีเนื้อหา)',
    // Account
    appVersion: 'เวอร์ชัน {v}',
    versionLabel: 'เวอร์ชัน',
    aboutAuthor: 'ผู้เขียน',
    starOnGitHub: 'กด Star บน GitHub',
    theme: 'ธีม',
    themeLight: 'สว่าง',
    themeDark: 'มืด',
    themeSystem: 'ตามระบบ',
    saveLocation: 'ตำแหน่งบันทึก',
    settings: 'การตั้งค่า',
    setSecGeneral: 'ทั่วไป',
    setSecProviders: 'ผู้ให้บริการโมเดล',
    setLogin: 'เข้าสู่ระบบ',
    setOauthWaiting: 'เปิดหน้าลงชื่อเข้าใช้ในเบราว์เซอร์แล้ว ทำให้เสร็จหรือวาง URL ด้านล่าง',
    setOauthPastePlaceholder: 'วาง URL เปลี่ยนเส้นทางหรือรหัส…',
    setTestFailTip: 'ไม่สามารถเชื่อมต่อได้ โปรดตรวจสอบ API key หรือการสมัครสมาชิก',
    setEnableNeedsTest: 'เปิดใช้ได้หลังผ่านการทดสอบการเชื่อมต่อ',
    setBedrockHint: 'Amazon Bedrock ใช้ข้อมูลรับรอง AWS (โปรไฟล์, คีย์ IAM, bearer token หรือ role) ไม่มี API key เดียว โปรดตั้งค่าข้อมูลรับรอง AWS ในสภาพแวดล้อมของคุณ',
    setEnable: 'เปิดใช้',
    setProxy: 'พร็อกซีเครือข่าย',
    setProxyEnable: 'เปิดใช้พร็อกซี',
    setProxyAuto: 'เว้นว่าง = ใช้พร็อกซีของระบบโดยอัตโนมัติ',
    setProxyNoDetect: 'เว้นว่าง = ตรวจหาอัตโนมัติ; ไม่พบพร็อกซีของระบบ',
    setInUse: 'กำลังใช้งาน',
    setEdit: 'แก้ไข',
    setBaseUrlLabel: 'Base URL',
    setBaseUrlPlaceholder: 'เว้นว่างเพื่อใช้ endpoint เริ่มต้น',
    setConnFailedTip: 'เชื่อมต่อไม่ได้ โปรดตรวจสอบ API key หรือ Base URL',
    tabHome: 'หน้าแรก',
    setProviderSearch: 'ค้นหาผู้ให้บริการ…',
    setConfigTitle: 'กำหนดค่า {name}',
    setApiKeyLabel: 'API Key',
    setModelLabel: 'โมเดล',
    setModelPlaceholder: 'ป้อน ID โมเดล',
    setSecImageGen: 'สร้างภาพ',
    setKeyConfigured: 'ตั้งค่าแล้ว',
    setKeyMissing: 'ยังไม่ได้ตั้งค่า',
    setKeyPlaceholder: 'วาง API key…',
    setKeyTest: 'ทดสอบ',
    setKeyTestOk: 'เชื่อมต่อสำเร็จ',
    setKeyTestFail: 'เชื่อมต่อล้มเหลว',
    setKeyClear: 'ล้าง',
    setKeySaved: 'บันทึกแล้ว',
    setKeyCleared: 'ล้างแล้ว',
    setSave: 'บันทึก',
    setProvidersEmpty: 'ไม่พบผู้ให้บริการ (ยังไม่ได้โหลด SDK เอเจนต์)',
    setImageGenHint: 'เลือกแบ็กเอนด์สร้างภาพสำหรับเอเจนต์ คีย์จะใช้ร่วมกับผู้ให้บริการด้านบน',
    setSecAbout: 'เกี่ยวกับ',
    setChange: 'เปลี่ยน',
    // Dates
    today: 'วันนี้',
    yesterday: 'เมื่อวาน',
    daysAgo: '{n} วันที่แล้ว',
    // Language / tab strip
    language: 'ภาษา',
    closeTab: 'ปิดแท็บ',
    tabList: 'แท็บทั้งหมด',
    newTab: 'แท็บใหม่',
  },
  id: {
    // Sidebar navigation
    navRecent: 'Terbaru',
    navStarred: 'Berbintang',
    cloudSortRecent: 'Terbaru',
    cloudSortOldest: 'Terlama',
    navTrash: 'Sampah',
    navTrashTip:
      'File yang dihapus akan dipindahkan ke tempat sampah sistem dan dapat dipulihkan dari sana',
    // Section headings
    secQuickStart: 'Mulai cepat',
    secRecent: 'Terbaru',
    secStarred: 'Berbintang',
    secProjectFiles: 'File proyek',
    secActivity: 'Aktivitas',
    colName: 'Nama',
    colLocation: 'Lokasi',
    colModified: 'Diubah',
    colSize: 'Ukuran',
    // Quick start
    openLocal: 'Buka File Lokal',
    quickAiPpt: 'AI PPT',
    quickAiPptSub: 'Buat deck profesional dari satu kalimat',
    greetMorning: 'Selamat pagi',
    greetAfternoon: 'Selamat siang',
    greetEvening: 'Selamat malam',
    greetAsk1: 'Mau membuat apa hari ini?',
    greetAsk2: 'Siap mulai?',
    greetAsk3: 'Ada yang ingin dikerjakan?',
    greetAsk4: 'Mulai dari mana hari ini?',
    greetAsk5: 'Mau buat sesuatu yang baru?',
    greetAsk6: 'Ada ide bagus?',
    // Filters
    filterAll: 'Semua',
    filterSlides: 'Presentasi',
    filterAria: 'Filter menurut jenis',
    // List / bulk actions
    fileCount: '{n} file',
    fileCountOne: '{n} file',
    selectedCount: '{n} dipilih',
    selectAll: 'Pilih semua',
    selectFile: 'Pilih {name}',
    removeFromList: 'Hapus dari daftar',
    deleteFiles: 'Hapus file',
    cancel: 'Batal',
    star: 'Beri bintang',
    unstar: 'Hapus bintang',
    moreActions: 'Tindakan lainnya',
    open: 'Buka',
    revealInFolder: 'Tampilkan di folder',
    copyPath: 'Salin jalur',
    moveToProject: 'Pindahkan ke proyek',
    rename: 'Ganti nama',
    duplicate: 'Duplikat',
    renameFailed: 'Gagal mengganti nama',
    emptyStarred: 'Belum ada file berbintang — arahkan kursor ke baris file lalu klik bintang.',
    emptyRecent: 'Belum ada file terbaru — buat atau buka file untuk memulai.',
    emptyFiltered: 'Tidak ada file jenis ini.',
    // Delete confirmation dialog
    deleteModalTitle: 'Hapus File',
    deleteConfirmOne: 'Pindahkan "{name}" ke tempat sampah?',
    deleteConfirmMany: 'Pindahkan {n} file ini ke tempat sampah?',
    deleteMoreCount: '… total {n} file',
    delete: 'Hapus',
    // Project sidebar
    projects: 'Proyek',
    newProject: 'Proyek baru',
    projectName: 'Nama proyek',
    deleteProject: 'Hapus proyek…',
    deleteProjectConfirm:
      'Hapus proyek ini?\nFile di dalamnya akan kembali ke Proyek Default dan tidak akan hilang.',
    projMoreActions: 'Tindakan lainnya untuk {name}',
    defaultProject: 'Proyek default',
    projEmpty:
      'Simpan dokumen terkait dalam satu proyek — riwayat percakapan AI terkumpul per proyek.',
    projEmptyHint: 'Buat file, atau klik kanan file terbaru dan pilih "Pindahkan ke proyek".',
    timelineCount: '{n} item',
    timelineCountOne: '{n} item',
    timelineEmpty: 'Belum ada percakapan AI di proyek ini.',
    timelineYou: 'Anda',
    timelineUserAria: 'Pengguna',
    untitled: 'Tanpa judul',
    noContent: '(kosong)',
    // Account
    appVersion: 'Versi {v}',
    versionLabel: 'Versi',
    aboutAuthor: 'Penulis',
    starOnGitHub: 'Beri bintang di GitHub',
    theme: 'Tema',
    themeLight: 'Terang',
    themeDark: 'Gelap',
    themeSystem: 'Ikuti Sistem',
    saveLocation: 'Lokasi penyimpanan',
    settings: 'Pengaturan',
    setSecGeneral: 'Umum',
    setSecProviders: 'Penyedia model',
    setLogin: 'Masuk',
    setOauthWaiting: 'Halaman login dibuka di browser — selesaikan atau tempel URL di bawah',
    setOauthPastePlaceholder: 'Tempel URL pengalihan atau kode…',
    setTestFailTip: 'Tidak dapat terhubung — periksa API key atau langganan',
    setEnableNeedsTest: 'Aktifkan setelah uji konektivitas berhasil',
    setBedrockHint: 'Amazon Bedrock memakai kredensial AWS (profil, kunci IAM, bearer token, atau role) — tidak ada API key tunggal. Konfigurasikan kredensial AWS di lingkungan Anda.',
    setEnable: 'Aktifkan',
    setProxy: 'Proksi jaringan',
    setProxyEnable: 'Aktifkan proksi',
    setProxyAuto: 'Kosong = gunakan proksi sistem',
    setProxyNoDetect: 'Kosong = deteksi otomatis; tidak ada proksi sistem',
    setInUse: 'Digunakan',
    setEdit: 'Edit',
    setBaseUrlLabel: 'Base URL',
    setBaseUrlPlaceholder: 'Kosongkan untuk endpoint default',
    setConnFailedTip: 'Tidak dapat terhubung — periksa API key atau Base URL',
    tabHome: 'Beranda',
    setProviderSearch: 'Cari penyedia…',
    setConfigTitle: 'Konfigurasi {name}',
    setApiKeyLabel: 'API Key',
    setModelLabel: 'Model',
    setModelPlaceholder: 'Masukkan ID model',
    setSecImageGen: 'Pembuatan gambar',
    setKeyConfigured: 'Terkonfigurasi',
    setKeyMissing: 'Belum dikonfigurasi',
    setKeyPlaceholder: 'Tempel API key…',
    setKeyTest: 'Uji',
    setKeyTestOk: 'Koneksi berhasil',
    setKeyTestFail: 'Koneksi gagal',
    setKeyClear: 'Hapus',
    setKeySaved: 'Tersimpan',
    setKeyCleared: 'Terhapus',
    setSave: 'Simpan',
    setProvidersEmpty: 'Tidak ada penyedia (SDK agen belum dimuat)',
    setImageGenHint: 'Pilih backend gambar untuk alat agen; kunci dipakai bersama penyedia terkait di atas.',
    setSecAbout: 'Tentang',
    setChange: 'Ubah',
    // Dates
    today: 'Hari ini',
    yesterday: 'Kemarin',
    daysAgo: '{n} hari lalu',
    // Language / tab strip
    language: 'Bahasa',
    closeTab: 'Tutup tab',
    tabList: 'Semua tab',
    newTab: 'Tab baru',
  },
  ru: {
    // Sidebar navigation
    navRecent: 'Недавние',
    navStarred: 'Избранное',
    cloudSortRecent: 'Сначала новые',
    cloudSortOldest: 'Сначала старые',
    navTrash: 'Корзина',
    navTrashTip: 'Удалённые файлы перемещаются в системную корзину, откуда их можно восстановить',
    // Section headings
    secQuickStart: 'Быстрый старт',
    secRecent: 'Недавние',
    secStarred: 'Избранное',
    secProjectFiles: 'Файлы проекта',
    secActivity: 'Активность',
    colName: 'Имя',
    colLocation: 'Расположение',
    colModified: 'Изменён',
    colSize: 'Размер',
    // Quick start
    openLocal: 'Открыть локальный файл',
    quickAiPpt: 'AI PPT',
    quickAiPptSub: 'Профессиональная презентация по одной фразе',
    greetMorning: 'Доброе утро',
    greetAfternoon: 'Добрый день',
    greetEvening: 'Добрый вечер',
    greetAsk1: 'Что создадим сегодня?',
    greetAsk2: 'Готовы начать?',
    greetAsk3: 'Над чем работаем?',
    greetAsk4: 'С чего начнём сегодня?',
    greetAsk5: 'Хотите создать что-то новое?',
    greetAsk6: 'Есть идея?',
    // Filters
    filterAll: 'Все',
    filterSlides: 'Презентации',
    filterAria: 'Фильтр по типу',
    // List / bulk actions
    fileCount: 'Файлов: {n}',
    fileCountOne: '{n} файл',
    selectedCount: 'Выбрано: {n}',
    selectAll: 'Выбрать все',
    selectFile: 'Выбрать {name}',
    removeFromList: 'Убрать из списка',
    deleteFiles: 'Удалить файлы',
    cancel: 'Отмена',
    star: 'В избранное',
    unstar: 'Убрать из избранного',
    moreActions: 'Другие действия',
    open: 'Открыть',
    revealInFolder: 'Показать в папке',
    copyPath: 'Скопировать путь',
    moveToProject: 'Переместить в проект',
    rename: 'Переименовать',
    duplicate: 'Создать копию',
    renameFailed: 'Не удалось переименовать',
    emptyStarred:
      'В избранном пока пусто — наведите курсор на строку файла и нажмите на звёздочку.',
    emptyRecent: 'Нет недавних файлов — создайте или откройте файл, чтобы начать.',
    emptyFiltered: 'Файлов этого типа нет.',
    // Delete confirmation dialog
    deleteModalTitle: 'Удаление файлов',
    deleteConfirmOne: 'Переместить «{name}» в корзину?',
    deleteConfirmMany: 'Переместить эти файлы ({n}) в корзину?',
    deleteMoreCount: '… всего {n}',
    delete: 'Удалить',
    // Project sidebar
    projects: 'Проекты',
    newProject: 'Создать проект',
    projectName: 'Название проекта',
    deleteProject: 'Удалить проект…',
    deleteProjectConfirm:
      'Удалить этот проект?\nЕго файлы вернутся в проект по умолчанию и не будут потеряны.',
    projMoreActions: 'Другие действия для {name}',
    defaultProject: 'Проект по умолчанию',
    projEmpty:
      'Храните связанные документы в одном проекте — история диалогов с ИИ накапливается по проектам.',
    projEmptyHint:
      'Создайте файл или щёлкните недавний файл правой кнопкой мыши и выберите «Переместить в проект».',
    timelineCount: 'Записей: {n}',
    timelineCountOne: '{n} запись',
    timelineEmpty: 'В этом проекте пока нет диалогов с ИИ.',
    timelineYou: 'Вы',
    timelineUserAria: 'Пользователь',
    untitled: 'Без названия',
    noContent: '(пусто)',
    // Account
    appVersion: 'Версия {v}',
    versionLabel: 'Версия',
    aboutAuthor: 'Автор',
    starOnGitHub: 'Звезда на GitHub',
    theme: 'Тема',
    themeLight: 'Светлая',
    themeDark: 'Тёмная',
    themeSystem: 'Как в системе',
    saveLocation: 'Папка сохранения',
    settings: 'Настройки',
    setSecGeneral: 'Общие',
    setSecProviders: 'Провайдеры моделей',
    setLogin: 'Войти',
    setOauthWaiting: 'Страница входа открыта в браузере — завершите вход или вставьте URL ниже',
    setOauthPastePlaceholder: 'Вставьте URL перенаправления или код…',
    setTestFailTip: 'Не удается подключиться — проверьте API-ключ или подписку',
    setEnableNeedsTest: 'Доступно после успешной проверки подключения',
    setBedrockHint: 'Amazon Bedrock использует учётные данные AWS (профиль, ключи IAM, bearer-токен или роль) — единого API-ключа нет. Настройте учётные данные AWS в окружении.',
    setEnable: 'Включить',
    setProxy: 'Сетевой прокси',
    setProxyEnable: 'Включить прокси',
    setProxyAuto: 'Пусто = использовать системный прокси',
    setProxyNoDetect: 'Пусто = автоопределение; системный прокси не найден',
    setInUse: 'Используется',
    setEdit: 'Изменить',
    setBaseUrlLabel: 'Base URL',
    setBaseUrlPlaceholder: 'Оставьте пустым для endpoint по умолчанию',
    setConnFailedTip: 'Не удаётся подключиться — проверьте API-ключ или Base URL',
    tabHome: 'Главная',
    setProviderSearch: 'Поиск провайдеров…',
    setConfigTitle: 'Настройка {name}',
    setApiKeyLabel: 'API Key',
    setModelLabel: 'Модель',
    setModelPlaceholder: 'Введите ID модели',
    setSecImageGen: 'Генерация изображений',
    setKeyConfigured: 'Настроено',
    setKeyMissing: 'Не настроено',
    setKeyPlaceholder: 'Вставьте API-ключ…',
    setKeyTest: 'Проверить',
    setKeyTestOk: 'Подключено',
    setKeyTestFail: 'Ошибка подключения',
    setKeyClear: 'Очистить',
    setKeySaved: 'Сохранено',
    setKeyCleared: 'Очищено',
    setSave: 'Сохранить',
    setProvidersEmpty: 'Провайдеры не найдены (SDK агента не загружен)',
    setImageGenHint: 'Выберите бэкенд генерации изображений для агента; ключи общие с соответствующим провайдером выше.',
    setSecAbout: 'О программе',
    setChange: 'Изменить',
    // Dates
    today: 'Сегодня',
    yesterday: 'Вчера',
    daysAgo: '{n} дн. назад',
    // Language / tab strip
    language: 'Язык',
    closeTab: 'Закрыть вкладку',
    tabList: 'Все вкладки',
    newTab: 'Новая вкладка',
  },
  ar: {
    // Sidebar navigation
    navRecent: 'الأخيرة',
    navStarred: 'المفضلة',
    cloudSortRecent: 'الأحدث',
    cloudSortOldest: 'الأقدم',
    navTrash: 'سلة المهملات',
    navTrashTip: 'تُنقل الملفات المحذوفة إلى سلة مهملات النظام ويمكن استعادتها من هناك',
    // Section headings
    secQuickStart: 'بدء سريع',
    secRecent: 'المستخدمة مؤخرًا',
    secStarred: 'المفضلة',
    secProjectFiles: 'ملفات المشروع',
    secActivity: 'النشاط',
    colName: 'الاسم',
    colLocation: 'الموقع',
    colModified: 'تاريخ التعديل',
    colSize: 'الحجم',
    // Quick start
    openLocal: 'فتح ملف محلي',
    quickAiPpt: 'AI PPT',
    quickAiPptSub: 'أنشئ عرضًا احترافيًا من جملة واحدة',
    greetMorning: 'صباح الخير',
    greetAfternoon: 'مساء الخير',
    greetEvening: 'مساء الخير',
    greetAsk1: 'ماذا تريد أن تنشئ اليوم؟',
    greetAsk2: 'هل أنت مستعد للبدء؟',
    greetAsk3: 'على ماذا تعمل؟',
    greetAsk4: 'من أين نبدأ اليوم؟',
    greetAsk5: 'هل ترغب في إنشاء شيء جديد؟',
    greetAsk6: 'هل لديك فكرة؟',
    // Filters
    filterAll: 'الكل',
    filterSlides: 'عروض تقديمية',
    filterAria: 'تصفية حسب النوع',
    // List / bulk actions
    fileCount: '{n} ملفات',
    fileCountOne: 'ملف واحد',
    selectedCount: 'تم تحديد {n}',
    selectAll: 'تحديد الكل',
    selectFile: 'تحديد {name}',
    removeFromList: 'إزالة من القائمة',
    deleteFiles: 'حذف الملفات',
    cancel: 'إلغاء',
    star: 'إضافة إلى المفضلة',
    unstar: 'إزالة من المفضلة',
    moreActions: 'إجراءات أخرى',
    open: 'فتح',
    revealInFolder: 'إظهار في المجلد',
    copyPath: 'نسخ المسار',
    moveToProject: 'نقل إلى مشروع',
    rename: 'إعادة تسمية',
    duplicate: 'إنشاء نسخة',
    renameFailed: 'فشلت إعادة التسمية',
    emptyStarred: 'لا توجد ملفات مفضلة — مرِّر المؤشر فوق صف الملف وانقر على النجمة.',
    emptyRecent: 'لا توجد ملفات حديثة — أنشئ ملفًا أو افتحه للبدء.',
    emptyFiltered: 'لا توجد ملفات من هذا النوع.',
    // Delete confirmation dialog
    deleteModalTitle: 'حذف الملفات',
    deleteConfirmOne: 'هل تريد نقل "{name}" إلى سلة المهملات؟',
    deleteConfirmMany: 'هل تريد نقل هذه الملفات ({n}) إلى سلة المهملات؟',
    deleteMoreCount: '… الإجمالي {n}',
    delete: 'حذف',
    // Project sidebar
    projects: 'المشاريع',
    newProject: 'مشروع جديد',
    projectName: 'اسم المشروع',
    deleteProject: 'حذف المشروع…',
    deleteProjectConfirm:
      'هل تريد حذف هذا المشروع؟\nستعود ملفاته إلى "المشروع الافتراضي" ولن تُفقد.',
    projMoreActions: 'إجراءات أخرى لـ {name}',
    defaultProject: 'المشروع الافتراضي',
    projEmpty:
      'احتفظ بالمستندات المرتبطة في مشروع واحد — يتراكم سجل محادثات الذكاء الاصطناعي لكل مشروع.',
    projEmptyHint: 'أنشئ ملفًا، أو انقر بزر الماوس الأيمن على ملف حديث واختر "نقل إلى مشروع".',
    timelineCount: '{n} عناصر',
    timelineCountOne: 'عنصر واحد',
    timelineEmpty: 'لا توجد محادثات ذكاء اصطناعي في هذا المشروع بعد.',
    timelineYou: 'أنت',
    timelineUserAria: 'المستخدم',
    untitled: 'بدون عنوان',
    noContent: '(فارغ)',
    // Account
    appVersion: 'الإصدار {v}',
    versionLabel: 'الإصدار',
    aboutAuthor: 'المؤلف',
    starOnGitHub: 'أضف نجمة على GitHub',
    theme: 'المظهر',
    themeLight: 'فاتح',
    themeDark: 'داكن',
    themeSystem: 'اتباع النظام',
    saveLocation: 'موقع الحفظ',
    settings: 'الإعدادات',
    setSecGeneral: 'عام',
    setSecProviders: 'موفرو النماذج',
    setLogin: 'تسجيل الدخول',
    setOauthWaiting: 'تم فتح صفحة تسجيل الدخول في المتصفح — أكملها أو الصق عنوان إعادة التوجيه أدناه',
    setOauthPastePlaceholder: 'الصق عنوان URL لإعادة التوجيه أو الرمز…',
    setTestFailTip: 'تعذّر الاتصال — تحقق من مفتاح API أو الاشتراك',
    setEnableNeedsTest: 'يُفعَّل بعد نجاح اختبار الاتصال',
    setBedrockHint: 'يستخدم Amazon Bedrock بيانات اعتماد AWS (ملف شخصي أو مفاتيح IAM أو رمز bearer أو دور) — لا يوجد مفتاح API واحد. قم بتكوين بيانات اعتماد AWS في بيئتك.',
    setEnable: 'تمكين',
    setProxy: 'وكيل الشبكة',
    setProxyEnable: 'تمكين الوكيل',
    setProxyAuto: 'فارغ = استخدام وكيل النظام تلقائيًا',
    setProxyNoDetect: 'فارغ = كشف تلقائي؛ لم يتم العثور على وكيل نظام',
    setInUse: 'قيد الاستخدام',
    setEdit: 'تحرير',
    setBaseUrlLabel: 'Base URL',
    setBaseUrlPlaceholder: 'اتركه فارغًا لنقطة النهاية الافتراضية',
    setConnFailedTip: 'تعذّر الاتصال — تحقق من مفتاح API أو عنوان Base URL',
    tabHome: 'الصفحة الرئيسية',
    setProviderSearch: 'ابحث عن المزوّدين…',
    setConfigTitle: 'تهيئة {name}',
    setApiKeyLabel: 'API Key',
    setModelLabel: 'النموذج',
    setModelPlaceholder: 'أدخل معرّف النموذج',
    setSecImageGen: 'توليد الصور',
    setKeyConfigured: 'تم التكوين',
    setKeyMissing: 'غير مكوَّن',
    setKeyPlaceholder: 'الصق مفتاح API…',
    setKeyTest: 'اختبار',
    setKeyTestOk: 'تم الاتصال',
    setKeyTestFail: 'فشل الاتصال',
    setKeyClear: 'مسح',
    setKeySaved: 'تم الحفظ',
    setKeyCleared: 'تم المسح',
    setSave: 'حفظ',
    setProvidersEmpty: 'لم يتم العثور على موفرين (لم يُحمَّل SDK الوكيل)',
    setImageGenHint: 'اختر خلفية توليد الصور لأداة الوكيل؛ تُعاد مشاركة المفاتيح من الموفر المطابق أعلاه.',
    setSecAbout: 'حول',
    setChange: 'تغيير',
    // Dates
    today: 'اليوم',
    yesterday: 'أمس',
    daysAgo: 'قبل {n} أيام',
    // Language / tab strip
    language: 'اللغة',
    closeTab: 'إغلاق علامة التبويب',
    tabList: 'كل علامات التبويب',
    newTab: 'علامة تبويب جديدة',
  },
  pt: {
    navRecent: 'Recentes',
    navStarred: 'Favoritos',
    cloudSortRecent: 'Recentes',
    cloudSortOldest: 'Mais antigos',
    navTrash: 'Lixeira',
    navTrashTip:
      'Os arquivos excluídos vão para a lixeira do sistema e podem ser restaurados de lá',
    secQuickStart: 'Início rápido',
    secRecent: 'Recentes',
    secStarred: 'Favoritos',
    secProjectFiles: 'Arquivos do projeto',
    secActivity: 'Atividade',
    colName: 'Nome',
    colLocation: 'Local',
    colModified: 'Modificado',
    colSize: 'Tamanho',
    openLocal: 'Abrir arquivo local',
    quickAiPpt: 'AI PPT',
    quickAiPptSub: 'Gere uma apresentação profissional a partir de uma frase',
    greetMorning: 'Bom dia',
    greetAfternoon: 'Boa tarde',
    greetEvening: 'Boa noite',
    greetAsk1: 'O que você quer criar hoje?',
    greetAsk2: 'Pronto para começar?',
    greetAsk3: 'No que você está trabalhando?',
    greetAsk4: 'Por onde começamos hoje?',
    greetAsk5: 'Que tal criar algo novo?',
    greetAsk6: 'Alguma ideia?',
    filterAll: 'Todos',
    filterSlides: 'Apresentações',
    filterAria: 'Filtrar por tipo',
    fileCount: '{n} arquivos',
    fileCountOne: '{n} arquivo',
    selectedCount: '{n} selecionados',
    selectAll: 'Selecionar tudo',
    selectFile: 'Selecionar {name}',
    removeFromList: 'Remover da lista',
    deleteFiles: 'Excluir arquivos',
    cancel: 'Cancelar',
    star: 'Adicionar aos favoritos',
    unstar: 'Remover dos favoritos',
    moreActions: 'Mais ações',
    open: 'Abrir',
    revealInFolder: 'Mostrar na pasta',
    copyPath: 'Copiar caminho',
    moveToProject: 'Mover para um projeto',
    rename: 'Renomear',
    duplicate: 'Duplicar',
    renameFailed: 'Falha ao renomear',
    emptyStarred: 'Nenhum favorito — passe o cursor sobre uma linha e clique na estrela.',
    emptyRecent: 'Nenhum arquivo recente — crie ou abra um arquivo para começar.',
    emptyFiltered: 'Nenhum arquivo deste tipo.',
    deleteModalTitle: 'Excluir arquivos',
    deleteConfirmOne: 'Mover "{name}" para a lixeira?',
    deleteConfirmMany: 'Mover estes {n} arquivos para a lixeira?',
    deleteMoreCount: '… {n} no total',
    delete: 'Excluir',
    projects: 'Projetos',
    newProject: 'Novo projeto',
    projectName: 'Nome do projeto',
    deleteProject: 'Excluir projeto…',
    deleteProjectConfirm:
      'Excluir este projeto?\nSeus arquivos voltarão ao projeto padrão e não serão perdidos.',
    projMoreActions: 'Mais ações para {name}',
    defaultProject: 'Projeto padrão',
    projEmpty:
      'Mantenha documentos relacionados em um mesmo projeto — o histórico de conversas com a IA se acumula por projeto.',
    projEmptyHint:
      'Crie um arquivo ou clique com o botão direito em um arquivo recente e escolha "Mover para um projeto".',
    timelineCount: '{n} itens',
    timelineCountOne: '{n} item',
    timelineEmpty: 'Ainda não há conversas com a IA neste projeto.',
    timelineYou: 'Você',
    timelineUserAria: 'Usuário',
    untitled: 'Sem título',
    noContent: '(vazio)',
    appVersion: 'Versão {v}',
    versionLabel: 'Versão',
    aboutAuthor: 'Autor',
    starOnGitHub: 'Estrelar no GitHub',
    theme: 'Tema',
    themeLight: 'Claro',
    themeDark: 'Escuro',
    themeSystem: 'Seguir o Sistema',
    saveLocation: 'Local de salvamento',
    settings: 'Configurações',
    setSecGeneral: 'Geral',
    setSecProviders: 'Provedores de modelos',
    setLogin: 'Entrar',
    setOauthWaiting: 'A página de login foi aberta no navegador — conclua ou cole a URL abaixo',
    setOauthPastePlaceholder: 'Colar URL de redirecionamento ou código…',
    setTestFailTip: 'Não foi possível conectar — verifique a chave API ou a assinatura',
    setEnableNeedsTest: 'Ative após o teste de conectividade',
    setBedrockHint: 'O Amazon Bedrock usa credenciais AWS (perfil, chaves IAM, token bearer ou função) — não há uma chave de API única. Configure as credenciais AWS no seu ambiente.',
    setEnable: 'Ativar',
    setProxy: 'Proxy de rede',
    setProxyEnable: 'Ativar proxy',
    setProxyAuto: 'Vazio = usar o proxy do sistema',
    setProxyNoDetect: 'Vazio = detecção automática; nenhum proxy do sistema encontrado',
    setInUse: 'Em uso',
    setEdit: 'Editar',
    setBaseUrlLabel: 'Base URL',
    setBaseUrlPlaceholder: 'Deixe vazio para o endpoint padrão',
    setConnFailedTip: 'Falha na conexão — verifique a chave de API ou a URL base',
    tabHome: 'Início',
    setProviderSearch: 'Pesquisar provedores…',
    setConfigTitle: 'Configurar {name}',
    setApiKeyLabel: 'API Key',
    setModelLabel: 'Modelo',
    setModelPlaceholder: 'Insira o ID do modelo',
    setSecImageGen: 'Geração de imagens',
    setKeyConfigured: 'Configurado',
    setKeyMissing: 'Não configurado',
    setKeyPlaceholder: 'Colar chave de API…',
    setKeyTest: 'Testar',
    setKeyTestOk: 'Conexão OK',
    setKeyTestFail: 'Falha na conexão',
    setKeyClear: 'Limpar',
    setKeySaved: 'Salvo',
    setKeyCleared: 'Limpo',
    setSave: 'Salvar',
    setProvidersEmpty: 'Nenhum provedor encontrado (SDK do agente não carregado)',
    setImageGenHint: 'Escolha o backend de imagens para a ferramenta do agente; as chaves são reutilizadas do provedor correspondente acima.',
    setSecAbout: 'Sobre',
    setChange: 'Alterar',
    today: 'Hoje',
    yesterday: 'Ontem',
    daysAgo: 'há {n} dias',
    language: 'Idioma',
    closeTab: 'Fechar guia',
    tabList: 'Todas as guias',
    newTab: 'Nova guia',
  },
  it: {
    navRecent: 'Recenti',
    navStarred: 'Preferiti',
    cloudSortRecent: 'Recenti',
    cloudSortOldest: 'Meno recenti',
    navTrash: 'Cestino',
    navTrashTip:
      'I file eliminati vengono spostati nel cestino di sistema e possono essere ripristinati da lì',
    secQuickStart: 'Avvio rapido',
    secRecent: 'Recenti',
    secStarred: 'Preferiti',
    secProjectFiles: 'File del progetto',
    secActivity: 'Attività',
    colName: 'Nome',
    colLocation: 'Posizione',
    colModified: 'Modificato',
    colSize: 'Dimensione',
    openLocal: 'Apri file locale',
    quickAiPpt: 'AI PPT',
    quickAiPptSub: 'Genera una presentazione professionale da una frase',
    greetMorning: 'Buongiorno',
    greetAfternoon: 'Buon pomeriggio',
    greetEvening: 'Buonasera',
    greetAsk1: 'Cosa vuoi creare oggi?',
    greetAsk2: 'Pronto per iniziare?',
    greetAsk3: 'Su cosa stai lavorando?',
    greetAsk4: 'Da dove iniziamo oggi?',
    greetAsk5: 'Vuoi creare qualcosa di nuovo?',
    greetAsk6: "Hai un'idea?",
    filterAll: 'Tutti',
    filterSlides: 'Presentazioni',
    filterAria: 'Filtra per tipo',
    fileCount: '{n} file',
    fileCountOne: '{n} file',
    selectedCount: '{n} selezionati',
    selectAll: 'Seleziona tutto',
    selectFile: 'Seleziona {name}',
    removeFromList: "Rimuovi dall'elenco",
    deleteFiles: 'Elimina file',
    cancel: 'Annulla',
    star: 'Aggiungi ai preferiti',
    unstar: 'Rimuovi dai preferiti',
    moreActions: 'Altre azioni',
    open: 'Apri',
    revealInFolder: 'Mostra nella cartella',
    copyPath: 'Copia percorso',
    moveToProject: 'Sposta in un progetto',
    rename: 'Rinomina',
    duplicate: 'Duplica',
    renameFailed: 'Impossibile rinominare',
    emptyStarred: 'Nessun preferito — passa il cursore su una riga e fai clic sulla stella.',
    emptyRecent: 'Nessun file recente — crea o apri un file per iniziare.',
    emptyFiltered: 'Nessun file di questo tipo.',
    deleteModalTitle: 'Elimina file',
    deleteConfirmOne: 'Spostare "{name}" nel cestino?',
    deleteConfirmMany: 'Spostare questi {n} file nel cestino?',
    deleteMoreCount: '… {n} in totale',
    delete: 'Elimina',
    projects: 'Progetti',
    newProject: 'Nuovo progetto',
    projectName: 'Nome del progetto',
    deleteProject: 'Elimina progetto…',
    deleteProjectConfirm:
      'Eliminare questo progetto?\nI suoi file torneranno nel progetto predefinito e non andranno persi.',
    projMoreActions: 'Altre azioni per {name}',
    defaultProject: 'Progetto predefinito',
    projEmpty:
      'Tieni i documenti correlati in uno stesso progetto — la cronologia delle chat IA si accumula per progetto.',
    projEmptyHint:
      'Crea un file oppure fai clic con il pulsante destro su un file recente e scegli "Sposta in un progetto".',
    timelineCount: '{n} elementi',
    timelineCountOne: '{n} elemento',
    timelineEmpty: 'Non ci sono ancora conversazioni IA in questo progetto.',
    timelineYou: 'Tu',
    timelineUserAria: 'Utente',
    untitled: 'Senza titolo',
    noContent: '(vuoto)',
    appVersion: 'Versione {v}',
    versionLabel: 'Versione',
    aboutAuthor: 'Autore',
    starOnGitHub: 'Metti una stella su GitHub',
    theme: 'Tema',
    themeLight: 'Chiaro',
    themeDark: 'Scuro',
    themeSystem: 'Segui il sistema',
    saveLocation: 'Posizione di salvataggio',
    settings: 'Impostazioni',
    setSecGeneral: 'Generale',
    setSecProviders: 'Provider di modelli',
    setLogin: 'Accedi',
    setOauthWaiting: "Pagina di accesso aperta nel browser — completa o incolla l'URL qui sotto",
    setOauthPastePlaceholder: 'Incolla URL di reindirizzamento o codice…',
    setTestFailTip: "Connessione non riuscita — controlla la chiave API o l'abbonamento",
    setEnableNeedsTest: 'Attivabile dopo il test di connessione',
    setBedrockHint: "Amazon Bedrock usa le credenziali AWS (profilo, chiavi IAM, bearer token o ruolo) — nessuna chiave API singola. Configura le credenziali AWS nell'ambiente.",
    setEnable: 'Attiva',
    setProxy: 'Proxy di rete',
    setProxyEnable: 'Attiva proxy',
    setProxyAuto: 'Vuoto = usa il proxy di sistema',
    setProxyNoDetect: 'Vuoto = rilevamento automatico; nessun proxy di sistema trovato',
    setInUse: 'In uso',
    setEdit: 'Modifica',
    setBaseUrlLabel: 'Base URL',
    setBaseUrlPlaceholder: "Lascia vuoto per l'endpoint predefinito",
    setConnFailedTip: "Connessione non riuscita — controlla la chiave API o l'URL di base",
    tabHome: 'Home',
    setProviderSearch: 'Cerca provider…',
    setConfigTitle: 'Configura {name}',
    setApiKeyLabel: 'API Key',
    setModelLabel: 'Modello',
    setModelPlaceholder: 'Inserisci ID modello',
    setSecImageGen: 'Generazione immagini',
    setKeyConfigured: 'Configurato',
    setKeyMissing: 'Non configurato',
    setKeyPlaceholder: 'Incolla la chiave API…',
    setKeyTest: 'Testa',
    setKeyTestOk: 'Connessione riuscita',
    setKeyTestFail: 'Connessione fallita',
    setKeyClear: 'Cancella',
    setKeySaved: 'Salvato',
    setKeyCleared: 'Cancellato',
    setSave: 'Salva',
    setProvidersEmpty: 'Nessun provider trovato (SDK agente non caricato)',
    setImageGenHint: 'Scegli il backend immagini per lo strumento dell\'agente; le chiavi sono condivise con il provider corrispondente sopra.',
    setSecAbout: 'Informazioni',
    setChange: 'Cambia',
    today: 'Oggi',
    yesterday: 'Ieri',
    daysAgo: '{n} giorni fa',
    language: 'Lingua',
    closeTab: 'Chiudi scheda',
    tabList: 'Tutte le schede',
    newTab: 'Nuova scheda',
  },
  pl: {
    navRecent: 'Ostatnie',
    navStarred: 'Ulubione',
    cloudSortRecent: 'Najnowsze',
    cloudSortOldest: 'Najstarsze',
    navTrash: 'Kosz',
    navTrashTip: 'Usunięte pliki trafiają do systemowego kosza i można je stamtąd przywrócić',
    secQuickStart: 'Szybki start',
    secRecent: 'Ostatnie',
    secStarred: 'Ulubione',
    secProjectFiles: 'Pliki projektu',
    secActivity: 'Aktywność',
    colName: 'Nazwa',
    colLocation: 'Lokalizacja',
    colModified: 'Zmodyfikowano',
    colSize: 'Rozmiar',
    openLocal: 'Otwórz plik lokalny',
    quickAiPpt: 'AI PPT',
    quickAiPptSub: 'Wygeneruj profesjonalną prezentację z jednego zdania',
    greetMorning: 'Dzień dobry',
    greetAfternoon: 'Dzień dobry',
    greetEvening: 'Dobry wieczór',
    greetAsk1: 'Co chcesz dziś stworzyć?',
    greetAsk2: 'Gotowy, aby zacząć?',
    greetAsk3: 'Nad czym pracujesz?',
    greetAsk4: 'Od czego dziś zaczniemy?',
    greetAsk5: 'Masz ochotę stworzyć coś nowego?',
    greetAsk6: 'Masz jakiś pomysł?',
    filterAll: 'Wszystkie',
    filterSlides: 'Prezentacje',
    filterAria: 'Filtruj według typu',
    fileCount: 'Pliki: {n}',
    fileCountOne: '{n} plik',
    selectedCount: 'Wybrano: {n}',
    selectAll: 'Zaznacz wszystko',
    selectFile: 'Zaznacz {name}',
    removeFromList: 'Usuń z listy',
    deleteFiles: 'Usuń pliki',
    cancel: 'Anuluj',
    star: 'Dodaj do ulubionych',
    unstar: 'Usuń z ulubionych',
    moreActions: 'Więcej działań',
    open: 'Otwórz',
    revealInFolder: 'Pokaż w folderze',
    copyPath: 'Kopiuj ścieżkę',
    moveToProject: 'Przenieś do projektu',
    rename: 'Zmień nazwę',
    duplicate: 'Utwórz kopię',
    renameFailed: 'Nie udało się zmienić nazwy',
    emptyStarred: 'Brak ulubionych — najedź kursorem na wiersz pliku i kliknij gwiazdkę.',
    emptyRecent: 'Brak ostatnich plików — utwórz lub otwórz plik, aby rozpocząć.',
    emptyFiltered: 'Brak plików tego typu.',
    deleteModalTitle: 'Usuwanie plików',
    deleteConfirmOne: 'Przenieść „{name}” do kosza?',
    deleteConfirmMany: 'Przenieść te pliki ({n}) do kosza?',
    deleteMoreCount: '… łącznie {n}',
    delete: 'Usuń',
    projects: 'Projekty',
    newProject: 'Nowy projekt',
    projectName: 'Nazwa projektu',
    deleteProject: 'Usuń projekt…',
    deleteProjectConfirm:
      'Usunąć ten projekt?\nJego pliki wrócą do projektu domyślnego i nie zostaną utracone.',
    projMoreActions: 'Więcej działań dla {name}',
    defaultProject: 'Projekt domyślny',
    projEmpty:
      'Trzymaj powiązane dokumenty w jednym projekcie — historia rozmów z AI gromadzi się dla każdego projektu.',
    projEmptyHint:
      'Utwórz plik lub kliknij ostatni plik prawym przyciskiem myszy i wybierz „Przenieś do projektu”.',
    timelineCount: 'Wpisy: {n}',
    timelineCountOne: '{n} wpis',
    timelineEmpty: 'W tym projekcie nie ma jeszcze rozmów z AI.',
    timelineYou: 'Ty',
    timelineUserAria: 'Użytkownik',
    untitled: 'Bez tytułu',
    noContent: '(pusto)',
    appVersion: 'Wersja {v}',
    versionLabel: 'Wersja',
    aboutAuthor: 'Autor',
    starOnGitHub: 'Dodaj gwiazdkę na GitHub',
    theme: 'Motyw',
    themeLight: 'Jasny',
    themeDark: 'Ciemny',
    themeSystem: 'Zgodnie z systemem',
    saveLocation: 'Lokalizacja zapisu',
    settings: 'Ustawienia',
    setSecGeneral: 'Ogólne',
    setSecProviders: 'Dostawcy modeli',
    setLogin: 'Zaloguj się',
    setOauthWaiting: 'Strona logowania otwarta w przeglądarce — dokończ lub wklej URL poniżej',
    setOauthPastePlaceholder: 'Wklej URL przekierowania lub kod…',
    setTestFailTip: 'Nie można połączyć — sprawdź klucz API lub subskrypcję',
    setEnableNeedsTest: 'Włączalne po pomyślnym teście łączności',
    setBedrockHint: 'Amazon Bedrock używa poświadczeń AWS (profil, klucze IAM, token bearer lub rola) — brak pojedynczego klucza API. Skonfiguruj poświadczenia AWS w środowisku.',
    setEnable: 'Włącz',
    setProxy: 'Serwer proxy',
    setProxyEnable: 'Włącz proxy',
    setProxyAuto: 'Puste = użyj proxy systemowego',
    setProxyNoDetect: 'Puste = wykryj automatycznie; nie wykryto proxy systemowego',
    setInUse: 'W użyciu',
    setEdit: 'Edytuj',
    setBaseUrlLabel: 'Base URL',
    setBaseUrlPlaceholder: 'Pozostaw puste, aby użyć domyślnego endpointu',
    setConnFailedTip: 'Nie można połączyć — sprawdź klucz API lub Base URL',
    tabHome: 'Strona główna',
    setProviderSearch: 'Szukaj dostawców…',
    setConfigTitle: 'Konfiguruj {name}',
    setApiKeyLabel: 'API Key',
    setModelLabel: 'Model',
    setModelPlaceholder: 'Wpisz ID modelu',
    setSecImageGen: 'Generowanie obrazów',
    setKeyConfigured: 'Skonfigurowano',
    setKeyMissing: 'Nieskonfigurowano',
    setKeyPlaceholder: 'Wklej klucz API…',
    setKeyTest: 'Testuj',
    setKeyTestOk: 'Połączono',
    setKeyTestFail: 'Błąd połączenia',
    setKeyClear: 'Wyczyść',
    setKeySaved: 'Zapisano',
    setKeyCleared: 'Wyczyszczono',
    setSave: 'Zapisz',
    setProvidersEmpty: 'Nie znaleziono dostawców (SDK agenta niezaładowany)',
    setImageGenHint: 'Wybierz backend obrazów dla narzędzia agenta; klucze są współdzielone z odpowiednim dostawcą powyżej.',
    setSecAbout: 'O aplikacji',
    setChange: 'Zmień',
    today: 'Dzisiaj',
    yesterday: 'Wczoraj',
    daysAgo: '{n} dni temu',
    language: 'Język',
    closeTab: 'Zamknij kartę',
    tabList: 'Wszystkie karty',
    newTab: 'Nowa karta',
  },
  nl: {
    navRecent: 'Recent',
    navStarred: 'Favorieten',
    cloudSortRecent: 'Recent',
    cloudSortOldest: 'Oudste',
    navTrash: 'Prullenbak',
    navTrashTip:
      'Verwijderde bestanden gaan naar de systeemprullenbak en kunnen daar worden hersteld',
    secQuickStart: 'Snel starten',
    secRecent: 'Recent',
    secStarred: 'Favorieten',
    secProjectFiles: 'Projectbestanden',
    secActivity: 'Activiteit',
    colName: 'Naam',
    colLocation: 'Locatie',
    colModified: 'Gewijzigd',
    colSize: 'Grootte',
    openLocal: 'Lokaal bestand openen',
    quickAiPpt: 'AI PPT',
    quickAiPptSub: 'Genereer een professionele presentatie met één zin',
    greetMorning: 'Goedemorgen',
    greetAfternoon: 'Goedemiddag',
    greetEvening: 'Goedenavond',
    greetAsk1: 'Wat wil je vandaag maken?',
    greetAsk2: 'Klaar om te beginnen?',
    greetAsk3: 'Waar werk je aan?',
    greetAsk4: 'Waar beginnen we vandaag?',
    greetAsk5: 'Zin om iets nieuws te maken?',
    greetAsk6: 'Al een idee?',
    filterAll: 'Alle',
    filterSlides: 'Presentaties',
    filterAria: 'Filteren op type',
    fileCount: '{n} bestanden',
    fileCountOne: '{n} bestand',
    selectedCount: '{n} geselecteerd',
    selectAll: 'Alles selecteren',
    selectFile: '{name} selecteren',
    removeFromList: 'Uit lijst verwijderen',
    deleteFiles: 'Bestanden verwijderen',
    cancel: 'Annuleren',
    star: 'Aan favorieten toevoegen',
    unstar: 'Uit favorieten verwijderen',
    moreActions: 'Meer acties',
    open: 'Openen',
    revealInFolder: 'Tonen in map',
    copyPath: 'Pad kopiëren',
    moveToProject: 'Naar project verplaatsen',
    rename: 'Naam wijzigen',
    duplicate: 'Dupliceren',
    renameFailed: 'Naam wijzigen mislukt',
    emptyStarred: 'Geen favorieten — beweeg de muis over een rij en klik op de ster.',
    emptyRecent: 'Geen recente bestanden — maak of open een bestand om te beginnen.',
    emptyFiltered: 'Geen bestanden van dit type.',
    deleteModalTitle: 'Bestanden verwijderen',
    deleteConfirmOne: '"{name}" naar de prullenbak verplaatsen?',
    deleteConfirmMany: 'Deze {n} bestanden naar de prullenbak verplaatsen?',
    deleteMoreCount: '… {n} in totaal',
    delete: 'Verwijderen',
    projects: 'Projecten',
    newProject: 'Nieuw project',
    projectName: 'Projectnaam',
    deleteProject: 'Project verwijderen…',
    deleteProjectConfirm:
      'Dit project verwijderen?\nDe bestanden gaan terug naar het standaardproject en gaan niet verloren.',
    projMoreActions: 'Meer acties voor {name}',
    defaultProject: 'Standaardproject',
    projEmpty:
      'Bewaar gerelateerde documenten in één project — de AI-chatgeschiedenis wordt per project opgebouwd.',
    projEmptyHint:
      'Maak een bestand, of klik met de rechtermuisknop op een recent bestand en kies "Naar project verplaatsen".',
    timelineCount: '{n} items',
    timelineCountOne: '{n} item',
    timelineEmpty: 'Nog geen AI-gesprekken in dit project.',
    timelineYou: 'Jij',
    timelineUserAria: 'Gebruiker',
    untitled: 'Naamloos',
    noContent: '(leeg)',
    appVersion: 'Versie {v}',
    versionLabel: 'Versie',
    aboutAuthor: 'Auteur',
    starOnGitHub: 'Ster op GitHub',
    theme: 'Thema',
    themeLight: 'Licht',
    themeDark: 'Donker',
    themeSystem: 'Systeem volgen',
    saveLocation: 'Opslaglocatie',
    settings: 'Instellingen',
    setSecGeneral: 'Algemeen',
    setSecProviders: 'Modelproviders',
    setLogin: 'Inloggen',
    setOauthWaiting: 'Inlogpagina geopend in de browser — voltooi of plak de URL hieronder',
    setOauthPastePlaceholder: 'Redirect-URL of code plakken…',
    setTestFailTip: 'Verbinding mislukt — controleer de API-sleutel of het abonnement',
    setEnableNeedsTest: 'Inschakelen na geslaagde connectiviteitstest',
    setBedrockHint: 'Amazon Bedrock gebruikt AWS-referenties (profiel, IAM-sleutels, bearer-token of rol) — er is geen enkele API-sleutel. Configureer AWS-referenties in je omgeving.',
    setEnable: 'Inschakelen',
    setProxy: 'Netwerkproxy',
    setProxyEnable: 'Proxy inschakelen',
    setProxyAuto: 'Leeg = systeemproxy automatisch gebruiken',
    setProxyNoDetect: 'Leeg = automatisch detecteren; geen systeemproxy gevonden',
    setInUse: 'In gebruik',
    setEdit: 'Bewerken',
    setBaseUrlLabel: 'Base URL',
    setBaseUrlPlaceholder: 'Leeg laten voor het standaard endpoint',
    setConnFailedTip: 'Verbinding mislukt — controleer de API-sleutel of Base URL',
    tabHome: 'Home',
    setProviderSearch: 'Providers zoeken…',
    setConfigTitle: '{name} configureren',
    setApiKeyLabel: 'API Key',
    setModelLabel: 'Model',
    setModelPlaceholder: 'Model-ID invoeren',
    setSecImageGen: 'Afbeeldingen genereren',
    setKeyConfigured: 'Geconfigureerd',
    setKeyMissing: 'Niet geconfigureerd',
    setKeyPlaceholder: 'Plak API-sleutel…',
    setKeyTest: 'Testen',
    setKeyTestOk: 'Verbinding OK',
    setKeyTestFail: 'Verbinding mislukt',
    setKeyClear: 'Wissen',
    setKeySaved: 'Opgeslagen',
    setKeyCleared: 'Gewist',
    setSave: 'Opslaan',
    setProvidersEmpty: 'Geen providers gevonden (agent-SDK niet geladen)',
    setImageGenHint: 'Kies de afbeeldingsbackend voor de agent-tool; sleutels worden gedeeld met de bijbehorende provider hierboven.',
    setSecAbout: 'Over',
    setChange: 'Wijzigen',
    today: 'Vandaag',
    yesterday: 'Gisteren',
    daysAgo: '{n} dagen geleden',
    language: 'Taal',
    closeTab: 'Tabblad sluiten',
    tabList: 'Alle tabbladen',
    newTab: 'Nieuw tabblad',
  },
  ms: {
    navRecent: 'Terkini',
    navStarred: 'Berbintang',
    cloudSortRecent: 'Terbaru',
    cloudSortOldest: 'Terlama',
    navTrash: 'Tong sampah',
    navTrashTip:
      'Fail yang dipadamkan akan dipindahkan ke tong sampah sistem dan boleh dipulihkan dari sana',
    secQuickStart: 'Mula pantas',
    secRecent: 'Terkini',
    secStarred: 'Berbintang',
    secProjectFiles: 'Fail projek',
    secActivity: 'Aktiviti',
    colName: 'Nama',
    colLocation: 'Lokasi',
    colModified: 'Diubah suai',
    colSize: 'Saiz',
    openLocal: 'Buka Fail Setempat',
    quickAiPpt: 'AI PPT',
    quickAiPptSub: 'Jana pembentangan profesional daripada satu ayat',
    greetMorning: 'Selamat pagi',
    greetAfternoon: 'Selamat tengah hari',
    greetEvening: 'Selamat petang',
    greetAsk1: 'Apa yang anda mahu cipta hari ini?',
    greetAsk2: 'Sedia untuk bermula?',
    greetAsk3: 'Apa yang anda sedang usahakan?',
    greetAsk4: 'Dari mana kita mula hari ini?',
    greetAsk5: 'Mahu cipta sesuatu yang baharu?',
    greetAsk6: 'Ada idea?',
    filterAll: 'Semua',
    filterSlides: 'Persembahan',
    filterAria: 'Tapis mengikut jenis',
    fileCount: '{n} fail',
    fileCountOne: '{n} fail',
    selectedCount: '{n} dipilih',
    selectAll: 'Pilih semua',
    selectFile: 'Pilih {name}',
    removeFromList: 'Alih keluar daripada senarai',
    deleteFiles: 'Padam fail',
    cancel: 'Batal',
    star: 'Tambah bintang',
    unstar: 'Buang bintang',
    moreActions: 'Tindakan lain',
    open: 'Buka',
    revealInFolder: 'Tunjukkan dalam folder',
    copyPath: 'Salin laluan',
    moveToProject: 'Pindahkan ke projek',
    rename: 'Namakan semula',
    duplicate: 'Buat salinan',
    renameFailed: 'Gagal menamakan semula',
    emptyStarred: 'Belum ada fail berbintang — halakan kursor ke baris fail dan klik bintang.',
    emptyRecent: 'Belum ada fail terkini — cipta atau buka fail untuk bermula.',
    emptyFiltered: 'Tiada fail jenis ini.',
    deleteModalTitle: 'Padam Fail',
    deleteConfirmOne: 'Pindahkan "{name}" ke tong sampah?',
    deleteConfirmMany: 'Pindahkan {n} fail ini ke tong sampah?',
    deleteMoreCount: '… {n} kesemuanya',
    delete: 'Padam',
    projects: 'Projek',
    newProject: 'Projek baharu',
    projectName: 'Nama projek',
    deleteProject: 'Padam projek…',
    deleteProjectConfirm:
      'Padam projek ini?\nFail di dalamnya akan kembali ke Projek Lalai dan tidak akan hilang.',
    projMoreActions: 'Tindakan lain untuk {name}',
    defaultProject: 'Projek lalai',
    projEmpty:
      'Simpan dokumen berkaitan dalam satu projek — sejarah perbualan AI terkumpul mengikut projek.',
    projEmptyHint: 'Cipta fail, atau klik kanan fail terkini dan pilih "Pindahkan ke projek".',
    timelineCount: '{n} item',
    timelineCountOne: '{n} item',
    timelineEmpty: 'Belum ada perbualan AI dalam projek ini.',
    timelineYou: 'Anda',
    timelineUserAria: 'Pengguna',
    untitled: 'Tanpa tajuk',
    noContent: '(kosong)',
    appVersion: 'Versi {v}',
    versionLabel: 'Versi',
    aboutAuthor: 'Pengarang',
    starOnGitHub: 'Beri bintang di GitHub',
    theme: 'Tema',
    themeLight: 'Cerah',
    themeDark: 'Gelap',
    themeSystem: 'Ikut Sistem',
    saveLocation: 'Lokasi simpanan',
    settings: 'Tetapan',
    setSecGeneral: 'Umum',
    setSecProviders: 'Pembekal model',
    setLogin: 'Log Masuk',
    setOauthWaiting: 'Halaman log masuk dibuka dalam pelayar — selesaikan atau tampal URL di bawah',
    setOauthPastePlaceholder: 'Tampal URL ubah hala atau kod…',
    setTestFailTip: 'Tidak dapat disambungkan — semak kunci API atau langganan',
    setEnableNeedsTest: 'Dayakan selepas ujian kesambungan lulus',
    setBedrockHint: 'Amazon Bedrock menggunakan kelayakan AWS (profil, kunci IAM, token bearer atau peranan) — tiada kunci API tunggal. Konfigurasikan kelayakan AWS dalam persekitaran anda.',
    setEnable: 'Dayakan',
    setProxy: 'Proksi rangkaian',
    setProxyEnable: 'Dayakan proksi',
    setProxyAuto: 'Kosong = guna proksi sistem secara automatik',
    setProxyNoDetect: 'Kosong = kesan automatik; tiada proksi sistem ditemui',
    setInUse: 'Sedang digunakan',
    setEdit: 'Edit',
    setBaseUrlLabel: 'Base URL',
    setBaseUrlPlaceholder: 'Kosongkan untuk endpoint lalai',
    setConnFailedTip: 'Tidak dapat disambung — semak kunci API atau Base URL',
    tabHome: 'Laman Utama',
    setProviderSearch: 'Cari pembekal…',
    setConfigTitle: 'Konfigurasi {name}',
    setApiKeyLabel: 'API Key',
    setModelLabel: 'Model',
    setModelPlaceholder: 'Masukkan ID model',
    setSecImageGen: 'Penjanaan imej',
    setKeyConfigured: 'Dikonfigurasi',
    setKeyMissing: 'Belum dikonfigurasi',
    setKeyPlaceholder: 'Tampal kunci API…',
    setKeyTest: 'Uji',
    setKeyTestOk: 'Sambungan berjaya',
    setKeyTestFail: 'Sambungan gagal',
    setKeyClear: 'Kosongkan',
    setKeySaved: 'Disimpan',
    setKeyCleared: 'Dikosongkan',
    setSave: 'Simpan',
    setProvidersEmpty: 'Tiada pembekal ditemui (SDK ejen tidak dimuatkan)',
    setImageGenHint: 'Pilih backend imej untuk alat ejen; kunci dikongsi dengan pembekal yang sepadan di atas.',
    setSecAbout: 'Perihal',
    setChange: 'Tukar',
    today: 'Hari ini',
    yesterday: 'Semalam',
    daysAgo: '{n} hari lalu',
    language: 'Bahasa',
    closeTab: 'Tutup tab',
    tabList: 'Semua tab',
    newTab: 'Tab baharu',
  },
  he: {
    navRecent: 'אחרונים',
    navStarred: 'מועדפים',
    cloudSortRecent: 'החדשים ביותר',
    cloudSortOldest: 'הישנים ביותר',
    navTrash: 'אשפה',
    navTrashTip: 'קבצים שנמחקו עוברים לאשפה של המערכת וניתן לשחזר אותם משם',
    secQuickStart: 'התחלה מהירה',
    secRecent: 'אחרונים',
    secStarred: 'מועדפים',
    secProjectFiles: 'קובצי הפרויקט',
    secActivity: 'פעילות',
    colName: 'שם',
    colLocation: 'מיקום',
    colModified: 'שונה',
    colSize: 'גודל',
    openLocal: 'פתיחת קובץ מקומי',
    quickAiPpt: 'AI PPT',
    quickAiPptSub: 'צור מצגת מקצועית ממשפט אחד',
    greetMorning: 'בוקר טוב',
    greetAfternoon: 'צהריים טובים',
    greetEvening: 'ערב טוב',
    greetAsk1: 'מה תרצו ליצור היום?',
    greetAsk2: 'מוכנים להתחיל?',
    greetAsk3: 'על מה אתם עובדים?',
    greetAsk4: 'מאיפה נתחיל היום?',
    greetAsk5: 'רוצים ליצור משהו חדש?',
    greetAsk6: 'יש לכם רעיון?',
    filterAll: 'הכול',
    filterSlides: 'מצגות',
    filterAria: 'סינון לפי סוג',
    fileCount: '{n} קבצים',
    fileCountOne: 'קובץ אחד',
    selectedCount: 'נבחרו {n}',
    selectAll: 'בחירת הכול',
    selectFile: 'בחירת {name}',
    removeFromList: 'הסרה מהרשימה',
    deleteFiles: 'מחיקת קבצים',
    cancel: 'ביטול',
    star: 'הוספה למועדפים',
    unstar: 'הסרה מהמועדפים',
    moreActions: 'פעולות נוספות',
    open: 'פתיחה',
    revealInFolder: 'הצגה בתיקייה',
    copyPath: 'העתקת נתיב',
    moveToProject: 'העברה לפרויקט',
    rename: 'שינוי שם',
    duplicate: 'יצירת עותק',
    renameFailed: 'שינוי השם נכשל',
    emptyStarred: 'אין מועדפים עדיין — רחפו מעל שורת קובץ ולחצו על הכוכב.',
    emptyRecent: 'אין קבצים אחרונים — צרו או פתחו קובץ כדי להתחיל.',
    emptyFiltered: 'אין קבצים מסוג זה.',
    deleteModalTitle: 'מחיקת קבצים',
    deleteConfirmOne: 'להעביר את "{name}" לאשפה?',
    deleteConfirmMany: 'להעביר את {n} הקבצים האלה לאשפה?',
    deleteMoreCount: '… {n} בסך הכול',
    delete: 'מחיקה',
    projects: 'פרויקטים',
    newProject: 'פרויקט חדש',
    projectName: 'שם הפרויקט',
    deleteProject: 'מחיקת פרויקט…',
    deleteProjectConfirm:
      'למחוק את הפרויקט הזה?\nהקבצים שבו יחזרו ל"פרויקט ברירת המחדל" ולא יאבדו.',
    projMoreActions: 'פעולות נוספות עבור {name}',
    defaultProject: 'פרויקט ברירת מחדל',
    projEmpty: 'שמרו מסמכים קשורים באותו פרויקט — היסטוריית שיחות ה-AI נצברת לפי פרויקט.',
    projEmptyHint: 'צרו קובץ, או לחצו לחיצה ימנית על קובץ אחרון ובחרו "העברה לפרויקט".',
    timelineCount: '{n} פריטים',
    timelineCountOne: 'פריט אחד',
    timelineEmpty: 'אין עדיין שיחות AI בפרויקט הזה.',
    timelineYou: 'את/ה',
    timelineUserAria: 'משתמש',
    untitled: 'ללא שם',
    noContent: '(ריק)',
    appVersion: 'גרסה {v}',
    versionLabel: 'גרסה',
    aboutAuthor: 'מחבר',
    starOnGitHub: 'סמן כוכב ב-GitHub',
    theme: 'ערכת נושא',
    themeLight: 'בהיר',
    themeDark: 'כהה',
    themeSystem: 'עקוב אחר המערכת',
    saveLocation: 'מיקום שמירה',
    settings: 'הגדרות',
    setSecGeneral: 'כללי',
    setSecProviders: 'ספקי מודלים',
    setLogin: 'התחבר',
    setOauthWaiting: 'דף הכניסה נפתח בדפדפן — השלם או הדבק את ה-URL למטה',
    setOauthPastePlaceholder: 'הדבק URL הפניה או קוד…',
    setTestFailTip: 'לא ניתן להתחבר — בדוק את מפתח ה-API או את המנוי',
    setEnableNeedsTest: 'לאחר בדיקת קישוריות מוצלחת',
    setBedrockHint: 'Amazon Bedrock משתמש באישורי AWS (פרופיל, מפתחות IAM, bearer token או תפקיד) — אין מפתח API יחיד. הגדר אישורי AWS בסביבה שלך.',
    setEnable: 'הפעל',
    setProxy: 'פרוקסי רשת',
    setProxyEnable: 'הפעל פרוקסי',
    setProxyAuto: 'ריק = השתמש בפרוקסי המערכת',
    setProxyNoDetect: 'ריק = זיהוי אוטומטי; לא נמצא פרוקסי מערכת',
    setInUse: 'בשימוש',
    setEdit: 'עריכה',
    setBaseUrlLabel: 'Base URL',
    setBaseUrlPlaceholder: 'השאר ריק לנקודת הקצה ברירת המחדל',
    setConnFailedTip: 'החיבור נכשל — בדקו את מפתח ה-API או את Base URL',
    tabHome: 'בית',
    setProviderSearch: 'חיפוש ספקים…',
    setConfigTitle: 'הגדרת {name}',
    setApiKeyLabel: 'API Key',
    setModelLabel: 'מודל',
    setModelPlaceholder: 'הזן מזהה מודל',
    setSecImageGen: 'יצירת תמונות',
    setKeyConfigured: 'מוגדר',
    setKeyMissing: 'לא מוגדר',
    setKeyPlaceholder: 'הדביקו מפתח API…',
    setKeyTest: 'בדיקה',
    setKeyTestOk: 'החיבור הצליח',
    setKeyTestFail: 'החיבור נכשל',
    setKeyClear: 'ניקוי',
    setKeySaved: 'נשמר',
    setKeyCleared: 'נוקה',
    setSave: 'שמירה',
    setProvidersEmpty: 'לא נמצאו ספקים (SDK הסוכן לא נטען)',
    setImageGenHint: 'בחרו את מנוע יצירת התמונות לכלי הסוכן; המפתחות משותפים עם הספק המתאים למעלה.',
    setSecAbout: 'אודות',
    setChange: 'שינוי',
    today: 'היום',
    yesterday: 'אתמול',
    daysAgo: 'לפני {n} ימים',
    language: 'שפה',
    closeTab: 'סגירת כרטיסייה',
    tabList: 'כל הכרטיסיות',
    newTab: 'כרטיסייה חדשה',
  },
  hi: {
    navRecent: 'हाल के',
    navStarred: 'तारांकित',
    cloudSortRecent: 'हाल के',
    cloudSortOldest: 'सबसे पुराने',
    navTrash: 'ट्रैश',
    navTrashTip: 'हटाई गई फ़ाइलें सिस्टम ट्रैश में जाती हैं और वहाँ से पुनर्स्थापित की जा सकती हैं',
    secQuickStart: 'त्वरित प्रारंभ',
    secRecent: 'हाल के',
    secStarred: 'तारांकित',
    secProjectFiles: 'प्रोजेक्ट फ़ाइलें',
    secActivity: 'गतिविधि',
    colName: 'नाम',
    colLocation: 'स्थान',
    colModified: 'संशोधित',
    colSize: 'आकार',
    openLocal: 'स्थानीय फ़ाइल खोलें',
    quickAiPpt: 'AI PPT',
    quickAiPptSub: 'एक वाक्य से प्रोफ़ेशनल प्रेज़ेंटेशन बनाएं',
    greetMorning: 'सुप्रभात',
    greetAfternoon: 'नमस्ते',
    greetEvening: 'शुभ संध्या',
    greetAsk1: 'आज आप क्या बनाना चाहेंगे?',
    greetAsk2: 'शुरू करने के लिए तैयार?',
    greetAsk3: 'आप किस पर काम कर रहे हैं?',
    greetAsk4: 'आज कहाँ से शुरू करें?',
    greetAsk5: 'कुछ नया बनाना चाहेंगे?',
    greetAsk6: 'कोई आइडिया है?',
    filterAll: 'सभी',
    filterSlides: 'प्रस्तुतियाँ',
    filterAria: 'प्रकार के अनुसार फ़िल्टर करें',
    fileCount: '{n} फ़ाइलें',
    fileCountOne: '{n} फ़ाइल',
    selectedCount: '{n} चयनित',
    selectAll: 'सभी चुनें',
    selectFile: '{name} चुनें',
    removeFromList: 'सूची से हटाएँ',
    deleteFiles: 'फ़ाइलें हटाएँ',
    cancel: 'रद्द करें',
    star: 'तारांकित करें',
    unstar: 'तारांकन हटाएँ',
    moreActions: 'अधिक कार्रवाइयाँ',
    open: 'खोलें',
    revealInFolder: 'फ़ोल्डर में दिखाएँ',
    copyPath: 'पथ कॉपी करें',
    moveToProject: 'प्रोजेक्ट में ले जाएँ',
    rename: 'नाम बदलें',
    duplicate: 'प्रतिलिपि बनाएँ',
    renameFailed: 'नाम बदलने में विफल',
    emptyStarred:
      'कोई तारांकित फ़ाइल नहीं — फ़ाइल की पंक्ति पर कर्सर ले जाएँ और तारे पर क्लिक करें।',
    emptyRecent: 'कोई हालिया फ़ाइल नहीं — शुरू करने के लिए कोई फ़ाइल बनाएँ या खोलें।',
    emptyFiltered: 'इस प्रकार की कोई फ़ाइल नहीं है।',
    deleteModalTitle: 'फ़ाइलें हटाएँ',
    deleteConfirmOne: '"{name}" को ट्रैश में ले जाएँ?',
    deleteConfirmMany: 'इन {n} फ़ाइलों को ट्रैश में ले जाएँ?',
    deleteMoreCount: '… कुल {n}',
    delete: 'हटाएँ',
    projects: 'प्रोजेक्ट',
    newProject: 'नया प्रोजेक्ट',
    projectName: 'प्रोजेक्ट का नाम',
    deleteProject: 'प्रोजेक्ट हटाएँ…',
    deleteProjectConfirm:
      'यह प्रोजेक्ट हटाएँ?\nइसकी फ़ाइलें "डिफ़ॉल्ट प्रोजेक्ट" में वापस चली जाएँगी और खोएँगी नहीं।',
    projMoreActions: '{name} के लिए अधिक कार्रवाइयाँ',
    defaultProject: 'डिफ़ॉल्ट प्रोजेक्ट',
    projEmpty:
      'संबंधित दस्तावेज़ों को एक ही प्रोजेक्ट में रखें — AI चैट इतिहास प्रोजेक्ट के अनुसार जमा होता है।',
    projEmptyHint:
      'कोई फ़ाइल बनाएँ, या किसी हालिया फ़ाइल पर राइट-क्लिक करके "प्रोजेक्ट में ले जाएँ" चुनें।',
    timelineCount: '{n} आइटम',
    timelineCountOne: '{n} आइटम',
    timelineEmpty: 'इस प्रोजेक्ट में अभी तक कोई AI बातचीत नहीं है।',
    timelineYou: 'आप',
    timelineUserAria: 'उपयोगकर्ता',
    untitled: 'बिना शीर्षक',
    noContent: '(खाली)',
    appVersion: 'संस्करण {v}',
    versionLabel: 'संस्करण',
    aboutAuthor: 'लेखक',
    starOnGitHub: 'GitHub पर स्टार करें',
    theme: 'थीम',
    themeLight: 'लाइट',
    themeDark: 'डार्क',
    themeSystem: 'सिस्टम का अनुसरण करें',
    saveLocation: 'सहेजने का स्थान',
    settings: 'सेटिंग्स',
    setSecGeneral: 'सामान्य',
    setSecProviders: 'मॉडल प्रदाता',
    setLogin: 'लॉग इन',
    setOauthWaiting: 'ब्राउज़र में लॉगिन पेज खुल गया है — पूरा करें या नीचे URL पेस्ट करें',
    setOauthPastePlaceholder: 'रीडायरेक्ट URL या कोड पेस्ट करें…',
    setTestFailTip: 'कनेक्ट नहीं हो सका — API key या सदस्यता जाँचें',
    setEnableNeedsTest: 'कनेक्टिविटी परीक्षण पास होने के बाद सक्षम करें',
    setBedrockHint: 'Amazon Bedrock AWS क्रेडेंशियल (प्रोफ़ाइल, IAM कुंजियाँ, bearer token या role) उपयोग करता है — कोई एकल API key नहीं। अपने वातावरण में AWS क्रेडेंशियल कॉन्फ़िगर करें।',
    setEnable: 'सक्षम करें',
    setProxy: 'नेटवर्क प्रॉक्सी',
    setProxyEnable: 'प्रॉक्सी सक्षम करें',
    setProxyAuto: 'खाली = सिस्टम प्रॉक्सी स्वतः उपयोग करें',
    setProxyNoDetect: 'खाली = स्वतः पहचान; कोई सिस्टम प्रॉक्सी नहीं मिला',
    setInUse: 'उपयोग में',
    setEdit: 'संपादित करें',
    setBaseUrlLabel: 'Base URL',
    setBaseUrlPlaceholder: 'डिफ़ॉल्ट endpoint के लिए खाली छोड़ें',
    setConnFailedTip: 'कनेक्ट नहीं हो सका — API key या Base URL जांचें',
    tabHome: 'होम',
    setProviderSearch: 'प्रदाता खोजें…',
    setConfigTitle: '{name} कॉन्फ़िगर करें',
    setApiKeyLabel: 'API Key',
    setModelLabel: 'मॉडल',
    setModelPlaceholder: 'मॉडल ID दर्ज करें',
    setSecImageGen: 'छवि निर्माण',
    setKeyConfigured: 'कॉन्फ़िगर किया गया',
    setKeyMissing: 'कॉन्फ़िगर नहीं',
    setKeyPlaceholder: 'API कुंजी पेस्ट करें…',
    setKeyTest: 'परीक्षण',
    setKeyTestOk: 'कनेक्शन सफल',
    setKeyTestFail: 'कनेक्शन विफल',
    setKeyClear: 'हटाएँ',
    setKeySaved: 'सहेजा गया',
    setKeyCleared: 'हटाया गया',
    setSave: 'सहेजें',
    setProvidersEmpty: 'कोई प्रदाता नहीं मिला (एजेंट SDK लोड नहीं हुआ)',
    setImageGenHint: 'एजेंट के चित्र टूल के लिए बैकएंड चुनें; कुंजियाँ ऊपर के संबंधित प्रदाता से साझा होती हैं।',
    setSecAbout: 'जानकारी',
    setChange: 'बदलें',
    today: 'आज',
    yesterday: 'कल',
    daysAgo: '{n} दिन पहले',
    language: 'भाषा',
    closeTab: 'टैब बंद करें',
    tabList: 'सभी टैब',
    newTab: 'नया टैब',
  },
  'zh-TW': {
    navRecent: '最近',
    navStarred: '收藏',
    cloudSortRecent: '最近',
    cloudSortOldest: '最早',
    navTrash: '垃圾桶',
    navTrashTip: '刪除的檔案會移至系統垃圾桶，可從那裡還原',
    secQuickStart: '快速開始',
    secRecent: '最近使用',
    secStarred: '收藏',
    secProjectFiles: '專案檔案',
    secActivity: '專案動態',
    colName: '名稱',
    colLocation: '位置',
    colModified: '修改時間',
    colSize: '大小',
    openLocal: '開啟本機檔案',
    quickAiPpt: 'AI PPT',
    quickAiPptSub: '用一句話生成專業簡報',
    greetMorning: '早安',
    greetAfternoon: '午安',
    greetEvening: '晚安',
    greetAsk1: '今天想建立點什麼？',
    greetAsk2: '準備好開始了嗎？',
    greetAsk3: '有什麼想做的嗎？',
    greetAsk4: '今天從哪裡開始？',
    greetAsk5: '想做點什麼新的？',
    greetAsk6: '靈感來了嗎？',
    filterAll: '全部',
    filterSlides: '簡報',
    filterAria: '依類型篩選',
    fileCount: '{n} 個檔案',
    fileCountOne: '{n} 個檔案',
    selectedCount: '已選 {n} 項',
    selectAll: '全選',
    selectFile: '選取 {name}',
    removeFromList: '從清單中移除',
    deleteFiles: '刪除檔案',
    cancel: '取消',
    star: '收藏',
    unstar: '取消收藏',
    moreActions: '更多動作',
    open: '開啟',
    revealInFolder: '開啟所在資料夾',
    copyPath: '複製路徑',
    moveToProject: '移至專案',
    rename: '重新命名',
    duplicate: '建立副本',
    renameFailed: '重新命名失敗',
    emptyStarred: '還沒有收藏 — 將游標移到檔案列並點按星號即可收藏。',
    emptyRecent: '暫無最近檔案 — 新增或開啟檔案即可開始使用。',
    emptyFiltered: '此類型下暫無檔案。',
    deleteModalTitle: '刪除檔案',
    deleteConfirmOne: '確定將「{name}」移至垃圾桶？',
    deleteConfirmMany: '確定將以下 {n} 個檔案移至垃圾桶？',
    deleteMoreCount: '… 等共 {n} 個',
    delete: '刪除',
    projects: '專案',
    newProject: '新增專案',
    projectName: '專案名稱',
    deleteProject: '刪除專案…',
    deleteProjectConfirm: '刪除此專案？\n專案內的檔案會回到「預設專案」，不會遺失。',
    projMoreActions: '{name} 更多動作',
    defaultProject: '預設專案',
    projEmpty: '把相關文件放進同一個專案，AI 對話紀錄會依專案累積。',
    projEmptyHint: '新增檔案，或在「最近」檔案上按右鍵選擇「移至專案」。',
    timelineCount: '{n} 筆',
    timelineCountOne: '{n} 筆',
    timelineEmpty: '此專案還沒有 AI 對話紀錄。',
    timelineYou: '你',
    timelineUserAria: '使用者',
    untitled: '未命名',
    noContent: '（無內容）',
    appVersion: '版本 {v}',
    versionLabel: '版本',
    aboutAuthor: '作者',
    starOnGitHub: '在 GitHub 上 Star',
    theme: '主題',
    themeLight: '淺色',
    themeDark: '深色',
    themeSystem: '跟隨系統',
    saveLocation: '預設儲存位置',
    settings: '設定',
    setSecGeneral: '一般',
    setSecProviders: '模型服務',
    setLogin: '登入',
    setOauthWaiting: '已在瀏覽器開啟登入頁，完成授權即可；也可以手動貼上重新導向網址',
    setOauthPastePlaceholder: '貼上重新導向網址或授權碼…',
    setTestFailTip: '無法連線，請檢查 API key 或訂閱狀態',
    setEnableNeedsTest: '通過連線測試後即可啟用',
    setBedrockHint: 'Amazon Bedrock 使用 AWS 憑證（profile、IAM 金鑰、bearer token 或角色），不支援單一 API key — 請先在環境中設定 AWS 憑證。',
    setEnable: '啟用',
    setProxy: '網路代理',
    setProxyEnable: '啟用代理',
    setProxyAuto: '留空則自動使用系統代理',
    setProxyNoDetect: '留空則自動偵測;未偵測到系統代理',
    setInUse: '使用中',
    setEdit: '編輯',
    setBaseUrlLabel: 'Base URL',
    setBaseUrlPlaceholder: '留空使用預設位址',
    setConnFailedTip: '無法連線，請檢查 API Key 或 Base URL',
    tabHome: '首頁',
    setProviderSearch: '搜尋供應商…',
    setConfigTitle: '設定 {name}',
    setApiKeyLabel: 'API Key',
    setModelLabel: '模型',
    setModelPlaceholder: '輸入模型 ID',
    setSecImageGen: '圖片生成',
    setKeyConfigured: '已設定',
    setKeyMissing: '未設定',
    setKeyPlaceholder: '貼上 API 金鑰…',
    setKeyTest: '測試',
    setKeyTestOk: '連線成功',
    setKeyTestFail: '連線失敗',
    setKeyClear: '清除',
    setKeySaved: '已儲存',
    setKeyCleared: '已清除',
    setSave: '儲存',
    setProvidersEmpty: '找不到供應商(代理 SDK 未載入)',
    setImageGenHint: '為代理的配圖工具選擇生圖後端;金鑰與上方對應供應商共用。',
    setSecAbout: '關於',
    setChange: '變更',
    today: '今天',
    yesterday: '昨天',
    daysAgo: '{n} 天前',
    language: '語言',
    closeTab: '關閉分頁',
    tabList: '全部分頁',
    newTab: '新分頁',
  },
} as const
